package main

import "core:fmt"
import "core:strings"

BANNER_OWNER :: "generated by tools/abi/generate_abi. do not edit"

builder_line :: proc(builder: ^strings.Builder, line := "")
{
	strings.write_string(builder, line)
	strings.write_byte(builder, '\n')
}

builder_format_line :: proc(builder: ^strings.Builder, format: string, args: ..any)
{
	fmt.sbprintf(builder, format, ..args)
	strings.write_byte(builder, '\n')
}

builder_result :: proc(builder: ^strings.Builder) -> string
{
	text := strings.to_string(builder^)
	if strings.has_suffix(text, "\n\n")
	{
		return text[:len(text) - 1]
	}
	return text
}

append_doc_comment :: proc(
	builder: ^strings.Builder,
	doc, details: string,
	params: []^Node = nil,
	return_doc: string = "",
)
{
	if doc == "" && details == "" && len(params) == 0 && return_doc == ""
	{
		return
	}
	builder_line(builder, "/**")
	if doc != ""
	{
		builder_format_line(builder, " * %s", doc)
	}
	if details != "" && details != doc
	{
		builder_line(builder, " *")
		builder_format_line(builder, " * %s", details)
	}
	if len(params) > 0
	{
		builder_line(builder, " *")
		for parameter in params
		{
			builder_format_line(
				builder,
				" * @param %s %s",
				field_string(parameter, "name"),
				field_string(parameter, "doc"),
			)
		}
	}
	if return_doc != ""
	{
		builder_line(builder, " *")
		builder_format_line(builder, " * @return %s", return_doc)
	}
	builder_line(builder, " */")
}

c_decl :: proc(field: ^Node) -> string
{
	count := node_field(field, "count")
	if count != nil
	{
		return fmt.aprintf("%s %s[%d]", field_string(field, "c_type"), field_string(field, "name"), node_integer(count))
	}
	return fmt.aprintf("%s %s", field_string(field, "c_type"), field_string(field, "name"))
}

header_include_path :: proc(manifest: ^Manifest, header: string) -> string
{
	path := field_string(header_spec(manifest, header), "path")
	prefix := "include/"
	if strings.has_prefix(path, prefix)
	{
		return path[len(prefix):]
	}
	return path
}

node_pointer_contains :: proc(items: []^Node, target: ^Node) -> External_Flag
{
	for item in items
	{
		if item == target
		{
			return .Enabled
		}
	}
	return .Disabled
}

ordered_structs :: proc(manifest: ^Manifest) -> ([dynamic]^Node, External_Flag, string)
{
	items := field_items(manifest.root, "structs")
	result: [dynamic]^Node
	for len(result) < len(items)
	{
		ready_items: [dynamic]^Node
		for item in items
		{
			if node_pointer_contains(result[:], item) == .Enabled
			{
				continue
			}
			ready: External_Flag = .Enabled
			for field in field_items(item, "fields")
			{
				named, pointer := c_named_type(field_string(field, "c_type"))
				dependency := find_named_item(items, named)
				if dependency != nil && dependency != item && pointer == .Disabled && node_pointer_contains(result[:], dependency) == .Disabled
				{
					ready = .Disabled
					break
				}
			}
			if ready == .Enabled
			{
				append(&ready_items, item)
			}
		}
		if len(ready_items) == 0
		{
			names: [dynamic]string
			for item in items
			{
				if node_pointer_contains(result[:], item) == .Disabled
				{
					append(&names, field_string(item, "name"))
				}
			}
			sort_strings(names[:])
			return result, .Disabled, fmt.aprintf("by-value C struct dependency cycle: %s", strings.join(names[:], ", "))
		}
		append(&result, ..ready_items[:])
	}
	return result, .Enabled, ""
}

sort_strings :: proc(values: []string)
{
	for index := 1; index < len(values); index += 1
	{
		current := values[index]
		position := index
		for position > 0 && strings.compare(current, values[position - 1]) < 0
		{
			values[position] = values[position - 1]
			position -= 1
		}
		values[position] = current
	}
}

append_api_macros :: proc(builder: ^strings.Builder, prefix: string)
{
	builder_line(builder, "#if defined(_WIN32)")
	builder_format_line(builder, "#  define %s_CALL __cdecl", prefix)
	builder_format_line(builder, "#  if defined(%s_BUILD_SHARED)", prefix)
	builder_format_line(builder, "#    define %s_API __declspec(dllexport)", prefix)
	builder_format_line(builder, "#  elif defined(%s_USE_SHARED)", prefix)
	builder_format_line(builder, "#    define %s_API __declspec(dllimport)", prefix)
	builder_line(builder, "#  else")
	builder_format_line(builder, "#    define %s_API", prefix)
	builder_line(builder, "#  endif")
	builder_line(builder, "#elif defined(__GNUC__) || defined(__clang__)")
	builder_format_line(builder, "#  define %s_CALL", prefix)
	builder_format_line(builder, "#  define %s_API __attribute__((visibility(\"default\")))", prefix)
	builder_line(builder, "#else")
	builder_format_line(builder, "#  define %s_CALL", prefix)
	builder_format_line(builder, "#  define %s_API", prefix)
	builder_line(builder, "#endif")
}

append_struct_definition :: proc(builder: ^strings.Builder, item: ^Node)
{
	append_doc_comment(builder, field_string(item, "doc"), field_string(item, "details"))
	builder_format_line(builder, "struct %s {{", field_string(item, "name"))
	for field, index in field_items(item, "fields")
	{
		doc := field_string(field, "doc")
		if doc != ""
		{
			builder_format_line(builder, "    /* %s */", doc)
		}
		alignment := field_integer(item, "explicit_alignment")
		if index == 0 && alignment > 0
		{
			builder_format_line(builder, "    ENTASIS_ALIGNAS(%d) %s;", alignment, c_decl(field))
		}
		else
		{
			builder_format_line(builder, "    %s;", c_decl(field))
		}
	}
	builder_line(builder, "};")
	builder_line(builder)
}

pre_callback_struct_names :: proc(manifest: ^Manifest, ordered: []^Node, header: string) -> [dynamic]string
{
	header_names: [dynamic]string
	result: [dynamic]string
	for item in ordered
	{
		if field_string(item, "header") == header
		{
			name := field_string(item, "name")
			append(&header_names, name)
			if field_flag(item, "pre_callbacks") == .Enabled
			{
				append(&result, name)
			}
		}
	}
	for callback in field_items(manifest.root, "callback_types")
	{
		if field_string(callback, "header") != header
		{
			continue
		}
		for parameter in field_items(callback, "params")
		{
			named, pointer := c_named_type(field_string(parameter, "c_type"))
			if pointer == .Disabled && contains_string(header_names[:], named) == .Enabled && contains_string(result[:], named) == .Disabled
			{
				append(&result, named)
			}
		}
		if field_string(callback, "return_c") != "void"
		{
			named, pointer := c_named_type(field_string(callback, "return_c"))
			if pointer == .Disabled && contains_string(header_names[:], named) == .Enabled && contains_string(result[:], named) == .Disabled
			{
				append(&result, named)
			}
		}
	}
	changed: External_Flag = .Enabled
	for changed == .Enabled
	{
		changed = .Disabled
		for name in result
		{
			item := find_named_item(ordered, name)
			for field in field_items(item, "fields")
			{
				named, pointer := c_named_type(field_string(field, "c_type"))
				if pointer == .Disabled && contains_string(header_names[:], named) == .Enabled && contains_string(result[:], named) == .Disabled
				{
					append(&result, named)
					changed = .Enabled
				}
			}
		}
	}
	return result
}

render_domain_header :: proc(manifest: ^Manifest, header: string) -> (string, External_Flag, string)
{
	ordered, ordered_status, ordered_error := ordered_structs(manifest)
	if ordered_status == .Disabled
	{
		return "", .Disabled, ordered_error
	}
	builder := strings.builder_make_len_cap(0, 32768)
	spec := header_spec(manifest, header)
	guard := field_string(spec, "guard")
	builder_format_line(&builder, "// %s", BANNER_OWNER)
	builder_format_line(&builder, "#ifndef %s", guard)
	builder_format_line(&builder, "#define %s", guard)
	builder_line(&builder)

	if header == "base"
	{
		builder_line(&builder, "#include <stddef.h>")
		builder_line(&builder, "#include <stdint.h>")
		builder_line(&builder)
		builder_line(&builder, "#if UINTPTR_MAX != UINT64_MAX")
		builder_line(&builder, "#  error \"Entasis ABI v1 requires a 64-bit target.\"")
		builder_line(&builder, "#endif")
		builder_line(&builder)
		append_api_macros(&builder, "ENTASIS")
		builder_line(&builder, "#if defined(__cplusplus)")
		builder_line(&builder, "#  define ENTASIS_ALIGNAS(bytes) alignas(bytes)")
		builder_line(&builder, "#elif defined(_MSC_VER)")
		builder_line(&builder, "#  define ENTASIS_ALIGNAS(bytes) __declspec(align(bytes))")
		builder_line(&builder, "#else")
		builder_line(&builder, "#  define ENTASIS_ALIGNAS(bytes) _Alignas(bytes)")
		builder_line(&builder, "#endif")
		builder_line(&builder)
	}
	else
	{
		for dependency in field_items(spec, "includes")
		{
			builder_format_line(&builder, "#include <%s>", header_include_path(manifest, node_string(dependency)))
		}
		if len(field_items(spec, "includes")) > 0
		{
			builder_line(&builder)
		}
		if header == "cooking"
		{
			append_api_macros(&builder, "ENTASIS_COOKING")
			builder_line(&builder)
		}
	}
	builder_line(&builder, "#ifdef __cplusplus")
	builder_line(&builder, "extern \"C\" {")
	builder_line(&builder, "#endif")
	builder_line(&builder)

	if header == "base"
	{
		product := node_field(manifest.root, "product")
		builder_line(&builder, "/* product major version */")
		builder_format_line(&builder, "#define ENTASIS_VERSION_MAJOR UINT16_C(%d)", field_integer(product, "version_major"))
		builder_line(&builder, "/* product minor version */")
		builder_format_line(&builder, "#define ENTASIS_VERSION_MINOR UINT16_C(%d)", field_integer(product, "version_minor"))
		builder_line(&builder, "/* product patch version */")
		builder_format_line(&builder, "#define ENTASIS_VERSION_PATCH UINT16_C(%d)", field_integer(product, "version_patch"))
		builder_line(&builder, "/* product prerelease identifier, empty for a stable release */")
		builder_format_line(&builder, "#define ENTASIS_VERSION_PRERELEASE \"%s\"", field_string(product, "version_prerelease"))
		builder_line(&builder, "/* complete product version string */")
		builder_format_line(&builder, "#define ENTASIS_VERSION_STRING \"%s\"", field_string(product, "version_string"))
		builder_line(&builder, "/* stable C ABI generation */")
		builder_format_line(&builder, "#define ENTASIS_ABI_VERSION UINT32_C(%d)", field_integer(product, "abi_version"))
		builder_line(&builder, "/* maximum worker count accepted by the runtime */")
		builder_format_line(&builder, "#define ENTASIS_MAXIMUM_WORKER_COUNT UINT32_C(%d)", field_integer(product, "maximum_worker_count"))
		builder_line(&builder)
		for constant in field_items(manifest.root, "macro_constants")
		{
			append_doc_comment(&builder, field_string(constant, "doc"), "")
			builder_format_line(&builder, "#define %s %s", field_string(constant, "name"), field_string(constant, "c_value"))
		}
		if len(field_items(manifest.root, "macro_constants")) > 0
		{
			builder_line(&builder)
		}
		for alias in field_items(manifest.root, "scalar_aliases")
		{
			append_doc_comment(&builder, field_string(alias, "doc"), "")
			builder_format_line(&builder, "typedef %s %s;", field_string(alias, "c_type"), field_string(alias, "name"))
		}
		builder_line(&builder)
		for enum_group in field_items(manifest.root, "enum_constants")
		{
			append_doc_comment(&builder, field_string(enum_group, "doc"), "")
			builder_line(&builder, "enum {")
			values := field_items(enum_group, "values")
			for value, index in values
			{
				pair := node_items(value)
				name := node_string(pair[0])
				doc := node_string(node_field(node_field(enum_group, "value_docs"), name))
				if doc != ""
				{
					builder_format_line(&builder, "    /* %s */", doc)
				}
				comma := ""
				if index + 1 < len(values)
				{
					comma = ","
				}
				builder_format_line(&builder, "    %s = %d%s", name, node_integer(pair[1]), comma)
			}
			builder_line(&builder, "};")
			builder_line(&builder)
		}
		for item in ordered
		{
			builder_format_line(&builder, "typedef struct %s %s;", field_string(item, "name"), field_string(item, "name"))
		}
		builder_line(&builder)
	}
	else if header == "cooking"
	{
		builder_format_line(&builder, "#define ENTASIS_COOKING_ABI_VERSION UINT32_C(%d)", field_integer(root_field(manifest, "product"), "abi_version"))
		builder_line(&builder)
	}
	header_structs: [dynamic]^Node
	for item in ordered
	{
		if field_string(item, "header") == header
		{
			append(&header_structs, item)
		}
	}
	pre_callback_names := pre_callback_struct_names(manifest, ordered[:], header)
	for item in header_structs
	{
		if contains_string(pre_callback_names[:], field_string(item, "name")) == .Enabled
		{
			append_struct_definition(&builder, item)
		}
	}
	callback_count := 0
	for callback in field_items(manifest.root, "callback_types")
	{
		if field_string(callback, "header") != header
		{
			continue
		}
		callback_count += 1
		append_doc_comment(
			&builder,
			field_string(callback, "doc"),
			field_string(callback, "details"),
			field_items(callback, "params"),
			field_string(callback, "return_doc"),
		)
		params: [dynamic]string
		for parameter in field_items(callback, "params")
		{
			append(&params, c_decl(parameter))
		}
		parameter_text := "void"
		if len(params) > 0
		{
			parameter_text = strings.join(params[:], ", ")
		}
		builder_format_line(&builder, "typedef %s (ENTASIS_CALL *%s)(%s);", field_string(callback, "return_c"), field_string(callback, "name"), parameter_text)
	}
	if callback_count > 0
	{
		builder_line(&builder)
	}
	for item in header_structs
	{
		if contains_string(pre_callback_names[:], field_string(item, "name")) == .Disabled
		{
			append_struct_definition(&builder, item)
		}
	}
	alias_count := 0
	for alias in field_items(manifest.root, "struct_aliases")
	{
		if field_string(alias, "header") == header
		{
			alias_count += 1
			append_doc_comment(&builder, field_string(alias, "doc"), field_string(alias, "details"))
			builder_format_line(&builder, "typedef %s %s;", field_string(alias, "target"), field_string(alias, "name"))
		}
	}
	if alias_count > 0
	{
		builder_line(&builder)
	}
	if header == "base"
	{
		builder_line(&builder, "#ifdef __cplusplus")
		builder_line(&builder, "#  define ENTASIS_STRING_VIEW_LITERAL(value) entasis_string_view_t{(value), (uint64_t)(sizeof(value) - 1u)}")
		builder_line(&builder, "#  define ENTASIS_CURRENT_VERSION entasis_version_t{ENTASIS_VERSION_MAJOR, ENTASIS_VERSION_MINOR, ENTASIS_VERSION_PATCH, UINT16_C(0), ENTASIS_STRING_VIEW_LITERAL(ENTASIS_VERSION_PRERELEASE)}")
		builder_line(&builder, "#else")
		builder_line(&builder, "#  define ENTASIS_STRING_VIEW_LITERAL(value) ((entasis_string_view_t){(value), (uint64_t)(sizeof(value) - 1u)})")
		builder_line(&builder, "#  define ENTASIS_CURRENT_VERSION ((entasis_version_t){ENTASIS_VERSION_MAJOR, ENTASIS_VERSION_MINOR, ENTASIS_VERSION_PATCH, UINT16_C(0), ENTASIS_STRING_VIEW_LITERAL(ENTASIS_VERSION_PRERELEASE)})")
		builder_line(&builder, "#endif")
		builder_line(&builder)
	}
	api_prefix := "ENTASIS"
	if header == "cooking"
	{
		api_prefix = "ENTASIS_COOKING"
	}
	for function in field_items(manifest.root, "functions")
	{
		if field_string(function, "header") != header
		{
			continue
		}
		append_doc_comment(
			&builder,
			field_string(function, "doc"),
			field_string(function, "details"),
			field_items(function, "params"),
			field_string(function, "return_doc"),
		)
		params: [dynamic]string
		for parameter in field_items(function, "params")
		{
			append(&params, c_decl(parameter))
		}
		parameter_text := "void"
		if len(params) > 0
		{
			parameter_text = strings.join(params[:], ", ")
		}
		builder_format_line(&builder, "%s_API %s %s_CALL %s(%s);", api_prefix, field_string(function, "return_c"), api_prefix, field_string(function, "name"), parameter_text)
		builder_line(&builder)
	}
	builder_line(&builder, "#ifdef __cplusplus")
	builder_line(&builder, "} /* extern \"C\" */")
	builder_line(&builder, "#endif")
	builder_line(&builder)
	builder_format_line(&builder, "#endif /* %s */", guard)
	builder_line(&builder)
	return builder_result(&builder), .Enabled, ""
}

render_umbrella_header :: proc(manifest: ^Manifest, header: string) -> string
{
	builder := strings.builder_make_len_cap(0, 2048)
	spec := header_spec(manifest, header)
	guard := field_string(spec, "guard")
	builder_format_line(&builder, "// %s", BANNER_OWNER)
	builder_format_line(&builder, "#ifndef %s", guard)
	builder_format_line(&builder, "#define %s", guard)
	builder_line(&builder)
	for dependency in field_items(spec, "includes")
	{
		builder_format_line(&builder, "#include <%s>", header_include_path(manifest, node_string(dependency)))
	}
	builder_line(&builder)
	builder_format_line(&builder, "#endif /* %s */", guard)
	builder_line(&builder)
	return builder_result(&builder)
}

render_compatibility_header :: proc(guard, target: string) -> string
{
	builder := strings.builder_make_len_cap(0, 512)
	builder_format_line(&builder, "// %s", BANNER_OWNER)
	builder_format_line(&builder, "#ifndef %s", guard)
	builder_format_line(&builder, "#define %s", guard)
	builder_line(&builder)
	builder_format_line(&builder, "#include <%s>", target)
	builder_line(&builder)
	builder_format_line(&builder, "#endif /* %s */", guard)
	builder_line(&builder)
	return builder_result(&builder)
}

library_symbols :: proc(manifest: ^Manifest, library: string) -> [dynamic]string
{
	result: [dynamic]string
	for function in field_items(manifest.root, "functions")
	{
		if field_string(function, "library") == library
		{
			append(&result, field_string(function, "name"))
		}
	}
	sort_strings(result[:])
	return result
}

render_version_script :: proc(manifest: ^Manifest, library: string) -> string
{
	builder := strings.builder_make_len_cap(0, 16384)
	builder_format_line(&builder, "# %s", BANNER_OWNER)
	builder_format_line(&builder, "%s {{", field_string(library_spec(manifest, library), "version_node"))
	builder_line(&builder, "  global:")
	for symbol in library_symbols(manifest, library)
	{
		builder_format_line(&builder, "    %s;", symbol)
	}
	builder_line(&builder, "  local:")
	builder_line(&builder, "    *;")
	builder_line(&builder, "};")
	builder_line(&builder)
	return builder_result(&builder)
}

render_def :: proc(manifest: ^Manifest, library: string) -> string
{
	builder := strings.builder_make_len_cap(0, 16384)
	builder_format_line(&builder, "; %s", BANNER_OWNER)
	builder_format_line(&builder, "LIBRARY %s", field_string(library_spec(manifest, library), "def_library"))
	builder_line(&builder, "EXPORTS")
	for symbol in library_symbols(manifest, library)
	{
		builder_format_line(&builder, "    %s", symbol)
	}
	builder_line(&builder)
	return builder_result(&builder)
}

render_layout_header :: proc(manifest: ^Manifest) -> string
{
	builder := strings.builder_make_len_cap(0, 32768)
	builder_format_line(&builder, "// %s", BANNER_OWNER)
	builder_line(&builder, "#ifndef ENTASIS_GENERATED_LAYOUT_ASSERTS_H")
	builder_line(&builder, "#define ENTASIS_GENERATED_LAYOUT_ASSERTS_H")
	builder_line(&builder)
	builder_line(&builder, "#include <entasis/entasis.h>")
	builder_line(&builder, "#include <entasis/cooking.h>")
	builder_line(&builder)
	builder_line(&builder, "#ifdef __cplusplus")
	builder_line(&builder, "#  define ENTASIS_LAYOUT_ASSERT(condition, message) static_assert((condition), message)")
	builder_line(&builder, "#  define ENTASIS_LAYOUT_ALIGNOF(type) alignof(type)")
	builder_line(&builder, "#else")
	builder_line(&builder, "#  define ENTASIS_LAYOUT_ASSERT(condition, message) _Static_assert((condition), message)")
	builder_line(&builder, "#  define ENTASIS_LAYOUT_ALIGNOF(type) _Alignof(type)")
	builder_line(&builder, "#endif")
	builder_line(&builder)
	for item in field_items(manifest.root, "structs")
	{
		name := field_string(item, "name")
		builder_format_line(&builder, "ENTASIS_LAYOUT_ASSERT(sizeof(%s) == %du, \"%s size\");", name, field_integer(item, "size"), name)
		builder_format_line(&builder, "ENTASIS_LAYOUT_ASSERT(ENTASIS_LAYOUT_ALIGNOF(%s) == %du, \"%s alignment\");", name, field_integer(item, "align"), name)
		for offset in field_entries(item, "offsets")
		{
			builder_format_line(&builder, "ENTASIS_LAYOUT_ASSERT(offsetof(%s, %s) == %du, \"%s.%s offset\");", name, offset.key, node_integer(offset.value), name, offset.key)
		}
	}
	builder_line(&builder)
	builder_line(&builder, "ENTASIS_LAYOUT_ASSERT(ENTASIS_STATUS_OK == 0, \"status value\");")
	builder_line(&builder, "ENTASIS_LAYOUT_ASSERT(ENTASIS_STATUS_DISPOSED == 6, \"status value\");")
	builder_line(&builder, "ENTASIS_LAYOUT_ASSERT(ENTASIS_BODY_MOBILITY_STATIC == 2, \"mobility value\");")
	builder_line(&builder, "ENTASIS_LAYOUT_ASSERT(ENTASIS_CONTINUOUS_DETECTION_CONTINUOUS == 2, \"continuity value\");")
	builder_format_line(&builder, "ENTASIS_LAYOUT_ASSERT(ENTASIS_ABI_VERSION == %du, \"ABI version\");", field_integer(root_field(manifest, "product"), "abi_version"))
	builder_line(&builder, "ENTASIS_LAYOUT_ASSERT(ENTASIS_MAXIMUM_WORKER_COUNT == 64u, \"worker limit\");")
	builder_line(&builder)
	builder_line(&builder, "#undef ENTASIS_LAYOUT_ALIGNOF")
	builder_line(&builder, "#undef ENTASIS_LAYOUT_ASSERT")
	builder_line(&builder)
	builder_line(&builder, "#endif /* ENTASIS_GENERATED_LAYOUT_ASSERTS_H */")
	builder_line(&builder)
	return builder_result(&builder)
}
