// generated by tools/abi/generate_abi. do not edit
package entasis_cooking_c

@(export, link_name="entasis_cooking_abi_version")
export_entasis_cooking_abi_version :: proc "c" () -> u32
{
	return abi_cooking_version();
}

@(export, link_name="entasis_cook_big_compound")
export_entasis_cook_big_compound :: proc "c" (
	context_: ^Entasis_Cooking_Context,
	children: [^]Entasis_Cooked_Big_Compound_Child,
	count: u64,
	out_cooked: ^Entasis_Cooked_Big_Compound,
	diagnostic: ^Entasis_Diagnostic,
) -> Entasis_Status
{
	return abi_cook_big_compound(context_, children, count, out_cooked, diagnostic);
}

@(export, link_name="entasis_cook_compound")
export_entasis_cook_compound :: proc "c" (
	context_: ^Entasis_Cooking_Context,
	children: [^]Entasis_Cooked_Compound_Child,
	count: u64,
	out_cooked: ^Entasis_Cooked_Compound,
	diagnostic: ^Entasis_Diagnostic,
) -> Entasis_Status
{
	return abi_cook_compound(context_, children, count, out_cooked, diagnostic);
}

@(export, link_name="entasis_cook_hull")
export_entasis_cook_hull :: proc "c" (
	context_: ^Entasis_Cooking_Context,
	points: [^]Entasis_Vector3,
	count: u64,
	out_cooked: ^Entasis_Cooked_Hull,
	out_center: ^Entasis_Vector3,
	diagnostic: ^Entasis_Diagnostic,
) -> Entasis_Status
{
	return abi_cook_hull(context_, points, count, out_cooked, out_center, diagnostic);
}

@(export, link_name="entasis_cook_mesh")
export_entasis_cook_mesh :: proc "c" (
	context_: ^Entasis_Cooking_Context,
	triangles: [^]Entasis_Triangle,
	count: u64,
	scale: Entasis_Vector3,
	out_cooked: ^Entasis_Cooked_Mesh,
	diagnostic: ^Entasis_Diagnostic,
) -> Entasis_Status
{
	return abi_cook_mesh(context_, triangles, count, scale, out_cooked, diagnostic);
}

@(export, link_name="entasis_cooked_big_compound_destroy")
export_entasis_cooked_big_compound_destroy :: proc "c" (
	cooked: ^Entasis_Cooked_Big_Compound,
	diagnostic: ^Entasis_Diagnostic,
) -> Entasis_Status
{
	return abi_cooked_big_compound_destroy(cooked, diagnostic);
}

@(export, link_name="entasis_cooked_big_compound_import")
export_entasis_cooked_big_compound_import :: proc "c" (
	world: ^Entasis_World,
	cooked: ^Entasis_Cooked_Big_Compound,
	shape_slots: [^]Entasis_Shape_Handle,
	shape_slot_count: u64,
	out_handle: ^Entasis_Shape_Handle,
	diagnostic: ^Entasis_Diagnostic,
) -> Entasis_Status
{
	return abi_cooked_big_compound_import(world, cooked, shape_slots, shape_slot_count, out_handle, diagnostic);
}

@(export, link_name="entasis_cooked_compound_destroy")
export_entasis_cooked_compound_destroy :: proc "c" (
	cooked: ^Entasis_Cooked_Compound,
	diagnostic: ^Entasis_Diagnostic,
) -> Entasis_Status
{
	return abi_cooked_compound_destroy(cooked, diagnostic);
}

@(export, link_name="entasis_cooked_compound_import")
export_entasis_cooked_compound_import :: proc "c" (
	world: ^Entasis_World,
	cooked: ^Entasis_Cooked_Compound,
	shape_slots: [^]Entasis_Shape_Handle,
	shape_slot_count: u64,
	out_handle: ^Entasis_Shape_Handle,
	diagnostic: ^Entasis_Diagnostic,
) -> Entasis_Status
{
	return abi_cooked_compound_import(world, cooked, shape_slots, shape_slot_count, out_handle, diagnostic);
}

@(export, link_name="entasis_cooked_hull_destroy")
export_entasis_cooked_hull_destroy :: proc "c" (
	cooked: ^Entasis_Cooked_Hull,
	diagnostic: ^Entasis_Diagnostic,
) -> Entasis_Status
{
	return abi_cooked_hull_destroy(cooked, diagnostic);
}

@(export, link_name="entasis_cooked_hull_import")
export_entasis_cooked_hull_import :: proc "c" (
	world: ^Entasis_World,
	cooked: ^Entasis_Cooked_Hull,
	out_handle: ^Entasis_Shape_Handle,
	diagnostic: ^Entasis_Diagnostic,
) -> Entasis_Status
{
	return abi_cooked_hull_import(world, cooked, out_handle, diagnostic);
}

@(export, link_name="entasis_cooked_hull_validate")
export_entasis_cooked_hull_validate :: proc "c" (cooked: ^Entasis_Cooked_Hull) -> Entasis_Status
{
	return abi_cooked_hull_validate(cooked);
}

@(export, link_name="entasis_cooked_mesh_closed_mass_properties")
export_entasis_cooked_mesh_closed_mass_properties :: proc "c" (
	cooked: ^Entasis_Cooked_Mesh,
	mass: f32,
	recenter: Entasis_Bool,
	out_properties: ^Entasis_Mesh_Mass_Properties,
	diagnostic: ^Entasis_Diagnostic,
) -> Entasis_Status
{
	return abi_cooked_mesh_closed_mass_properties(cooked, mass, recenter, out_properties, diagnostic);
}

@(export, link_name="entasis_cooked_mesh_destroy")
export_entasis_cooked_mesh_destroy :: proc "c" (
	cooked: ^Entasis_Cooked_Mesh,
	diagnostic: ^Entasis_Diagnostic,
) -> Entasis_Status
{
	return abi_cooked_mesh_destroy(cooked, diagnostic);
}

@(export, link_name="entasis_cooked_mesh_import")
export_entasis_cooked_mesh_import :: proc "c" (
	world: ^Entasis_World,
	cooked: ^Entasis_Cooked_Mesh,
	out_handle: ^Entasis_Shape_Handle,
	diagnostic: ^Entasis_Diagnostic,
) -> Entasis_Status
{
	return abi_cooked_mesh_import(world, cooked, out_handle, diagnostic);
}

@(export, link_name="entasis_cooked_mesh_open_mass_properties")
export_entasis_cooked_mesh_open_mass_properties :: proc "c" (
	cooked: ^Entasis_Cooked_Mesh,
	mass: f32,
	recenter: Entasis_Bool,
	out_properties: ^Entasis_Mesh_Mass_Properties,
	diagnostic: ^Entasis_Diagnostic,
) -> Entasis_Status
{
	return abi_cooked_mesh_open_mass_properties(cooked, mass, recenter, out_properties, diagnostic);
}

@(export, link_name="entasis_cooking_context_clear")
export_entasis_cooking_context_clear :: proc "c" (
	context_: ^Entasis_Cooking_Context,
	diagnostic: ^Entasis_Diagnostic,
) -> Entasis_Status
{
	return abi_cooking_context_clear(context_, diagnostic);
}

@(export, link_name="entasis_cooking_context_destroy")
export_entasis_cooking_context_destroy :: proc "c" (
	context_: ^Entasis_Cooking_Context,
	diagnostic: ^Entasis_Diagnostic,
) -> Entasis_Status
{
	return abi_cooking_context_destroy(context_, diagnostic);
}

@(export, link_name="entasis_cooking_context_init")
export_entasis_cooking_context_init :: proc "c" (
	context_: ^Entasis_Cooking_Context,
	minimum_block_size: i32,
	expected_resource_count: i32,
	allocator: ^Entasis_Allocator,
	diagnostic: ^Entasis_Diagnostic,
) -> Entasis_Status
{
	return abi_cooking_context_init(context_, minimum_block_size, expected_resource_count, allocator, diagnostic);
}

@(export, link_name="entasis_cooking_context_init_extended")
export_entasis_cooking_context_init_extended :: proc "c" (
	context_: ^Entasis_Cooking_Context,
	minimum_block_size: i32,
	expected_resource_count: i32,
	allocator: ^Entasis_Allocator,
	allocation_scope: Entasis_Allocation_Scope,
	diagnostic: ^Entasis_Diagnostic,
) -> Entasis_Status
{
	return abi_cooking_context_init_extended(
		context_,
		minimum_block_size,
		expected_resource_count,
		allocator,
		allocation_scope,
		diagnostic,
	);
}
