// generated by tools/abi/generate_abi. do not edit
package entasis

// Version is the compile-time Entasis product version
Version :: struct
{
	major:      u16,
	minor:      u16,
	patch:      u16,
	prerelease: string,
}

// VERSION_MAJOR is the product major version
VERSION_MAJOR :: u16(1);
// VERSION_MINOR is the product minor version
VERSION_MINOR :: u16(0);
// VERSION_PATCH is the product patch version
VERSION_PATCH :: u16(0);
// VERSION_PRERELEASE is empty for a stable release or contains the prerelease identifier
VERSION_PRERELEASE :: "";
// VERSION_STRING is the complete compile-time product version
VERSION_STRING :: "1.0.0";

// ABI_VERSION identifies the public C ABI generation
ABI_VERSION :: u32(1);

// CURRENT_VERSION contains the compile-time product version fields
CURRENT_VERSION :: Version{
	major=VERSION_MAJOR,
	minor=VERSION_MINOR,
	patch=VERSION_PATCH,
	prerelease=VERSION_PRERELEASE,
};

// version_current returns CURRENT_VERSION
version_current :: proc "contextless" () -> Version
{
	return CURRENT_VERSION;
}
