// generated by tools/abi/generate_abi. do not edit
#ifndef ENTASIS_BASE_H
#define ENTASIS_BASE_H

#include <stddef.h>
#include <stdint.h>

#if UINTPTR_MAX != UINT64_MAX
#  error "Entasis ABI v1 requires a 64-bit target."
#endif

#if defined(_WIN32)
#  define ENTASIS_CALL __cdecl
#  if defined(ENTASIS_BUILD_SHARED)
#    define ENTASIS_API __declspec(dllexport)
#  elif defined(ENTASIS_USE_SHARED)
#    define ENTASIS_API __declspec(dllimport)
#  else
#    define ENTASIS_API
#  endif
#elif defined(__GNUC__) || defined(__clang__)
#  define ENTASIS_CALL
#  define ENTASIS_API __attribute__((visibility("default")))
#else
#  define ENTASIS_CALL
#  define ENTASIS_API
#endif
#if defined(__cplusplus)
#  define ENTASIS_ALIGNAS(bytes) alignas(bytes)
#elif defined(_MSC_VER)
#  define ENTASIS_ALIGNAS(bytes) __declspec(align(bytes))
#else
#  define ENTASIS_ALIGNAS(bytes) _Alignas(bytes)
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* product major version */
#define ENTASIS_VERSION_MAJOR UINT16_C(1)
/* product minor version */
#define ENTASIS_VERSION_MINOR UINT16_C(0)
/* product patch version */
#define ENTASIS_VERSION_PATCH UINT16_C(0)
/* product prerelease identifier, empty for a stable release */
#define ENTASIS_VERSION_PRERELEASE ""
/* complete product version string */
#define ENTASIS_VERSION_STRING "1.0.0"
/* stable C ABI generation */
#define ENTASIS_ABI_VERSION UINT32_C(1)
/* maximum worker count accepted by the runtime */
#define ENTASIS_MAXIMUM_WORKER_COUNT UINT32_C(64)

/**
 * maximum number of collision layers addressable by a layer mask
 */
#define ENTASIS_MAX_COLLISION_LAYER_COUNT UINT32_C(64)
/**
 * layer mask that contains no collision layers
 */
#define ENTASIS_LAYER_MASK_NONE UINT64_C(0)
/**
 * layer mask that contains every collision layer
 */
#define ENTASIS_LAYER_MASK_ALL UINT64_MAX
/**
 * invalid material ID sentinel
 */
#define ENTASIS_MATERIAL_ID_INVALID UINT16_MAX
/**
 * invalid constraint type ID sentinel
 */
#define ENTASIS_CONSTRAINT_TYPE_INVALID INT32_C(-1)
/**
 * maximum contacts stored by one solver contact record
 */
#define ENTASIS_MAXIMUM_SOLVER_CONTACT_COUNT UINT32_C(4)
/**
 * maximum accumulated impulse scalars exposed by solver inspection
 */
#define ENTASIS_MAXIMUM_SOLVER_IMPULSE_COUNT UINT32_C(32)
/**
 * query mask bit for dynamic bodies
 */
#define ENTASIS_COLLIDABLE_DYNAMIC UINT8_C(1)
/**
 * query mask bit for kinematic bodies
 */
#define ENTASIS_COLLIDABLE_KINEMATIC UINT8_C(2)
/**
 * query mask bit for statics
 */
#define ENTASIS_COLLIDABLE_STATIC UINT8_C(4)
/**
 * query mask containing dynamic and kinematic bodies
 */
#define ENTASIS_COLLIDABLE_BODIES UINT8_C(3)
/**
 * query mask containing every public collidable class
 */
#define ENTASIS_COLLIDABLE_ALL UINT8_C(7)
/**
 * number of entries in one profile snapshot
 */
#define ENTASIS_PROFILE_STAGE_COUNT UINT32_C(12)
/**
 * fixed byte capacity of one heterogeneous query payload
 */
#define ENTASIS_QUERY_PAYLOAD_SIZE UINT32_C(120)
/**
 * fixed byte capacity of one heterogeneous query result payload
 */
#define ENTASIS_QUERY_RESULT_PAYLOAD_SIZE UINT32_C(52)
/**
 * fixed total registry capacity including built-in types
 */
#define ENTASIS_MAXIMUM_SHAPE_TYPE_COUNT UINT32_C(128)
/**
 * number of reserved built-in shape type IDs
 */
#define ENTASIS_BUILT_IN_SHAPE_TYPE_COUNT UINT32_C(9)
/**
 * largest supported custom payload alignment in bytes
 */
#define ENTASIS_MAXIMUM_CUSTOM_SHAPE_ALIGNMENT UINT32_C(128)
/**
 * first caller-defined constraint type ID
 */
#define ENTASIS_FIRST_CUSTOM_CONSTRAINT_TYPE_ID UINT32_C(56)
/**
 * exclusive upper bound on registered constraint IDs
 */
#define ENTASIS_MAXIMUM_CONSTRAINT_TYPE_COUNT UINT32_C(64)
/**
 * maximum tightly packed scalar description size
 */
#define ENTASIS_MAXIMUM_CUSTOM_DESCRIPTION_BYTES UINT32_C(256)
/**
 * maximum impulse fields retained while sleeping
 */
#define ENTASIS_MAXIMUM_INACTIVE_IMPULSE_SCALARS UINT32_C(32)
/**
 * collidable A was a trigger at the sampled step
 */
#define ENTASIS_TRIGGER_PAIR_A UINT32_C(1)
/**
 * collidable B was a trigger at the sampled step
 */
#define ENTASIS_TRIGGER_PAIR_B UINT32_C(2)
/**
 * at least one endpoint requested Stay events
 */
#define ENTASIS_TRIGGER_PAIR_STAY_REQUESTED UINT32_C(4)

/**
 * C ABI boolean stored as an unsigned byte
 */
typedef uint8_t entasis_bool_t;
/**
 * result status returned by fallible Entasis operations
 */
typedef uint8_t entasis_status_t;
/**
 * operation category recorded in an optional diagnostic
 */
typedef uint8_t entasis_diagnostic_operation_t;
/**
 * dynamic, kinematic, or static collidable classification
 */
typedef uint8_t entasis_body_mobility_t;
/**
 * continuous collision detection mode
 */
typedef uint8_t entasis_continuous_detection_mode_t;
/**
 * result returned by an external dispatcher callback
 */
typedef uint8_t entasis_dispatcher_status_t;
/**
 * angular velocity integration model
 */
typedef uint8_t entasis_angular_integration_mode_t;
/**
 * enabled or disabled pose integration option
 */
typedef uint8_t entasis_pose_integration_state_t;
/**
 * built-in pose integration policy kind
 */
typedef uint8_t entasis_pose_policy_kind_t;
/**
 * stable numeric shape type ID
 */
typedef int32_t entasis_shape_type_id_t;
/**
 * collision layer index in the inclusive range 0 to 63
 */
typedef uint8_t entasis_collision_layer_t;
/**
 * index into a caller-owned material table
 */
typedef uint16_t entasis_material_id_t;
/**
 * bit mask containing one bit per collision layer
 */
typedef uint64_t entasis_layer_mask_t;
/**
 * policy controlling wake-up after a static mutation
 */
typedef uint8_t entasis_awakening_policy_t;
/**
 * allow or reject result returned by a filter callback
 */
typedef uint8_t entasis_filter_decision_t;
/**
 * built-in narrow-phase policy kind
 */
typedef uint8_t entasis_narrow_policy_kind_t;
/**
 * stable numeric built-in constraint type ID
 */
typedef int32_t entasis_constraint_type_id_t;
/**
 * active, inactive, or missing constraint state
 */
typedef uint8_t entasis_constraint_state_t;
/**
 * active, sleeping, or missing body state
 */
typedef uint8_t entasis_body_activation_state_t;
/**
 * convex or nonconvex solver contact layout
 */
typedef uint8_t entasis_contact_constraint_kind_t;
/**
 * deferred structural command kind
 */
typedef uint8_t entasis_command_kind_t;
/**
 * bit mask selecting dynamic, kinematic, and static query targets
 */
typedef uint8_t entasis_collidable_mask_t;
/**
 * single optional contact event data flag
 */
typedef uint8_t entasis_contact_event_flag_t;
/**
 * bit set describing optional data available in a contact event
 */
typedef uint8_t entasis_contact_event_flags_t;
/**
 * contact pair transition after a completed world step
 */
typedef uint8_t entasis_contact_event_kind_t;
/**
 * active contact manifold representation
 */
typedef uint8_t entasis_manifold_kind_t;
/**
 * profiled world-step stage
 */
typedef uint8_t entasis_profile_stage_t;
/**
 * tagged batch query kind
 */
typedef uint8_t entasis_query_kind_t;
/**
 * miss or impact state returned by a sweep
 */
typedef uint8_t entasis_sweep_hit_state_t;
/**
 * a completion point reported by the default or selected custom timestepper
 */
typedef uint8_t entasis_timestep_completion_stage_t;
/**
 * reach of the existing allocator: Legacy or complete Entasis-owned allocation (All_Owned)
 */
typedef uint32_t entasis_allocation_scope_t;
/**
 * classification of registered custom shape storage and traversal
 */
typedef uint32_t entasis_shape_batch_type_t;
/**
 * existing collision task pair-storage classification
 */
typedef uint32_t entasis_collision_pair_type_t;
/**
 * native collision task result and traversal classification
 */
typedef uint32_t entasis_collision_task_kind_t;
/**
 * bit mask describing native collision task result and traversal capabilities
 */
typedef uint32_t entasis_collision_task_capabilities_t;
/**
 * fields a custom constraint kernel may read or update
 */
typedef uint32_t entasis_body_access_mask_t;
/**
 * phase of one registered constraint kernel invocation
 */
typedef uint32_t entasis_constraint_kernel_phase_t;
/**
 * unsigned discriminator describing a buffered sensor transition
 */
typedef uint32_t entasis_trigger_event_kind_t;
/**
 * unsigned discriminator describing a buffered sensor transition
 */
typedef uint32_t entasis_trigger_exit_reason_t;
/**
 * tolerance-bounded geometry state
 */
typedef uint8_t entasis_distance_query_state_t;
/**
 * operation in the dedicated distance batch, independent of the older query union
 */
typedef uint8_t entasis_distance_query_kind_t;
/**
 * geometric overlap presence, valid only on an OK status
 */
typedef uint8_t entasis_overlap_state_t;
/**
 * awakening policy for queued body controls
 */
typedef uint32_t entasis_body_control_wake_t;
/**
 * continuous input units
 */
typedef uint32_t entasis_body_input_mode_t;
/**
 * composition of per-body exponential damping
 */
typedef uint32_t entasis_body_damping_mode_t;
/**
 * bit mask selecting X, Y and Z physical lock rows
 */
typedef uint32_t entasis_body_lock_axes_t;
/**
 * physical role of one instance part
 */
typedef uint8_t entasis_collider_part_role_t;
/**
 * opt-in part trigger options
 */
typedef uint8_t entasis_collider_part_options_t;
/**
 * part event subscription selected at initialization
 */
typedef uint8_t entasis_collider_part_subscription_t;
/**
 * pending notification stream bits
 */
typedef uint8_t entasis_collider_part_pending_t;
/**
 * independent force and torque selection flags
 */
typedef uint32_t entasis_joint_break_metrics_t;
/**
 * committed watched-reaction validity
 */
typedef uint32_t entasis_joint_reaction_state_t;
/**
 * pending event-stream flags for the combined stepper
 */
typedef uint8_t entasis_joint_break_pending_t;

/**
 * boolean constants
 */
enum {
    /* boolean false */
    ENTASIS_FALSE = 0,
    /* boolean true */
    ENTASIS_TRUE = 1
};

/**
 * operation status values
 */
enum {
    /* operation completed successfully */
    ENTASIS_STATUS_OK = 0,
    /* a pointer, count, handle, range, or current state is invalid for the operation */
    ENTASIS_STATUS_INVALID_ARGUMENT = 1,
    /* a supplied description contains invalid or unsupported values */
    ENTASIS_STATUS_INVALID_DESCRIPTION = 2,
    /* the requested object or property is not present */
    ENTASIS_STATUS_NOT_FOUND = 3,
    /* required storage could not be reserved or supplied output capacity is too small */
    ENTASIS_STATUS_CAPACITY_MISSING = 4,
    /* the shape or cooking context still has live references */
    ENTASIS_STATUS_SHAPE_IN_USE = 5,
    /* the target object is uninitialized, already disposed, or no longer usable */
    ENTASIS_STATUS_DISPOSED = 6,
    /* a bounded geometry query did not establish its requested tolerance. no result is published */
    ENTASIS_STATUS_NO_CONVERGENCE = 7
};

/**
 * operations that can populate a diagnostic
 */
enum {
    /* no diagnostic operation */
    ENTASIS_DIAGNOSTIC_OPERATION_NONE = 0,
    /* world initialization */
    ENTASIS_DIAGNOSTIC_OPERATION_WORLD_INITIALIZE = 1,
    /* world capacity growth */
    ENTASIS_DIAGNOSTIC_OPERATION_WORLD_ENSURE_CAPACITY = 2,
    /* callback configuration */
    ENTASIS_DIAGNOSTIC_OPERATION_CALLBACK_CONFIGURE = 3,
    /* shape registration */
    ENTASIS_DIAGNOSTIC_OPERATION_SHAPE_REGISTER = 4,
    /* constraint registration */
    ENTASIS_DIAGNOSTIC_OPERATION_CONSTRAINT_REGISTER = 5,
    /* collision task registration */
    ENTASIS_DIAGNOSTIC_OPERATION_COLLISION_TASK_REGISTER = 6,
    /* sweep task registration */
    ENTASIS_DIAGNOSTIC_OPERATION_SWEEP_TASK_REGISTER = 7,
    /* dispatcher initialization */
    ENTASIS_DIAGNOSTIC_OPERATION_DISPATCHER_INITIALIZE = 8,
    /* cooked asset import */
    ENTASIS_DIAGNOSTIC_OPERATION_ASSET_IMPORT = 9
};

/**
 * body and collidable mobility classes
 */
enum {
    /* dynamic body */
    ENTASIS_BODY_MOBILITY_DYNAMIC = 0,
    /* kinematic body */
    ENTASIS_BODY_MOBILITY_KINEMATIC = 1,
    /* static collidable */
    ENTASIS_BODY_MOBILITY_STATIC = 2
};

/**
 * continuous collision detection modes
 */
enum {
    /* discrete collision detection with bounded speculative expansion */
    ENTASIS_CONTINUOUS_DETECTION_DISCRETE = 0,
    /* speculative expansion without running a sweep for this collidable */
    ENTASIS_CONTINUOUS_DETECTION_PASSIVE = 1,
    /* swept continuous collision detection */
    ENTASIS_CONTINUOUS_DETECTION_CONTINUOUS = 2
};

/**
 * external dispatcher callback results
 */
enum {
    /* dispatch completed successfully */
    ENTASIS_DISPATCHER_STATUS_OK = 0,
    /* dispatcher input is invalid */
    ENTASIS_DISPATCHER_STATUS_INVALID_ARGUMENT = 1,
    /* dispatcher storage could not satisfy the request */
    ENTASIS_DISPATCHER_STATUS_CAPACITY_MISSING = 2,
    /* dispatcher is already executing work */
    ENTASIS_DISPATCHER_STATUS_BUSY = 3,
    /* dispatcher is shutting down */
    ENTASIS_DISPATCHER_STATUS_SHUTTING_DOWN = 4,
    /* dispatcher is no longer usable */
    ENTASIS_DISPATCHER_STATUS_DISPOSED = 5
};

/**
 * angular velocity integration modes
 */
enum {
    /* standard nonconserving angular integration */
    ENTASIS_ANGULAR_INTEGRATION_NONCONSERVING = 0,
    /* conserves angular momentum */
    ENTASIS_ANGULAR_INTEGRATION_CONSERVE_MOMENTUM = 1,
    /* conserves angular momentum and applies gyroscopic torque */
    ENTASIS_ANGULAR_INTEGRATION_CONSERVE_MOMENTUM_WITH_GYROSCOPIC_TORQUE = 2
};

/**
 * pose integration option states
 */
enum {
    /* option disabled */
    ENTASIS_POSE_INTEGRATION_DISABLED = 0,
    /* option enabled */
    ENTASIS_POSE_INTEGRATION_ENABLED = 1
};

/**
 * built-in pose policy kinds
 */
enum {
    /* uses gravity and damping from the world description */
    ENTASIS_POSE_POLICY_DESCRIPTION_DEFAULT = 0,
    /* uniform gravity policy */
    ENTASIS_POSE_POLICY_UNIFORM_GRAVITY = 1,
    /* inverse-square planetary gravity policy */
    ENTASIS_POSE_POLICY_PLANETARY_GRAVITY = 2,
    /* dense handle-indexed per-body gravity policy */
    ENTASIS_POSE_POLICY_PER_BODY_GRAVITY = 3
};

/**
 * built-in shape type IDs and the invalid sentinel
 */
enum {
    /* invalid shape type ID */
    ENTASIS_SHAPE_TYPE_INVALID = -1,
    /* built-in sphere shape type ID */
    ENTASIS_SHAPE_TYPE_SPHERE = 0,
    /* built-in capsule shape type ID */
    ENTASIS_SHAPE_TYPE_CAPSULE = 1,
    /* built-in box shape type ID */
    ENTASIS_SHAPE_TYPE_BOX = 2,
    /* built-in triangle shape type ID */
    ENTASIS_SHAPE_TYPE_TRIANGLE = 3,
    /* built-in cylinder shape type ID */
    ENTASIS_SHAPE_TYPE_CYLINDER = 4,
    /* built-in convex hull shape type ID */
    ENTASIS_SHAPE_TYPE_CONVEX_HULL = 5,
    /* built-in compound shape type ID */
    ENTASIS_SHAPE_TYPE_COMPOUND = 6,
    /* built-in big compound shape type ID */
    ENTASIS_SHAPE_TYPE_BIG_COMPOUND = 7,
    /* built-in mesh shape type ID */
    ENTASIS_SHAPE_TYPE_MESH = 8
};

/**
 * static mutation awakening policies
 */
enum {
    /* awakens dynamic bodies overlapping the changed static bounds */
    ENTASIS_AWAKENING_OVERLAPS = 0,
    /* performs the static mutation without automatic awakening */
    ENTASIS_AWAKENING_NONE = 1
};

/**
 * filter callback decisions
 */
enum {
    /* rejects the candidate pair or child */
    ENTASIS_FILTER_REJECT = 0,
    /* allows the candidate pair or child */
    ENTASIS_FILTER_ALLOW = 1
};

/**
 * built-in narrow-phase policy kinds
 */
enum {
    /* constant default contact material policy */
    ENTASIS_NARROW_POLICY_DEFAULT = 0,
    /* layer, material, and optional callback policy */
    ENTASIS_NARROW_POLICY_LAYERS_MATERIALS = 1
};

/**
 * constraint storage states
 */
enum {
    /* constraint is missing or the handle is invalid */
    ENTASIS_CONSTRAINT_STATE_MISSING = 0,
    /* constraint is stored in the active solver */
    ENTASIS_CONSTRAINT_STATE_ACTIVE = 1,
    /* constraint is stored in a sleeping island */
    ENTASIS_CONSTRAINT_STATE_INACTIVE = 2
};

/**
 * body activation states
 */
enum {
    /* body is missing or the handle is invalid */
    ENTASIS_BODY_ACTIVATION_MISSING = 0,
    /* body is stored in the active set */
    ENTASIS_BODY_ACTIVATION_ACTIVE = 1,
    /* body is stored in a sleeping island */
    ENTASIS_BODY_ACTIVATION_SLEEPING = 2
};

/**
 * solver contact constraint forms
 */
enum {
    /* convex contact constraint */
    ENTASIS_CONTACT_CONSTRAINT_CONVEX = 0,
    /* nonconvex contact constraint */
    ENTASIS_CONTACT_CONSTRAINT_NONCONVEX = 1
};

/**
 * deferred structural command kinds
 */
enum {
    /* adds one body */
    ENTASIS_COMMAND_BODY_ADD = 0,
    /* replaces one body description */
    ENTASIS_COMMAND_BODY_APPLY = 1,
    /* removes one body */
    ENTASIS_COMMAND_BODY_REMOVE = 2,
    /* adds one static */
    ENTASIS_COMMAND_STATIC_ADD = 3,
    /* replaces one static description */
    ENTASIS_COMMAND_STATIC_APPLY = 4,
    /* removes one static */
    ENTASIS_COMMAND_STATIC_REMOVE = 5
};

/**
 * built-in constraint type IDs
 */
enum {
    /* built-in ball socket constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_BALL_SOCKET = 22,
    /* built-in angular hinge constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_ANGULAR_HINGE = 23,
    /* built-in angular swivel hinge constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_ANGULAR_SWIVEL_HINGE = 24,
    /* built-in swing limit constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_SWING_LIMIT = 25,
    /* built-in twist servo constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_TWIST_SERVO = 26,
    /* built-in twist limit constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_TWIST_LIMIT = 27,
    /* built-in twist motor constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_TWIST_MOTOR = 28,
    /* built-in angular servo constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_ANGULAR_SERVO = 29,
    /* built-in angular motor constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_ANGULAR_MOTOR = 30,
    /* built-in weld constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_WELD = 31,
    /* built-in volume constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_VOLUME_CONSTRAINT = 32,
    /* built-in distance servo constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_DISTANCE_SERVO = 33,
    /* built-in distance limit constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_DISTANCE_LIMIT = 34,
    /* built-in center distance constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_CENTER_DISTANCE_CONSTRAINT = 35,
    /* built-in area constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_AREA_CONSTRAINT = 36,
    /* built-in point on line servo constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_POINT_ON_LINE_SERVO = 37,
    /* built-in linear axis servo constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_LINEAR_AXIS_SERVO = 38,
    /* built-in linear axis motor constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_LINEAR_AXIS_MOTOR = 39,
    /* built-in linear axis limit constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_LINEAR_AXIS_LIMIT = 40,
    /* built-in angular axis motor constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_ANGULAR_AXIS_MOTOR = 41,
    /* built-in one body angular servo constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_ONE_BODY_ANGULAR_SERVO = 42,
    /* built-in one body angular motor constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_ONE_BODY_ANGULAR_MOTOR = 43,
    /* built-in one body linear servo constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_ONE_BODY_LINEAR_SERVO = 44,
    /* built-in one body linear motor constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_ONE_BODY_LINEAR_MOTOR = 45,
    /* built-in swivel hinge constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_SWIVEL_HINGE = 46,
    /* built-in hinge constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_HINGE = 47,
    /* built-in ball socket motor constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_BALL_SOCKET_MOTOR = 52,
    /* built-in ball socket servo constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_BALL_SOCKET_SERVO = 53,
    /* built-in angular axis gear motor constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_ANGULAR_AXIS_GEAR_MOTOR = 54,
    /* built-in center distance limit constraint type ID */
    ENTASIS_CONSTRAINT_TYPE_CENTER_DISTANCE_LIMIT = 55
};

/**
 * contact pair lifetime transitions
 */
enum {
    /* tracked pair started touching */
    ENTASIS_CONTACT_EVENT_BEGIN = 0,
    /* tracked pair remained touching */
    ENTASIS_CONTACT_EVENT_PERSIST = 1,
    /* tracked pair stopped touching */
    ENTASIS_CONTACT_EVENT_END = 2
};

/**
 * optional data available in a contact event
 */
enum {
    /* event contains a contact normal */
    ENTASIS_CONTACT_EVENT_NORMAL_AVAILABLE = 1,
    /* event contains the caller ID for collidable A */
    ENTASIS_CONTACT_EVENT_USER_A_AVAILABLE = 2,
    /* event contains the caller ID for collidable B */
    ENTASIS_CONTACT_EVENT_USER_B_AVAILABLE = 4,
    /* event contains solver contact data */
    ENTASIS_CONTACT_EVENT_SOLVER_DATA_AVAILABLE = 8
};

/**
 * contact manifold representations
 */
enum {
    /* convex contact manifold */
    ENTASIS_MANIFOLD_CONVEX = 0,
    /* nonconvex contact manifold */
    ENTASIS_MANIFOLD_NONCONVEX = 1
};

/**
 * profiled world-step stages
 */
enum {
    /* complete world step */
    ENTASIS_PROFILE_TIMESTEP = 0,
    /* sleep candidate processing */
    ENTASIS_PROFILE_SLEEP = 1,
    /* post-sleep callback stage */
    ENTASIS_PROFILE_SLEPT_CALLBACK = 2,
    /* pose prediction and bounds update */
    ENTASIS_PROFILE_PREDICT_BOUNDING_BOXES = 3,
    /* pre-collision callback stage */
    ENTASIS_PROFILE_BEFORE_COLLISION_CALLBACK = 4,
    /* broad-phase update and pair generation */
    ENTASIS_PROFILE_BROAD_PHASE = 5,
    /* narrow-phase collision detection */
    ENTASIS_PROFILE_COLLISION_DETECTION = 6,
    /* post-collision callback stage */
    ENTASIS_PROFILE_COLLISIONS_DETECTED_CALLBACK = 7,
    /* constraint solve */
    ENTASIS_PROFILE_SOLVE = 8,
    /* post-solve callback stage */
    ENTASIS_PROFILE_CONSTRAINTS_SOLVED_CALLBACK = 9,
    /* incremental broad-phase optimization */
    ENTASIS_PROFILE_INCREMENTALLY_OPTIMIZE = 10,
    /* end-of-step cleanup */
    ENTASIS_PROFILE_CLEANUP = 11
};

/**
 * batch query kinds
 */
enum {
    /* ray query that stops after the first accepted hit */
    ENTASIS_QUERY_RAY_ANY = 0,
    /* ray query that returns the closest accepted hit */
    ENTASIS_QUERY_RAY_CLOSEST = 1,
    /* ray query that writes all accepted hits */
    ENTASIS_QUERY_RAY_ALL = 2,
    /* shape sweep that returns the closest accepted hit */
    ENTASIS_QUERY_SWEEP_CLOSEST = 3,
    /* shape overlap query that writes all accepted hits */
    ENTASIS_QUERY_OVERLAP_ALL = 4,
    /* AABB query that writes all overlapping broad-phase entries */
    ENTASIS_QUERY_VOLUME_ALL = 5
};

/**
 * sweep result states
 */
enum {
    /* no impact found in the sweep interval */
    ENTASIS_SWEEP_MISS = 0,
    /* impact found in the sweep interval */
    ENTASIS_SWEEP_HIT = 1
};

/**
 * stable timestep completion identifiers
 */
enum {
    /* sleeping stage completed */
    ENTASIS_TIMESTEP_SLEPT = 0,
    /* predicted bounds are ready for collision detection */
    ENTASIS_TIMESTEP_BEFORE_COLLISION_DETECTION = 1,
    /* collision detection completed */
    ENTASIS_TIMESTEP_COLLISIONS_DETECTED = 2,
    /* constraint solving and integration completed */
    ENTASIS_TIMESTEP_CONSTRAINTS_SOLVED = 3
};

/**
 * implemented allocator reach modes
 */
enum {
    /* retains existing allocator reach and lazy pool metadata growth */
    ENTASIS_ALLOCATION_LEGACY = 0,
    /* routes resource metadata, native blocks and included worker/thread records through the selected allocator. valid buffer returns do not allocate */
    ENTASIS_ALLOCATION_ALL_OWNED = 1
};

/**
 * custom shape batch classifications
 */
enum {
    /* convex shape supporting local support mapping */
    ENTASIS_SHAPE_BATCH_CONVEX = 0,
    /* heterogeneous compound representation with caller-provided routes */
    ENTASIS_SHAPE_BATCH_COMPOUND = 1,
    /* homogeneous child representation with caller-provided routes */
    ENTASIS_SHAPE_BATCH_HOMOGENEOUS_COMPOUND = 2
};

/**
 * native pair-storage classifications
 */
enum {
    /* standard pair storage */
    ENTASIS_COLLISION_PAIR_STANDARD = 0,
    /* flipless pair storage */
    ENTASIS_COLLISION_PAIR_FLIPLESS = 1,
    /* sphere pair storage */
    ENTASIS_COLLISION_PAIR_SPHERE = 2,
    /* sphere including pair storage */
    ENTASIS_COLLISION_PAIR_SPHERE_INCLUDING = 3,
    /* bounds tested pair storage */
    ENTASIS_COLLISION_PAIR_BOUNDS_TESTED = 4
};

/**
 * native collision task kinds
 */
enum {
    /* convex callbacks. use entasis_collision_task_register */
    ENTASIS_COLLISION_TASK_CONVEX = 0,
    /* registered convex A against an engine-owned compound, big compound or mesh B */
    ENTASIS_COLLISION_TASK_CONVEX_COMPOUND = 1,
    /* engine-owned compound pair. built-in routes are already installed and cannot be replaced */
    ENTASIS_COLLISION_TASK_COMPOUND_PAIR = 2
};

/**
 * native collision task capability bits
 */
enum {
    /* convex callback result. not valid for compound registration */
    ENTASIS_COLLISION_TASK_CONVEX_RESULT = 1,
    /* SIMD callback result. not valid for compound registration */
    ENTASIS_COLLISION_TASK_WIDE_RESULT = 2,
    /* required compound child-task expansion */
    ENTASIS_COLLISION_TASK_SUBTASK_GENERATOR = 4,
    /* native child ordering metadata */
    ENTASIS_COLLISION_TASK_CHILD_ORDER = 8,
    /* native mesh reduction metadata. traversal/reduction still follows actual shape storage */
    ENTASIS_COLLISION_TASK_MESH_REDUCTION = 16
};

/**
 * custom constraint body field access
 */
enum {
    /* read position */
    ENTASIS_BODY_ACCESS_POSITION = 1,
    /* read orientation */
    ENTASIS_BODY_ACCESS_ORIENTATION = 2,
    /* read inverse mass */
    ENTASIS_BODY_ACCESS_MASS = 4,
    /* read inverse inertia */
    ENTASIS_BODY_ACCESS_INERTIA_TENSOR = 8,
    /* read and update linear velocity */
    ENTASIS_BODY_ACCESS_LINEAR_VELOCITY = 16,
    /* read and update angular velocity */
    ENTASIS_BODY_ACCESS_ANGULAR_VELOCITY = 32,
    /* all six body fields */
    ENTASIS_BODY_ACCESS_ALL = 63
};

/**
 * custom constraint kernel phases
 */
enum {
    /* prepares constraint data before warmstart */
    ENTASIS_CONSTRAINT_KERNEL_PRESTEP = 0,
    /* applies accumulated impulses */
    ENTASIS_CONSTRAINT_KERNEL_WARMSTART = 1,
    /* performs one velocity iteration */
    ENTASIS_CONSTRAINT_KERNEL_SOLVE = 2,
    /* updates between substeps after the first */
    ENTASIS_CONSTRAINT_KERNEL_INCREMENTAL_UPDATE = 3
};

/**
 * discriminators for retained sensor intersection transitions
 */
enum {
    /* indicates enter in the retained geometric transition stream */
    ENTASIS_TRIGGER_ENTER = 0,
    /* indicates stay in the retained geometric transition stream */
    ENTASIS_TRIGGER_STAY = 1,
    /* indicates exit in the retained geometric transition stream */
    ENTASIS_TRIGGER_EXIT = 2
};

/**
 * discriminators for retained sensor intersection transitions
 */
enum {
    /* indicates separation in the retained geometric transition stream */
    ENTASIS_TRIGGER_SEPARATION = 0,
    /* indicates removed in the retained geometric transition stream */
    ENTASIS_TRIGGER_REMOVED = 1,
    /* indicates disabled in the retained geometric transition stream */
    ENTASIS_TRIGGER_DISABLED = 2,
    /* indicates filter changed in the retained geometric transition stream */
    ENTASIS_TRIGGER_FILTER_CHANGED = 3
};

/**
 * tolerance-bounded geometry state
 */
enum {
    /* no valid geometric result. inspect the returned status */
    ENTASIS_DISTANCE_UNRESOLVED = 0,
    /* positive distance with closest witnesses */
    ENTASIS_DISTANCE_SEPARATED = 1,
    /* zero distance. distance alone does not determine a unique normal */
    ENTASIS_DISTANCE_INTERSECTING = 2,
    /* touching within the query tolerance. zero correction */
    ENTASIS_DISTANCE_TOUCHING = 3,
    /* positive convex separating depth or verified composite correction */
    ENTASIS_DISTANCE_PENETRATING = 4
};

/**
 * operation in the dedicated distance batch, independent of the older query union
 */
enum {
    /* use point and shape_b/pose_b */
    ENTASIS_DISTANCE_QUERY_CLOSEST_POINT = 0,
    /* closest witnesses between supported shapes */
    ENTASIS_DISTANCE_QUERY_DISTANCE = 1,
    /* fixed-orientation convex minimum separating translation */
    ENTASIS_DISTANCE_QUERY_PENETRATION = 2,
    /* verified convex-against-composite correction, not globally minimal */
    ENTASIS_DISTANCE_QUERY_DEPENETRATION = 3
};

/**
 * geometric overlap presence, valid only on an OK status
 */
enum {
    /* no accepted nonnegative-depth geometric contact */
    ENTASIS_OVERLAP_SEPARATED = 0,
    /* at least one accepted nonnegative-depth geometric contact */
    ENTASIS_OVERLAP_INTERSECTING = 1
};

/**
 * awakening policy for queued body controls
 */
enum {
    /* awaken and reset sleep activity before integration */
    ENTASIS_BODY_CONTROL_WAKE = 0,
    /* queue until the body next integrates. sleeping time contributes no input duration */
    ENTASIS_BODY_CONTROL_PRESERVE_SLEEP = 1
};

/**
 * continuous input units
 */
enum {
    /* force uses inverse mass. torque uses current world inverse inertia */
    ENTASIS_BODY_INPUT_FORCE = 0,
    /* mass-independent linear or angular acceleration */
    ENTASIS_BODY_INPUT_ACCELERATION = 1
};

/**
 * composition of per-body exponential damping
 */
enum {
    /* apply after the existing integration callback */
    ENTASIS_BODY_DAMPING_ADDITIONAL = 0,
    /* replace damping only in a recognized native gravity policy */
    ENTASIS_BODY_DAMPING_OVERRIDE = 1
};

/**
 * physical axis-lock row selection
 */
enum {
    /* no rows on this component */
    ENTASIS_BODY_LOCK_NONE = 0,
    /* X coordinate or reference-frame angular axis */
    ENTASIS_BODY_LOCK_X = 1,
    /* Y coordinate or reference-frame angular axis */
    ENTASIS_BODY_LOCK_Y = 2,
    /* Z coordinate or reference-frame angular axis */
    ENTASIS_BODY_LOCK_Z = 4,
    /* all three axes */
    ENTASIS_BODY_LOCK_ALL = 7
};

/**
 * part response role
 */
enum {
    /* part response role (solid) */
    ENTASIS_COLLIDER_PART_SOLID = 0,
    /* part response role (trigger) */
    ENTASIS_COLLIDER_PART_TRIGGER = 1
};

/**
 * part trigger option bit
 */
enum {
    /* part trigger option bit (stay) */
    ENTASIS_COLLIDER_PART_STAY = 1,
    /* include static/static overlaps for this trigger part */
    ENTASIS_COLLIDER_PART_STATIC_STATIC = 2
};

/**
 * part event subscription
 */
enum {
    /* part event subscription (disabled) */
    ENTASIS_COLLIDER_PART_EVENTS_DISABLED = 0,
    /* part event subscription (enabled) */
    ENTASIS_COLLIDER_PART_EVENTS_ENABLED = 1
};

/**
 * pending stream bit
 */
enum {
    /* parent trigger batch remains pending */
    ENTASIS_COLLIDER_PARENT_PENDING = 1,
    /* part trigger batch remains pending */
    ENTASIS_COLLIDER_PART_PENDING = 2,
    /* contact history/output remains undelivered. only returned by the contact-aware update */
    ENTASIS_COLLIDER_CONTACT_PENDING = 4
};

/**
 * independent physical breaking metrics
 */
enum {
    /* no watched metrics */
    ENTASIS_JOINT_BREAK_NONE = 0,
    /* compare peak force magnitude */
    ENTASIS_JOINT_BREAK_FORCE = 1,
    /* compare peak torque magnitude */
    ENTASIS_JOINT_BREAK_TORQUE = 2
};

/**
 * committed reaction validity
 */
enum {
    /* no committed solved sample */
    ENTASIS_JOINT_REACTION_UNSOLVED = 0,
    /* a completed step committed this sample */
    ENTASIS_JOINT_REACTION_SOLVED = 1
};

/**
 * pending streams in a joint-break stepper result
 */
enum {
    /* parent trigger batch remains pending */
    ENTASIS_JOINT_BREAK_PENDING_PARENT = 1,
    /* part trigger batch remains pending */
    ENTASIS_JOINT_BREAK_PENDING_PART = 2,
    /* contact delivery remains pending */
    ENTASIS_JOINT_BREAK_PENDING_CONTACT = 4,
    /* break publication or delivery remains pending */
    ENTASIS_JOINT_BREAK_PENDING_BREAK = 8
};

typedef struct entasis_string_view_t entasis_string_view_t;
typedef struct entasis_body_handle_t entasis_body_handle_t;
typedef struct entasis_static_handle_t entasis_static_handle_t;
typedef struct entasis_constraint_handle_t entasis_constraint_handle_t;
typedef struct entasis_shape_handle_t entasis_shape_handle_t;
typedef struct entasis_vector2_t entasis_vector2_t;
typedef struct entasis_vector3_t entasis_vector3_t;
typedef struct entasis_vector4_t entasis_vector4_t;
typedef struct entasis_quaternion_t entasis_quaternion_t;
typedef struct entasis_symmetric3x3_t entasis_symmetric3x3_t;
typedef struct entasis_continuous_detection_t entasis_continuous_detection_t;
typedef struct entasis_activity_description_t entasis_activity_description_t;
typedef struct entasis_collidable_reference_t entasis_collidable_reference_t;
typedef struct entasis_diagnostic_t entasis_diagnostic_t;
typedef struct entasis_allocator_t entasis_allocator_t;
typedef struct entasis_world_t entasis_world_t;
typedef struct entasis_buffer_pool_t entasis_buffer_pool_t;
typedef struct entasis_thread_pool_t entasis_thread_pool_t;
typedef struct entasis_damping_t entasis_damping_t;
typedef struct entasis_capacity_hints_t entasis_capacity_hints_t;
typedef struct entasis_spring_settings_t entasis_spring_settings_t;
typedef struct entasis_per_body_gravity_policy_t entasis_per_body_gravity_policy_t;
typedef struct entasis_dispatcher_interface_t entasis_dispatcher_interface_t;
typedef struct entasis_solve_description_t entasis_solve_description_t;
typedef struct entasis_threading_description_t entasis_threading_description_t;
typedef struct entasis_world_stats_t entasis_world_stats_t;
typedef struct entasis_sphere_t entasis_sphere_t;
typedef struct entasis_capsule_t entasis_capsule_t;
typedef struct entasis_box_t entasis_box_t;
typedef struct entasis_cylinder_t entasis_cylinder_t;
typedef struct entasis_compound_builder_t entasis_compound_builder_t;
typedef struct entasis_material_table_t entasis_material_table_t;
typedef struct entasis_collision_filter_t entasis_collision_filter_t;
typedef struct entasis_collision_properties_t entasis_collision_properties_t;
typedef struct entasis_layer_matrix_t entasis_layer_matrix_t;
typedef struct entasis_collision_property_table_t entasis_collision_property_table_t;
typedef struct entasis_cooking_context_t entasis_cooking_context_t;
typedef struct entasis_cooked_hull_t entasis_cooked_hull_t;
typedef struct entasis_cooked_mesh_t entasis_cooked_mesh_t;
typedef struct entasis_cooked_compound_t entasis_cooked_compound_t;
typedef struct entasis_cooked_big_compound_t entasis_cooked_big_compound_t;
typedef struct entasis_motor_settings_t entasis_motor_settings_t;
typedef struct entasis_servo_settings_t entasis_servo_settings_t;
typedef struct entasis_fixed_stepper_t entasis_fixed_stepper_t;
typedef struct entasis_command_t entasis_command_t;
typedef struct entasis_command_buffer_t entasis_command_buffer_t;
typedef struct entasis_sweep_settings_t entasis_sweep_settings_t;
typedef struct entasis_query_filter_t entasis_query_filter_t;
typedef struct entasis_query_output_t entasis_query_output_t;
typedef struct entasis_query_t entasis_query_t;
typedef struct entasis_query_result_t entasis_query_result_t;
typedef struct entasis_query_scratch_t entasis_query_scratch_t;
typedef struct entasis_contact_tracker_t entasis_contact_tracker_t;
typedef struct entasis_contact_user_table_t entasis_contact_user_table_t;
typedef struct entasis_body_activity_t entasis_body_activity_t;
typedef struct entasis_active_body_view_t entasis_active_body_view_t;
typedef struct entasis_static_view_t entasis_static_view_t;
typedef struct entasis_profile_snapshot_t entasis_profile_snapshot_t;
typedef struct entasis_world_solver_stats_t entasis_world_solver_stats_t;
typedef struct entasis_body_property_table_t entasis_body_property_table_t;
typedef struct entasis_static_property_table_t entasis_static_property_table_t;
typedef struct entasis_collidable_property_table_t entasis_collidable_property_table_t;
typedef struct entasis_query_context_t entasis_query_context_t;
typedef struct entasis_query_context_description_t entasis_query_context_description_t;
typedef struct entasis_f32x8_t entasis_f32x8_t;
typedef struct entasis_i32x8_t entasis_i32x8_t;
typedef struct entasis_pose_integration_view_t entasis_pose_integration_view_t;
typedef struct entasis_velocity_callbacks_t entasis_velocity_callbacks_t;
typedef struct entasis_contact_callbacks_t entasis_contact_callbacks_t;
typedef struct entasis_timestep_callbacks_t entasis_timestep_callbacks_t;
typedef struct entasis_timestepper_t entasis_timestepper_t;
typedef struct entasis_substep_scheduler_t entasis_substep_scheduler_t;
typedef struct entasis_world_extensions_t entasis_world_extensions_t;
typedef struct entasis_shape_access_t entasis_shape_access_t;
typedef struct entasis_custom_shape_view_t entasis_custom_shape_view_t;
typedef struct entasis_custom_shape_registration_t entasis_custom_shape_registration_t;
typedef struct entasis_task_access_t entasis_task_access_t;
typedef struct entasis_collision_task_wide_input_t entasis_collision_task_wide_input_t;
typedef struct entasis_collision_task_registration_t entasis_collision_task_registration_t;
typedef struct entasis_sweep_task_registration_t entasis_sweep_task_registration_t;
typedef struct entasis_compound_task_registration_t entasis_compound_task_registration_t;
typedef struct entasis_constraint_body_view_t entasis_constraint_body_view_t;
typedef struct entasis_constraint_kernel_view_t entasis_constraint_kernel_view_t;
typedef struct entasis_custom_constraint_registration_t entasis_custom_constraint_registration_t;
typedef struct entasis_trigger_configuration_t entasis_trigger_configuration_t;
typedef struct entasis_trigger_settings_t entasis_trigger_settings_t;
typedef struct entasis_trigger_update_result_t entasis_trigger_update_result_t;
typedef struct entasis_restitution_settings_t entasis_restitution_settings_t;
typedef struct entasis_distance_query_settings_t entasis_distance_query_settings_t;
typedef struct entasis_distance_query_capacity_t entasis_distance_query_capacity_t;
typedef struct entasis_body_control_configuration_t entasis_body_control_configuration_t;
typedef struct entasis_body_damping_t entasis_body_damping_t;
typedef struct entasis_collider_part_configuration_t entasis_collider_part_configuration_t;
typedef struct entasis_collider_part_settings_t entasis_collider_part_settings_t;
typedef struct entasis_collider_part_identity_t entasis_collider_part_identity_t;
typedef struct entasis_collider_part_update_result_t entasis_collider_part_update_result_t;
typedef struct entasis_collider_part_contact_update_result_t entasis_collider_part_contact_update_result_t;
typedef struct entasis_joint_reaction_provider_t entasis_joint_reaction_provider_t;
typedef struct entasis_joint_break_limits_t entasis_joint_break_limits_t;
typedef struct entasis_joint_break_update_result_t entasis_joint_break_update_result_t;
typedef struct entasis_version_t entasis_version_t;
typedef struct entasis_matrix3x3_t entasis_matrix3x3_t;
typedef struct entasis_bounding_box_t entasis_bounding_box_t;
typedef struct entasis_rigid_pose_t entasis_rigid_pose_t;
typedef struct entasis_body_velocity_t entasis_body_velocity_t;
typedef struct entasis_body_inertia_t entasis_body_inertia_t;
typedef struct entasis_collidable_description_t entasis_collidable_description_t;
typedef struct entasis_ray_t entasis_ray_t;
typedef struct entasis_contact_material_t entasis_contact_material_t;
typedef struct entasis_uniform_gravity_policy_t entasis_uniform_gravity_policy_t;
typedef struct entasis_planetary_gravity_policy_t entasis_planetary_gravity_policy_t;
typedef struct entasis_pose_policy_t entasis_pose_policy_t;
typedef struct entasis_triangle_t entasis_triangle_t;
typedef struct entasis_shape_bounds_t entasis_shape_bounds_t;
typedef struct entasis_shape_ray_hit_t entasis_shape_ray_hit_t;
typedef struct entasis_shape_info_t entasis_shape_info_t;
typedef struct entasis_compound_child_t entasis_compound_child_t;
typedef struct entasis_material_t entasis_material_t;
typedef struct entasis_angular_axis_gear_motor_t entasis_angular_axis_gear_motor_t;
typedef struct entasis_angular_axis_motor_t entasis_angular_axis_motor_t;
typedef struct entasis_angular_hinge_t entasis_angular_hinge_t;
typedef struct entasis_angular_motor_t entasis_angular_motor_t;
typedef struct entasis_angular_servo_t entasis_angular_servo_t;
typedef struct entasis_angular_swivel_hinge_t entasis_angular_swivel_hinge_t;
typedef struct entasis_area_constraint_t entasis_area_constraint_t;
typedef struct entasis_ball_socket_t entasis_ball_socket_t;
typedef struct entasis_ball_socket_motor_t entasis_ball_socket_motor_t;
typedef struct entasis_ball_socket_servo_t entasis_ball_socket_servo_t;
typedef struct entasis_center_distance_constraint_t entasis_center_distance_constraint_t;
typedef struct entasis_center_distance_limit_t entasis_center_distance_limit_t;
typedef struct entasis_distance_limit_t entasis_distance_limit_t;
typedef struct entasis_distance_servo_t entasis_distance_servo_t;
typedef struct entasis_hinge_t entasis_hinge_t;
typedef struct entasis_linear_axis_limit_t entasis_linear_axis_limit_t;
typedef struct entasis_linear_axis_motor_t entasis_linear_axis_motor_t;
typedef struct entasis_linear_axis_servo_t entasis_linear_axis_servo_t;
typedef struct entasis_one_body_angular_motor_t entasis_one_body_angular_motor_t;
typedef struct entasis_one_body_angular_servo_t entasis_one_body_angular_servo_t;
typedef struct entasis_one_body_linear_motor_t entasis_one_body_linear_motor_t;
typedef struct entasis_one_body_linear_servo_t entasis_one_body_linear_servo_t;
typedef struct entasis_point_on_line_servo_t entasis_point_on_line_servo_t;
typedef struct entasis_swing_limit_t entasis_swing_limit_t;
typedef struct entasis_swivel_hinge_t entasis_swivel_hinge_t;
typedef struct entasis_twist_limit_t entasis_twist_limit_t;
typedef struct entasis_twist_motor_t entasis_twist_motor_t;
typedef struct entasis_twist_servo_t entasis_twist_servo_t;
typedef struct entasis_volume_constraint_t entasis_volume_constraint_t;
typedef struct entasis_weld_t entasis_weld_t;
typedef struct entasis_constraint_info_t entasis_constraint_info_t;
typedef struct entasis_solver_contact_point_t entasis_solver_contact_point_t;
typedef struct entasis_ray_hit_t entasis_ray_hit_t;
typedef struct entasis_sweep_result_t entasis_sweep_result_t;
typedef struct entasis_contact_point_t entasis_contact_point_t;
typedef struct entasis_convex_contact_t entasis_convex_contact_t;
typedef struct entasis_volume_hit_t entasis_volume_hit_t;
typedef struct entasis_collidable_state_t entasis_collidable_state_t;
typedef struct entasis_active_body_row_t entasis_active_body_row_t;
typedef struct entasis_static_row_t entasis_static_row_t;
typedef struct entasis_body_property_key_t entasis_body_property_key_t;
typedef struct entasis_static_property_key_t entasis_static_property_key_t;
typedef struct entasis_collidable_property_key_t entasis_collidable_property_key_t;
typedef struct entasis_vector3_wide_t entasis_vector3_wide_t;
typedef struct entasis_quaternion_wide_t entasis_quaternion_wide_t;
typedef struct entasis_symmetric3x3_wide_t entasis_symmetric3x3_wide_t;
typedef struct entasis_step_scope_t entasis_step_scope_t;
typedef struct entasis_sweep_task_result_t entasis_sweep_task_result_t;
typedef struct entasis_trigger_pair_t entasis_trigger_pair_t;
typedef struct entasis_restitution_configuration_t entasis_restitution_configuration_t;
typedef struct entasis_distance_geometry_t entasis_distance_geometry_t;
typedef struct entasis_shape_correction_result_t entasis_shape_correction_result_t;
typedef struct entasis_collider_part_info_t entasis_collider_part_info_t;
typedef struct entasis_collider_part_endpoint_t entasis_collider_part_endpoint_t;
typedef struct entasis_joint_impulse_wrench_t entasis_joint_impulse_wrench_t;
typedef struct entasis_joint_force_wrench_t entasis_joint_force_wrench_t;
typedef struct entasis_body_description_t entasis_body_description_t;
typedef struct entasis_static_description_t entasis_static_description_t;
typedef struct entasis_default_narrow_policy_t entasis_default_narrow_policy_t;
typedef struct entasis_compound_build_result_t entasis_compound_build_result_t;
typedef struct entasis_mesh_mass_properties_t entasis_mesh_mass_properties_t;
typedef struct entasis_layer_material_policy_t entasis_layer_material_policy_t;
typedef struct entasis_cooked_compound_child_t entasis_cooked_compound_child_t;
typedef struct entasis_cooked_big_compound_child_t entasis_cooked_big_compound_child_t;
typedef struct entasis_solver_contact_data_t entasis_solver_contact_data_t;
typedef struct entasis_sweep_hit_t entasis_sweep_hit_t;
typedef struct entasis_nonconvex_contact_manifold_t entasis_nonconvex_contact_manifold_t;
typedef struct entasis_convex_contact_manifold_t entasis_convex_contact_manifold_t;
typedef struct entasis_collision_query_t entasis_collision_query_t;
typedef struct entasis_motion_state_t entasis_motion_state_t;
typedef struct entasis_body_inertias_t entasis_body_inertias_t;
typedef struct entasis_static_view_record_t entasis_static_view_record_t;
typedef struct entasis_body_inertia_wide_t entasis_body_inertia_wide_t;
typedef struct entasis_body_velocity_wide_t entasis_body_velocity_wide_t;
typedef struct entasis_collision_task_input_t entasis_collision_task_input_t;
typedef struct entasis_convex_contact_wide_t entasis_convex_contact_wide_t;
typedef struct entasis_sweep_task_input_t entasis_sweep_task_input_t;
typedef struct entasis_trigger_event_t entasis_trigger_event_t;
typedef struct entasis_shape_distance_result_t entasis_shape_distance_result_t;
typedef struct entasis_distance_query_t entasis_distance_query_t;
typedef struct entasis_body_axis_lock_t entasis_body_axis_lock_t;
typedef struct entasis_collider_part_pair_t entasis_collider_part_pair_t;
typedef struct entasis_joint_reaction_provider_input_t entasis_joint_reaction_provider_input_t;
typedef struct entasis_joint_reaction_sample_t entasis_joint_reaction_sample_t;
typedef struct entasis_world_description_t entasis_world_description_t;
typedef struct entasis_narrow_policy_t entasis_narrow_policy_t;
typedef struct entasis_contact_manifold_t entasis_contact_manifold_t;
typedef struct entasis_contact_event_t entasis_contact_event_t;
typedef struct entasis_body_dynamics_t entasis_body_dynamics_t;
typedef struct entasis_convex_manifold_wide_t entasis_convex_manifold_wide_t;
typedef struct entasis_distance_query_result_t entasis_distance_query_result_t;
typedef struct entasis_collider_part_event_t entasis_collider_part_event_t;
typedef struct entasis_joint_reaction_t entasis_joint_reaction_t;
typedef struct entasis_overlap_hit_t entasis_overlap_hit_t;
typedef struct entasis_collision_query_result_t entasis_collision_query_result_t;
typedef struct entasis_joint_break_event_t entasis_joint_break_event_t;

/**
 * packed body or static identity used by queries and callbacks
 */
struct entasis_collidable_reference_t {
    /* packed mobility class and handle value */
    uint32_t packed;
};

/**
 * borrowed UTF-8 byte range that does not require NUL termination
 */
struct entasis_string_view_t {
    /* pointer to the first UTF-8 byte */
    const char * data;
    /* number of valid bytes */
    uint64_t count;
};

/**
 * live body handle whose numeric value may be reused after removal
 */
struct entasis_body_handle_t {
    /* signed body handle value. negative values are invalid */
    int32_t value;
};

/**
 * live static handle whose numeric value may be reused after removal
 */
struct entasis_static_handle_t {
    /* signed static handle value. negative values are invalid */
    int32_t value;
};

/**
 * live constraint handle whose numeric value may be reused after removal
 */
struct entasis_constraint_handle_t {
    /* signed constraint handle value. negative values are invalid */
    int32_t value;
};

/**
 * typed registered shape handle whose slot may be reused after removal
 */
struct entasis_shape_handle_t {
    /* packed presence bit, shape type ID and slot index */
    uint32_t packed;
};

/**
 * two-component single-precision vector
 */
struct entasis_vector2_t {
    /* X component */
    float x;
    /* Y component */
    float y;
};

/**
 * three-component single-precision vector
 */
struct entasis_vector3_t {
    /* X component */
    float x;
    /* Y component */
    float y;
    /* Z component */
    float z;
};

/**
 * four-component single-precision vector
 */
struct entasis_vector4_t {
    /* X component */
    float x;
    /* Y component */
    float y;
    /* Z component */
    float z;
    /* W component */
    float w;
};

/**
 * single-precision quaternion
 */
struct entasis_quaternion_t {
    /* X component */
    float x;
    /* Y component */
    float y;
    /* Z component */
    float z;
    /* W component */
    float w;
};

/**
 * compact symmetric three-by-three matrix
 */
struct entasis_symmetric3x3_t {
    /* XX matrix component */
    float xx;
    /* YX and XY matrix component */
    float yx;
    /* YY matrix component */
    float yy;
    /* ZX and XZ matrix component */
    float zx;
    /* ZY and YZ matrix component */
    float zy;
    /* ZZ matrix component */
    float zz;
};

/**
 * continuous collision detection settings for one collidable
 */
struct entasis_continuous_detection_t {
    /* continuous collision detection mode */
    entasis_continuous_detection_mode_t mode;
    /* reserved for ABI compatibility */
    uint8_t reserved[3];
    /* smallest sweep interval accepted by continuous collision detection */
    float minimum_sweep_timestep;
    /* convergence threshold used by continuous sweep refinement */
    float sweep_convergence_threshold;
};

/**
 * optional allocation-free failure context
 */
struct entasis_diagnostic_t {
    /* operation status */
    entasis_status_t status;
    /* operation that produced the diagnostic */
    entasis_diagnostic_operation_t operation;
    /* reserved for ABI compatibility */
    uint8_t reserved[2];
    /* operation-specific detail value */
    int32_t detail;
};

/**
 * eight aligned floating-point lanes passed by pointer at foreign callback boundaries
 */
struct entasis_f32x8_t {
    /* eight scalar lanes in native lane order */
    ENTASIS_ALIGNAS(32) float lanes[8];
};

/**
 * eight aligned integer lanes passed by pointer at foreign callback boundaries
 */
struct entasis_i32x8_t {
    /* eight integer lanes. active masks use nonzero values for active lanes */
    ENTASIS_ALIGNAS(32) int32_t lanes[8];
};

/**
 * compile-time Entasis product version
 */
struct entasis_version_t {
    /* major version component */
    uint16_t major;
    /* minor version component */
    uint16_t minor;
    /* patch version component */
    uint16_t patch;
    /* reserved for ABI compatibility */
    uint16_t reserved;
    /* borrowed prerelease identifier, empty for a stable release */
    entasis_string_view_t prerelease;
};

/**
 * three-by-three matrix stored as three basis vectors
 */
struct entasis_matrix3x3_t {
    /* first basis vector */
    entasis_vector3_t x;
    /* second basis vector */
    entasis_vector3_t y;
    /* third basis vector */
    entasis_vector3_t z;
};

/**
 * axis-aligned minimum and maximum bounds
 */
struct entasis_bounding_box_t {
    /* minimum corner */
    entasis_vector3_t min;
    /* reserved for ABI compatibility */
    float reserved_min;
    /* maximum corner */
    entasis_vector3_t max;
    /* reserved for ABI compatibility */
    float reserved_max;
};

/**
 * world or local position and orientation
 */
struct entasis_rigid_pose_t {
    /* rotation quaternion */
    entasis_quaternion_t orientation;
    /* world or local translation */
    entasis_vector3_t position;
    /* reserved for ABI compatibility */
    float reserved;
};

/**
 * linear and angular velocity
 */
struct entasis_body_velocity_t {
    /* linear velocity */
    entasis_vector3_t linear;
    /* reserved for ABI compatibility */
    float reserved_linear;
    /* angular velocity */
    entasis_vector3_t angular;
    /* reserved for ABI compatibility */
    float reserved_angular;
};

/**
 * inverse mass and body-local inverse inertia tensor
 */
struct entasis_body_inertia_t {
    /* body-local inverse inertia tensor */
    entasis_symmetric3x3_t inverse_inertia_tensor;
    /* inverse body mass. zero selects kinematic behavior */
    float inverse_mass;
    /* reserved for ABI compatibility */
    float reserved;
};

/**
 * world-space ray with a bounded parameter interval
 */
struct entasis_ray_t {
    /* ray origin */
    entasis_vector3_t origin;
    /* ray direction */
    entasis_vector3_t direction;
    /* maximum ray parameter */
    float maximum_t;
};

/**
 * eight-lane vector3 stored component-wise. callback-local pointer view
 */
struct entasis_vector3_wide_t {
    /* eight x components */
    entasis_f32x8_t x;
    /* eight y components */
    entasis_f32x8_t y;
    /* eight z components */
    entasis_f32x8_t z;
};

/**
 * eight-lane quaternion stored component-wise. callback-local pointer view
 */
struct entasis_quaternion_wide_t {
    /* eight x components */
    entasis_f32x8_t x;
    /* eight y components */
    entasis_f32x8_t y;
    /* eight z components */
    entasis_f32x8_t z;
    /* eight w components */
    entasis_f32x8_t w;
};

/**
 * eight-lane symmetric3x3 stored component-wise. callback-local pointer view
 */
struct entasis_symmetric3x3_wide_t {
    /* eight xx components */
    entasis_f32x8_t xx;
    /* eight yx components */
    entasis_f32x8_t yx;
    /* eight yy components */
    entasis_f32x8_t yy;
    /* eight zx components */
    entasis_f32x8_t zx;
    /* eight zy components */
    entasis_f32x8_t zy;
    /* eight zz components */
    entasis_f32x8_t zz;
};

/**
 * read-only eight-lane body inertia view
 */
struct entasis_body_inertia_wide_t {
    /* world-space inverse inertia tensor lanes */
    entasis_symmetric3x3_wide_t inverse_inertia_tensor;
    /* inverse mass lanes */
    entasis_f32x8_t inverse_mass;
};

/**
 * writable eight-lane velocity view
 */
struct entasis_body_velocity_wide_t {
    /* linear velocity lanes */
    entasis_vector3_wide_t linear;
    /* angular velocity lanes */
    entasis_vector3_wide_t angular;
};

#ifdef __cplusplus
#  define ENTASIS_STRING_VIEW_LITERAL(value) entasis_string_view_t{(value), (uint64_t)(sizeof(value) - 1u)}
#  define ENTASIS_CURRENT_VERSION entasis_version_t{ENTASIS_VERSION_MAJOR, ENTASIS_VERSION_MINOR, ENTASIS_VERSION_PATCH, UINT16_C(0), ENTASIS_STRING_VIEW_LITERAL(ENTASIS_VERSION_PRERELEASE)}
#else
#  define ENTASIS_STRING_VIEW_LITERAL(value) ((entasis_string_view_t){(value), (uint64_t)(sizeof(value) - 1u)})
#  define ENTASIS_CURRENT_VERSION ((entasis_version_t){ENTASIS_VERSION_MAJOR, ENTASIS_VERSION_MINOR, ENTASIS_VERSION_PATCH, UINT16_C(0), ENTASIS_STRING_VIEW_LITERAL(ENTASIS_VERSION_PRERELEASE)})
#endif

/**
 * returns the runtime C ABI generation used by this library
 *
 * @return returns ENTASIS_ABI_VERSION for a compatible runtime library
 */
ENTASIS_API uint32_t ENTASIS_CALL entasis_abi_version(void);

/**
 * returns the current Entasis product version
 *
 * @return returns the runtime product version
 */
ENTASIS_API entasis_version_t ENTASIS_CALL entasis_version_current(void);

/**
 * returns ENTASIS_TRUE only for ENTASIS_STATUS_OK
 *
 * @param status status to test or describe
 *
 * @return returns ENTASIS_TRUE when status is ENTASIS_STATUS_OK
 */
ENTASIS_API entasis_bool_t ENTASIS_CALL entasis_status_ok(entasis_status_t status);

/**
 * returns ENTASIS_TRUE for any non-OK status
 *
 * @param status status to test or describe
 *
 * @return returns ENTASIS_TRUE when status is not ENTASIS_STATUS_OK
 */
ENTASIS_API entasis_bool_t ENTASIS_CALL entasis_status_failed(entasis_status_t status);

/**
 * returns a process-lifetime borrowed status string
 *
 * @param status status to test or describe
 *
 * @return returns a borrowed static string describing status
 */
ENTASIS_API entasis_string_view_t ENTASIS_CALL entasis_status_text(entasis_status_t status);

/**
 * clears optional caller-owned diagnostic storage
 *
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return no return value
 */
ENTASIS_API void ENTASIS_CALL entasis_diagnostic_clear(entasis_diagnostic_t * diagnostic);

/**
 * records allocation-free cold-path failure context
 *
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 * @param status status to test or describe
 * @param operation operation category to record
 * @param detail operation-specific diagnostic detail
 *
 * @return no return value
 */
ENTASIS_API void ENTASIS_CALL entasis_diagnostic_record(entasis_diagnostic_t * diagnostic, entasis_status_t status, entasis_diagnostic_operation_t operation, int32_t detail);

/**
 * returns the invalid body handle sentinel
 *
 * @return returns the invalid body handle sentinel
 */
ENTASIS_API entasis_body_handle_t ENTASIS_CALL entasis_body_handle_invalid(void);

/**
 * checks the body handle sentinel representation
 *
 * checks representation only, not whether the object is alive. stop using a handle when its object is removed. a reused slot may identify a different object
 *
 * @param handle target body handle
 *
 * @return returns ENTASIS_TRUE when handle is not the invalid body sentinel
 */
ENTASIS_API entasis_bool_t ENTASIS_CALL entasis_body_handle_is_valid(entasis_body_handle_t handle);

/**
 * returns the invalid static handle sentinel
 *
 * @return returns the invalid static handle sentinel
 */
ENTASIS_API entasis_static_handle_t ENTASIS_CALL entasis_static_handle_invalid(void);

/**
 * checks the static handle sentinel representation
 *
 * checks representation only, not whether the object is alive. stop using a handle when its object is removed. a reused slot may identify a different object
 *
 * @param handle target static handle
 *
 * @return returns ENTASIS_TRUE when handle is not the invalid static sentinel
 */
ENTASIS_API entasis_bool_t ENTASIS_CALL entasis_static_handle_is_valid(entasis_static_handle_t handle);

/**
 * returns the invalid constraint handle sentinel
 *
 * @return returns the invalid constraint handle sentinel
 */
ENTASIS_API entasis_constraint_handle_t ENTASIS_CALL entasis_constraint_handle_invalid(void);

/**
 * checks the constraint handle sentinel representation
 *
 * checks representation only, not whether the object is alive. stop using a handle when its object is removed. a reused slot may identify a different object
 *
 * @param handle target constraint handle
 *
 * @return returns ENTASIS_TRUE when handle is not the invalid constraint sentinel
 */
ENTASIS_API entasis_bool_t ENTASIS_CALL entasis_constraint_handle_is_valid(entasis_constraint_handle_t handle);

/**
 * returns the missing shape handle sentinel
 *
 * @return returns the invalid shape handle sentinel
 */
ENTASIS_API entasis_shape_handle_t ENTASIS_CALL entasis_shape_handle_invalid(void);

/**
 * checks the shape-handle presence bit
 *
 * checks representation only, not whether the object is alive. stop using a handle when its object is removed. a reused slot may identify a different object
 *
 * @param handle target shape handle
 *
 * @return returns ENTASIS_TRUE when the shape handle contains a present slot
 */
ENTASIS_API entasis_bool_t ENTASIS_CALL entasis_shape_handle_is_valid(entasis_shape_handle_t handle);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* ENTASIS_BASE_H */
