// generated by tools/abi/generate_abi. do not edit
#ifndef ENTASIS_BODIES_H
#define ENTASIS_BODIES_H

#include <entasis/shapes.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * selects which overlapping sleeping-body islands may wake during one static mutation
 *
 * @param user_context caller-owned callback state, borrowed until the static mutation returns
 * @param body sleeping dynamic body whose island overlaps the changed static
 *
 * @return returns true to allow waking the body island
 */
typedef entasis_bool_t (ENTASIS_CALL *entasis_static_awakening_filter_fn)(void * user_context, entasis_body_handle_t body);

/**
 * sleep threshold settings for one body
 */
struct entasis_activity_description_t {
    /* motion threshold below which sleep can be considered */
    float sleep_threshold;
    /* consecutive steps required below the sleep threshold */
    uint8_t minimum_timestep_count_under_threshold;
    /* reserved for ABI compatibility */
    uint8_t reserved[3];
};

/**
 * copied configuration for optional body-control storage
 */
struct entasis_body_control_configuration_t {
    /* size of this structure */
    uint32_t struct_size;
    /* must be ENTASIS_STRUCT_VERSION */
    uint32_t struct_version;
    /* capacity for force and target entries, independently in each table */
    int32_t input_capacity;
    /* capacity for persistent damping settings */
    int32_t settings_capacity;
};

/**
 * exponential attenuation exp(-rate * integrated duration), distinct from the world damping fraction
 */
struct entasis_body_damping_t {
    /* finite nonnegative linear attenuation rate per second */
    float linear;
    /* finite nonnegative angular attenuation rate per second */
    float angular;
    /* Additional or recognized-native-policy Override */
    entasis_body_damping_mode_t mode;
};

/**
 * shape, CCD, and speculative margin settings for one body
 */
struct entasis_collidable_description_t {
    /* registered shape handle */
    entasis_shape_handle_t shape;
    /* continuous collision detection settings */
    entasis_continuous_detection_t continuity;
    /* minimum speculative contact margin */
    float minimum_speculative_margin;
    /* maximum speculative contact margin */
    float maximum_speculative_margin;
};

/**
 * complete pointer-free body description used for creation and replacement
 */
struct entasis_body_description_t {
    /* rigid pose */
    entasis_rigid_pose_t pose;
    /* linear and angular velocity */
    entasis_body_velocity_t velocity;
    /* body-local inverse inertia and inverse mass */
    entasis_body_inertia_t local_inertia;
    /* collidable description or identity */
    entasis_collidable_description_t collidable;
    /* sleep settings or active sleep state */
    entasis_activity_description_t activity;
};

/**
 * complete pointer-free static description used for creation and replacement
 */
struct entasis_static_description_t {
    /* rigid pose */
    entasis_rigid_pose_t pose;
    /* registered shape handle */
    entasis_shape_handle_t shape;
    /* continuous collision detection settings */
    entasis_continuous_detection_t continuity;
};

/**
 * one engine-owned one-body constraint. no post-solve velocity clamping. zero axes remove the lock. changing rows resets its accumulated impulses
 */
struct entasis_body_axis_lock_t {
    /* size of this structure */
    uint32_t struct_size;
    /* must be ENTASIS_STRUCT_VERSION */
    uint32_t struct_version;
    /* explicit captured position and orientation, not inferred from later body motion */
    entasis_rigid_pose_t reference;
    /* world-space coordinate rows */
    entasis_body_lock_axes_t linear_axes;
    /* angular rows in the supplied reference orientation */
    entasis_body_lock_axes_t angular_axes;
    /* finite positive angular frequency and nonnegative damping. existing constraint softness semantics */
    entasis_spring_settings_t spring_settings;
};

/**
 * pointer-free copy of one body state with the same layout as entasis_body_description_t
 */
typedef entasis_body_description_t entasis_body_state_t;
/**
 * pointer-free copy of one static state with the same layout as entasis_static_description_t
 */
typedef entasis_static_description_t entasis_static_state_t;

/**
 * constructs sleeping thresholds
 *
 * a negative sleep threshold disables automatic sleep for the body
 *
 * @param sleep_threshold motion threshold below which sleep can be considered
 * @param minimum_timesteps_under_threshold consecutive steps required below the sleep threshold
 *
 * @return returns the activity description
 */
ENTASIS_API entasis_activity_description_t ENTASIS_CALL entasis_body_activity(float sleep_threshold, uint8_t minimum_timesteps_under_threshold);

/**
 * returns the ordinary facade sleep policy
 *
 * @return returns the default activity description
 */
ENTASIS_API entasis_activity_description_t ENTASIS_CALL entasis_body_activity_default(void);

/**
 * adds one body
 *
 * allocation may occur when world capacity grows. ownership: owner thread only while the world is idle
 *
 * @param world target world
 * @param description body description to copy
 * @param out_handle receives the created body handle
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_add(entasis_world_t * world, const entasis_body_description_t * description, entasis_body_handle_t * out_handle, entasis_diagnostic_t * diagnostic);

/**
 * adds a prefix of descriptions in input order after one capacity check
 *
 * out_handles must contain at least count entries. on failure, out_completed receives the number of successfully committed prefix entries and entries at or after that index remain invalid. allocation: the initial capacity check may grow world storage. ownership: owner thread only while the world is idle
 *
 * @param world target world
 * @param descriptions input body description array
 * @param count number of entries in the input arrays
 * @param out_handles receives body handles in input order
 * @param out_completed receives the number of successfully completed prefix entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_add_batch(entasis_world_t * world, const entasis_body_description_t * descriptions, uint64_t count, entasis_body_handle_t * out_handles, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * replaces the complete body description
 *
 * the body is awakened and broad-phase membership is updated when required. ownership: owner thread only while the world is idle
 *
 * @param world target world
 * @param handle target body handle
 * @param description body description to copy
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_apply(entasis_world_t * world, entasis_body_handle_t handle, const entasis_body_description_t * description, entasis_diagnostic_t * diagnostic);

/**
 * applies matching handles and descriptions in input order
 *
 * a failure stops the batch. out_completed reports the number of applied entries and identifies the first failing index. earlier changes remain applied. allocation may occur through body mutation. ownership: owner thread only while the world is idle
 *
 * @param world target world
 * @param handles input body handles
 * @param descriptions input body description array
 * @param count number of entries in the input arrays
 * @param out_completed receives the number of successfully completed prefix entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_apply_batch(entasis_world_t * world, const entasis_body_handle_t * handles, const entasis_body_description_t * descriptions, uint64_t count, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * constructs a dynamic collidable body description
 *
 * @param shape registered shape handle
 * @param inertia body-local inverse inertia and inverse mass
 * @param pose rigid pose
 * @param velocity linear and angular velocity
 * @param activity sleep settings
 *
 * @return returns the constructed body description
 */
ENTASIS_API entasis_body_description_t ENTASIS_CALL entasis_body_dynamic(entasis_shape_handle_t shape, entasis_body_inertia_t inertia, entasis_rigid_pose_t pose, entasis_body_velocity_t velocity, entasis_activity_description_t activity);

/**
 * copies the description of one active or sleeping body
 *
 * allocation: none. the returned value contains no pointers into simulation data
 *
 * @param world target world
 * @param handle target body handle
 * @param out_state receives the copied body state
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_get(entasis_world_t * world, entasis_body_handle_t handle, entasis_body_state_t * out_state, entasis_diagnostic_t * diagnostic);

/**
 * copies body snapshots for a prefix of handles into caller-owned output storage
 *
 * @param world target world
 * @param handles input body handles
 * @param count number of entries in the input arrays
 * @param out_states receives copied body states in input order
 * @param out_completed receives the number of successfully completed prefix entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_get_batch(entasis_world_t * world, const entasis_body_handle_t * handles, uint64_t count, entasis_body_state_t * out_states, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * constructs a kinematic collidable body description
 *
 * @param shape registered shape handle
 * @param pose rigid pose
 * @param velocity linear and angular velocity
 * @param activity sleep settings
 *
 * @return returns the constructed body description
 */
ENTASIS_API entasis_body_description_t ENTASIS_CALL entasis_body_kinematic(entasis_shape_handle_t shape, entasis_rigid_pose_t pose, entasis_body_velocity_t velocity, entasis_activity_description_t activity);

/**
 * removes a body and every connected constraint
 *
 * ownership: owner thread only while the world is idle
 *
 * @param world target world
 * @param handle target body handle
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_remove(entasis_world_t * world, entasis_body_handle_t handle, entasis_diagnostic_t * diagnostic);

/**
 * removes handles in input order
 *
 * a failure stops the batch. out_completed reports how many bodies were removed and identifies the first failing index. earlier removals remain applied. ownership: owner thread only while the world is idle
 *
 * @param world target world
 * @param handles input body handles
 * @param count number of entries in the input arrays
 * @param out_completed receives the number of successfully completed prefix entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_remove_batch(entasis_world_t * world, const entasis_body_handle_t * handles, uint64_t count, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * updates sleep thresholds and resets the activity counters
 *
 * @param world target world
 * @param handle target body handle
 * @param value activity description
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_set_activity(entasis_world_t * world, entasis_body_handle_t handle, const entasis_activity_description_t * value, entasis_diagnostic_t * diagnostic);

/**
 * applies activity descriptions to a prefix of body handles in input order
 *
 * @param world target world
 * @param handles input body handles
 * @param values input activity description array
 * @param count number of entries in the input arrays
 * @param out_completed receives the number of successfully completed prefix entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_set_activity_batch(entasis_world_t * world, const entasis_body_handle_t * handles, const entasis_activity_description_t * values, uint64_t count, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * updates shape, continuity, and speculative margins
 *
 * @param world target world
 * @param handle target body handle
 * @param value collidable description
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_set_collidable(entasis_world_t * world, entasis_body_handle_t handle, const entasis_collidable_description_t * value, entasis_diagnostic_t * diagnostic);

/**
 * applies collidable descriptions to a prefix of body handles in input order
 *
 * @param world target world
 * @param handles input body handles
 * @param values input collidable description array
 * @param count number of entries in the input arrays
 * @param out_completed receives the number of successfully completed prefix entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_set_collidable_batch(entasis_world_t * world, const entasis_body_handle_t * handles, const entasis_collidable_description_t * values, uint64_t count, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * updates local inertia and handles dynamic/kinematic changes
 *
 * @param world target world
 * @param handle target body handle
 * @param value body inertia
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_set_inertia(entasis_world_t * world, entasis_body_handle_t handle, const entasis_body_inertia_t * value, entasis_diagnostic_t * diagnostic);

/**
 * applies inertia values to a prefix of body handles in input order
 *
 * @param world target world
 * @param handles input body handles
 * @param values input body inertia array
 * @param count number of entries in the input arrays
 * @param out_completed receives the number of successfully completed prefix entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_set_inertia_batch(entasis_world_t * world, const entasis_body_handle_t * handles, const entasis_body_inertia_t * values, uint64_t count, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * updates the pose through the complete body mutation path
 *
 * @param world target world
 * @param handle target body handle
 * @param value rigid pose
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_set_pose(entasis_world_t * world, entasis_body_handle_t handle, const entasis_rigid_pose_t * value, entasis_diagnostic_t * diagnostic);

/**
 * applies poses to a prefix of body handles in input order
 *
 * @param world target world
 * @param handles input body handles
 * @param values input rigid pose array
 * @param count number of entries in the input arrays
 * @param out_completed receives the number of successfully completed prefix entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_set_pose_batch(entasis_world_t * world, const entasis_body_handle_t * handles, const entasis_rigid_pose_t * values, uint64_t count, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * updates only the shape while retaining the other collidable settings
 *
 * it maintains shape reference counts and broad-phase membership
 *
 * @param world target world
 * @param handle target body handle
 * @param shape registered shape handle
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_set_shape(entasis_world_t * world, entasis_body_handle_t handle, entasis_shape_handle_t shape, entasis_diagnostic_t * diagnostic);

/**
 * applies shape handles to a prefix of body handles in input order
 *
 * @param world target world
 * @param handles input body handles
 * @param values input shape handle array
 * @param count number of entries in the input arrays
 * @param out_completed receives the number of successfully completed prefix entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_set_shape_batch(entasis_world_t * world, const entasis_body_handle_t * handles, const entasis_shape_handle_t * values, uint64_t count, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * updates velocity and awakens a sleeping body
 *
 * @param world target world
 * @param handle target body handle
 * @param value body velocity
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_set_velocity(entasis_world_t * world, entasis_body_handle_t handle, const entasis_body_velocity_t * value, entasis_diagnostic_t * diagnostic);

/**
 * applies velocities to a prefix of body handles in input order
 *
 * @param world target world
 * @param handles input body handles
 * @param values input body velocity array
 * @param count number of entries in the input arrays
 * @param out_completed receives the number of successfully completed prefix entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_set_velocity_batch(entasis_world_t * world, const entasis_body_handle_t * handles, const entasis_body_velocity_t * values, uint64_t count, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * constructs a dynamic body with no broad-phase collidable
 *
 * @param inertia body-local inverse inertia and inverse mass
 * @param pose rigid pose
 * @param velocity linear and angular velocity
 * @param activity sleep settings
 *
 * @return returns the constructed body description
 */
ENTASIS_API entasis_body_description_t ENTASIS_CALL entasis_body_shapeless(entasis_body_inertia_t inertia, entasis_rigid_pose_t pose, entasis_body_velocity_t velocity, entasis_activity_description_t activity);

/**
 * constructs a body collidable description
 *
 * the default matches the low-level implicit entasis_shape_handle_t conversion: passive continuity, no minimum margin, and an unbounded maximum speculative margin
 *
 * @param shape registered shape handle
 * @param continuity continuous collision detection settings
 * @param minimum_speculative_margin minimum speculative contact margin
 * @param maximum_speculative_margin maximum speculative contact margin
 *
 * @return returns the collidable description
 */
ENTASIS_API entasis_collidable_description_t ENTASIS_CALL entasis_collidable(entasis_shape_handle_t shape, entasis_continuous_detection_t continuity, float minimum_speculative_margin, float maximum_speculative_margin);

/**
 * constructs a rigid pose
 *
 * orientation is supplied explicitly. use {0, 0, 0, 1} for identity
 *
 * @param position world or local position
 * @param orientation world or local rotation quaternion
 *
 * @return returns the rigid pose
 */
ENTASIS_API entasis_rigid_pose_t ENTASIS_CALL entasis_pose(entasis_vector3_t position, entasis_quaternion_t orientation);

/**
 * adds one static and applies the selected awakening policy
 *
 * allocation may occur when world capacity grows. ownership: owner thread only while the world is idle
 *
 * @param world target world
 * @param description static description to copy
 * @param awakening static mutation awakening policy
 * @param out_handle receives the created static handle
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_add(entasis_world_t * world, const entasis_static_description_t * description, entasis_awakening_policy_t awakening, entasis_static_handle_t * out_handle, entasis_diagnostic_t * diagnostic);

/**
 * adds a prefix of descriptions in input order after one capacity check
 *
 * the awakening policy is applied to every item. allocation: the initial capacity check may grow world storage. ownership: owner thread only while the world is idle
 *
 * @param world target world
 * @param descriptions input static description array
 * @param count number of entries in the input arrays
 * @param awakening static mutation awakening policy
 * @param out_handles receives static handles in input order
 * @param out_completed receives the number of successfully completed prefix entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_add_batch(entasis_world_t * world, const entasis_static_description_t * descriptions, uint64_t count, entasis_awakening_policy_t awakening, entasis_static_handle_t * out_handles, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * replaces the complete static description and applies the selected awakening policy to overlapping sleeping bodies
 *
 * ownership: owner thread only while the world is idle
 *
 * @param world target world
 * @param handle target static handle
 * @param description static description to copy
 * @param awakening static mutation awakening policy
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_apply(entasis_world_t * world, entasis_static_handle_t handle, const entasis_static_description_t * description, entasis_awakening_policy_t awakening, entasis_diagnostic_t * diagnostic);

/**
 * applies matching handles and descriptions in input order
 *
 * a failure stops the batch. out_completed reports the number of applied entries and identifies the first failing index. earlier changes remain applied. ownership: owner thread only while the world is idle
 *
 * @param world target world
 * @param handles input static handles
 * @param descriptions input static description array
 * @param count number of entries in the input arrays
 * @param awakening static mutation awakening policy
 * @param out_completed receives the number of successfully completed prefix entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_apply_batch(entasis_world_t * world, const entasis_static_handle_t * handles, const entasis_static_description_t * descriptions, uint64_t count, entasis_awakening_policy_t awakening, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * constructs a static description using the supplied continuity settings
 *
 * @param shape registered shape handle
 * @param pose rigid pose
 * @param continuity continuous collision detection settings
 *
 * @return returns the constructed static description
 */
ENTASIS_API entasis_static_description_t ENTASIS_CALL entasis_static_body(entasis_shape_handle_t shape, entasis_rigid_pose_t pose, entasis_continuous_detection_t continuity);

/**
 * copies the description of one static
 *
 * allocation: none. the returned value contains no simulation pointers
 *
 * @param world target world
 * @param handle target static handle
 * @param out_state receives the copied static state
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_get(entasis_world_t * world, entasis_static_handle_t handle, entasis_static_state_t * out_state, entasis_diagnostic_t * diagnostic);

/**
 * copies static snapshots for a prefix of handles into caller-owned output storage
 *
 * @param world target world
 * @param handles input static handles
 * @param count number of entries in the input arrays
 * @param out_states receives copied static states in input order
 * @param out_completed receives the number of successfully completed prefix entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_get_batch(entasis_world_t * world, const entasis_static_handle_t * handles, uint64_t count, entasis_static_state_t * out_states, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * removes one static and applies the selected awakening policy
 *
 * ownership: owner thread only while the world is idle
 *
 * @param world target world
 * @param handle target static handle
 * @param awakening static mutation awakening policy
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_remove(entasis_world_t * world, entasis_static_handle_t handle, entasis_awakening_policy_t awakening, entasis_diagnostic_t * diagnostic);

/**
 * removes handles in input order using one awakening policy
 *
 * a failure stops the batch. out_completed reports how many statics were removed and identifies the first failing index. earlier removals remain applied. ownership: owner thread only while the world is idle
 *
 * @param world target world
 * @param handles input static handles
 * @param count number of entries in the input arrays
 * @param awakening static mutation awakening policy
 * @param out_completed receives the number of successfully completed prefix entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_remove_batch(entasis_world_t * world, const entasis_static_handle_t * handles, uint64_t count, entasis_awakening_policy_t awakening, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * updates only continuous-detection settings
 *
 * @param world target world
 * @param handle target static handle
 * @param value continuous detection
 * @param awakening static mutation awakening policy
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_set_continuity(entasis_world_t * world, entasis_static_handle_t handle, const entasis_continuous_detection_t * value, entasis_awakening_policy_t awakening, entasis_diagnostic_t * diagnostic);

/**
 * updates only the pose
 *
 * @param world target world
 * @param handle target static handle
 * @param value rigid pose
 * @param awakening static mutation awakening policy
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_set_pose(entasis_world_t * world, entasis_static_handle_t handle, const entasis_rigid_pose_t * value, entasis_awakening_policy_t awakening, entasis_diagnostic_t * diagnostic);

/**
 * applies poses to a prefix of static handles in input order
 *
 * @param world target world
 * @param handles input static handles
 * @param values input rigid pose array
 * @param count number of entries in the input arrays
 * @param awakening static mutation awakening policy
 * @param out_completed receives the number of successfully completed prefix entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_set_pose_batch(entasis_world_t * world, const entasis_static_handle_t * handles, const entasis_rigid_pose_t * values, uint64_t count, entasis_awakening_policy_t awakening, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * updates only the shape
 *
 * @param world target world
 * @param handle target static handle
 * @param shape registered shape handle
 * @param awakening static mutation awakening policy
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_set_shape(entasis_world_t * world, entasis_static_handle_t handle, entasis_shape_handle_t shape, entasis_awakening_policy_t awakening, entasis_diagnostic_t * diagnostic);

/**
 * constructs a clockwise one-sided triangle
 *
 * @param a triangle vertex A
 * @param b triangle vertex B
 * @param c triangle vertex C
 *
 * @return returns the triangle
 */
ENTASIS_API entasis_triangle_t ENTASIS_CALL entasis_triangle(entasis_vector3_t a, entasis_vector3_t b, entasis_vector3_t c);

/**
 * constructs body linear and angular velocity
 *
 * @param linear linear velocity
 * @param angular angular velocity
 *
 * @return returns the body velocity
 */
ENTASIS_API entasis_body_velocity_t ENTASIS_CALL entasis_velocity(entasis_vector3_t linear, entasis_vector3_t angular);

/**
 * adds a static with caller-filtered sleeping-island awakening
 *
 * callback state is borrowed only until this operation returns. the callback receives the same stable sleeping body handle as Odin and cannot reenter world mutation
 *
 * @param world caller-owned initialized world handle
 * @param description new static description
 * @param filter optional owner-thread filter. NULL uses ordinary overlap awakening
 * @param user_context caller-owned callback state, borrowed until this operation returns
 * @param out_handle receives the new static handle
 * @param diagnostic optional output diagnostic
 *
 * @return returns the operation status. completed work is not rolled back on callback failure
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_add_filtered(entasis_world_t * world, const entasis_static_description_t * description, entasis_static_awakening_filter_fn filter, void * user_context, entasis_static_handle_t * out_handle, entasis_diagnostic_t * diagnostic);

/**
 * removes a static with caller-filtered sleeping-island awakening
 *
 * @param world caller-owned initialized world handle
 * @param handle existing static handle
 * @param filter optional owner-thread filter. NULL uses ordinary overlap awakening
 * @param user_context caller-owned callback state, borrowed until this operation returns
 * @param diagnostic optional output diagnostic
 *
 * @return returns the operation status. completed work is not rolled back on callback failure
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_remove_filtered(entasis_world_t * world, entasis_static_handle_t handle, entasis_static_awakening_filter_fn filter, void * user_context, entasis_diagnostic_t * diagnostic);

/**
 * replaces a static and filters awakening over the union of old and new bounds
 *
 * @param world caller-owned initialized world handle
 * @param handle existing static handle
 * @param description new static description
 * @param filter optional owner-thread filter. NULL uses ordinary overlap awakening
 * @param user_context caller-owned callback state, borrowed until this operation returns
 * @param diagnostic optional output diagnostic
 *
 * @return returns the operation status. completed work is not rolled back on callback failure
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_apply_filtered(entasis_world_t * world, entasis_static_handle_t handle, const entasis_static_description_t * description, entasis_static_awakening_filter_fn filter, void * user_context, entasis_diagnostic_t * diagnostic);

/**
 * constructs the versioned body-control defaults
 *
 * @return returns the initialized descriptor
 */
ENTASIS_API entasis_body_control_configuration_t ENTASIS_CALL entasis_body_control_configuration_default(void);

/**
 * enables sparse optional force, damping and kinematic-target storage
 *
 * empty controls retain the original velocity callback
 *
 * @param world idle live world. mutations reject read phases and callback reentry
 * @param configuration copied configuration. NULL selects defaults
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK or the original failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_enable_body_control(entasis_world_t * world, const entasis_body_control_configuration_t * configuration, entasis_diagnostic_t * diagnostic);

/**
 * disables body controls and releases their storage
 *
 * restores the original callback, cancels queued controls and clears expired derived target velocities without altering application joints
 *
 * @param world idle live world. mutations reject read phases and callback reentry
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK or the original failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_disable_body_control(entasis_world_t * world, entasis_diagnostic_t * diagnostic);

/**
 * reserves control tables and active-index bindings without shrinking
 *
 * existing state survives allocation failure. warmed reserved operations do not allocate
 *
 * @param world idle live world. mutations reject read phases and callback reentry
 * @param input_capacity positive input/target capacity hint
 * @param settings_capacity positive persistent-setting capacity hint
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK or the original failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_control_reserve(entasis_world_t * world, int32_t input_capacity, int32_t settings_capacity, entasis_diagnostic_t * diagnostic);

/**
 * accumulates world-space force or linear acceleration
 *
 * dynamic bodies only. repeated submissions add for one integrated step over actual substep durations. zero does not awaken. executed input is consumed even if later physics fails. prediction never consumes it
 *
 * @param world idle live world. mutations reject read phases and callback reentry
 * @param body live body handle
 * @param force finite world-space vector
 * @param mode force or acceleration units
 * @param wake explicit wake policy. choose ENTASIS_BODY_CONTROL_WAKE for the native default
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK or the original failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_add_force(entasis_world_t * world, entasis_body_handle_t body, entasis_vector3_t force, entasis_body_input_mode_t mode, entasis_body_control_wake_t wake, entasis_diagnostic_t * diagnostic);

/**
 * accumulates world-space torque or angular acceleration
 *
 * dynamic bodies only. repeated submissions add for one integrated step over actual substep durations. zero does not awaken. executed input is consumed even if later physics fails. prediction never consumes it
 *
 * @param world idle live world. mutations reject read phases and callback reentry
 * @param body live body handle
 * @param torque finite world-space vector
 * @param mode force or acceleration units
 * @param wake explicit wake policy. choose ENTASIS_BODY_CONTROL_WAKE for the native default
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK or the original failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_add_torque(entasis_world_t * world, entasis_body_handle_t body, entasis_vector3_t torque, entasis_body_input_mode_t mode, entasis_body_control_wake_t wake, entasis_diagnostic_t * diagnostic);

/**
 * accumulates a fixed world-space force and moment about the current center of mass
 *
 * the wrench is frozen at submission. position is not a local-space attachment and is not updated as the body rotates
 *
 * @param world idle live world. mutations reject read phases and callback reentry
 * @param body live body handle
 * @param force finite world-space force
 * @param position finite world-space application point at submission
 * @param wake explicit wake policy. choose ENTASIS_BODY_CONTROL_WAKE for the native default
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK or the original failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_add_force_at_position(entasis_world_t * world, entasis_body_handle_t body, entasis_vector3_t force, entasis_vector3_t position, entasis_body_control_wake_t wake, entasis_diagnostic_t * diagnostic);

/**
 * cancels pending force and torque without changing velocity
 *
 * @param world idle live world. mutations reject read phases and callback reentry
 * @param body live body handle
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK or the original failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_clear_inputs(entasis_world_t * world, entasis_body_handle_t body, entasis_diagnostic_t * diagnostic);

/**
 * sets per-body exponential damping
 *
 * dynamic bodies only. Additional zero rates remove the override. Override rejects opaque custom velocity callbacks without modifying existing settings
 *
 * @param world idle live world. mutations reject read phases and callback reentry
 * @param body live body handle
 * @param settings required copied settings
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK or the original failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_set_damping(entasis_world_t * world, entasis_body_handle_t body, const entasis_body_damping_t * settings, entasis_diagnostic_t * diagnostic);

/**
 * reads the optional damping settings
 *
 * @param world live world with body control enabled, idle or within an explicit read phase
 * @param body live body handle
 * @param out_settings written only on success. absent settings return zero Additional rates
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK or the original failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_get_damping(entasis_world_t * world, entasis_body_handle_t body, entasis_body_damping_t * out_settings, entasis_diagnostic_t * diagnostic);

/**
 * queues a next-step kinematic target
 *
 * derives linear and shortest-arc angular velocity for the step. ordinary pose integration and collision response apply. no obstacle-resolving teleport. executed targets expire on failure as well as success
 *
 * @param world idle live world. mutations reject read phases and callback reentry
 * @param body live body handle
 * @param target required copied finite pose with unit quaternion
 * @param wake explicit wake policy. choose ENTASIS_BODY_CONTROL_WAKE for the native default
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK or the original failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_set_kinematic_target(entasis_world_t * world, entasis_body_handle_t body, const entasis_rigid_pose_t * target, entasis_body_control_wake_t wake, entasis_diagnostic_t * diagnostic);

/**
 * reads a pending target. expired or absent targets return NOT_FOUND
 *
 * @param world live world with body control enabled, idle or within an explicit read phase
 * @param body live body handle
 * @param out_target pending target, written only on success
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK or the original failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_get_kinematic_target(entasis_world_t * world, entasis_body_handle_t body, entasis_rigid_pose_t * out_target, entasis_diagnostic_t * diagnostic);

/**
 * cancels a pending target and clears an expired target-derived velocity
 *
 * explicit full body edits supersede target control, including a caller-authored velocity equal to the previous derived velocity
 *
 * @param world idle live world. mutations reject read phases and callback reentry
 * @param body live body handle
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK or the original failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_clear_kinematic_target(entasis_world_t * world, entasis_body_handle_t body, entasis_diagnostic_t * diagnostic);

/**
 * creates a descriptor with no axes and spring frequency 30 Hz, damping ratio 1
 *
 * @param reference captured reference pose
 *
 * @return returns copied defaults. select axes before applying
 */
ENTASIS_API entasis_body_axis_lock_t ENTASIS_CALL entasis_body_axis_lock_default(entasis_rigid_pose_t reference);

/**
 * sets or updates a physical axis lock on a dynamic body
 *
 * awakens a sleeping island. failure publishes no new lock. existing references are not reanchored by later pose edits. uses engine-owned constraint type 48, not caller IDs
 *
 * @param world live world with body control enabled
 * @param body live body handle
 * @param description descriptor copied before awakening or allocation
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK or the original failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_set_axis_lock(entasis_world_t * world, entasis_body_handle_t body, const entasis_body_axis_lock_t * description, entasis_diagnostic_t * diagnostic);

/**
 * copies active or sleeping lock settings without awakening
 *
 * returns NOT_FOUND when no lock exists. no borrowed pointer or allocation. the existing body constraint list is authoritative
 *
 * @param world live world with body control enabled
 * @param body live body handle
 * @param output written only on success, with current size/version
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK or the original failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_get_axis_lock(entasis_world_t * world, entasis_body_handle_t body, entasis_body_axis_lock_t * output, entasis_diagnostic_t * diagnostic);

/**
 * removes only the owned axis lock, leaving explicit joints intact
 *
 * a live body without a lock succeeds. removing a sleeping lock can awaken the island and fail on capacity. retry does not lose the remaining lock
 *
 * @param world live world with body control enabled
 * @param body live body handle
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK or the original failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_clear_axis_lock(entasis_world_t * world, entasis_body_handle_t body, entasis_diagnostic_t * diagnostic);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* ENTASIS_BODIES_H */
