// generated by tools/abi/generate_abi. do not edit
#ifndef ENTASIS_COLLISION_H
#define ENTASIS_COLLISION_H

#include <entasis/base.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * accepts or rejects one complete collidable pair
 *
 * @param user_context caller-owned context passed unchanged by Entasis
 * @param a collidable reference A
 * @param b collidable reference B
 *
 * @return returns ENTASIS_TRUE to keep the pair or ENTASIS_FALSE to reject it
 */
typedef entasis_bool_t (ENTASIS_CALL *entasis_collision_pair_filter_proc_t)(void * user_context, entasis_collidable_reference_t a, entasis_collidable_reference_t b);
/**
 * accepts or rejects one compound child pair
 *
 * @param user_context caller-owned context passed unchanged by Entasis
 * @param a collidable reference A
 * @param b collidable reference B
 * @param child_a compound child index for collidable A
 * @param child_b compound child index for collidable B
 *
 * @return returns ENTASIS_TRUE to keep the child pair or ENTASIS_FALSE to reject it
 */
typedef entasis_bool_t (ENTASIS_CALL *entasis_collision_child_filter_proc_t)(void * user_context, entasis_collidable_reference_t a, entasis_collidable_reference_t b, int32_t child_a, int32_t child_b);
/**
 * combines two collidable materials into one contact material
 *
 * @param user_context caller-owned context passed unchanged by Entasis
 * @param a_id material ID for collidable A
 * @param a borrowed material for collidable A
 * @param b_id material ID for collidable B
 * @param b borrowed material for collidable B
 * @param out_material receives the combined contact material
 *
 * @return returns ENTASIS_TRUE to use out_material or ENTASIS_FALSE to use the default combination
 */
typedef entasis_bool_t (ENTASIS_CALL *entasis_material_combine_proc_t)(void * user_context, entasis_material_id_t a_id, const entasis_material_t * a, entasis_material_id_t b_id, const entasis_material_t * b, entasis_material_t * out_material);
/**
 * combines settings on the owner thread before workers execute
 *
 * the callback may edit only out_settings. it must not mutate its world, retain borrowed pointers or unwind across the ABI. invalid output rejects solve preparation
 *
 * @param user_context copied configuration context
 * @param a first collidable
 * @param b second collidable
 * @param settings_a effective first settings, callback-local
 * @param settings_b effective second settings, callback-local
 * @param out_settings initialized to componentwise maximum. written values are validated
 *
 * @return writes the effective pair settings
 */
typedef void (ENTASIS_CALL *entasis_restitution_combine_fn)(void * user_context, entasis_collidable_reference_t a, entasis_collidable_reference_t b, const entasis_restitution_settings_t * settings_a, const entasis_restitution_settings_t * settings_b, entasis_restitution_settings_t * out_settings);

/**
 * spring angular frequency and damping ratio in solver form
 */
struct entasis_spring_settings_t {
    /* angular spring frequency */
    float angular_frequency;
    /* twice the damping ratio used by the solver */
    float twice_damping_ratio;
};

/**
 * caller-owned immutable material array
 */
struct entasis_material_table_t {
    /* borrowed material array */
    const entasis_material_t * values;
    /* number of entries in values */
    uint64_t count;
};

/**
 * collision layer and accepted layer mask
 */
struct entasis_collision_filter_t {
    /* accepted collision layer mask */
    entasis_layer_mask_t mask;
    /* collision layer */
    entasis_collision_layer_t layer;
    /* reserved for ABI compatibility */
    uint8_t reserved[7];
};

/**
 * collision filter and material ID stored for one collidable
 */
struct entasis_collision_properties_t {
    /* accepted collision layer mask */
    entasis_layer_mask_t mask;
    /* material table index */
    entasis_material_id_t material_id;
    /* collision layer */
    entasis_collision_layer_t layer;
    /* reserved for ABI compatibility */
    uint8_t reserved[5];
};

/**
 * symmetric global layer-pair policy
 */
struct entasis_layer_matrix_t {
    /* fixed storage for rows */
    entasis_layer_mask_t rows[64];
};

/**
 * generation-aware body and static collision property table
 */
struct entasis_collision_property_table_t {
    /* internal collision property state managed by Entasis */
    void * opaque;
};

/**
 * optional per-collidable solid-contact bounce settings
 */
struct entasis_restitution_settings_t {
    /* restitution coefficient in [0,1] */
    float coefficient;
    /* finite nonnegative approach speed threshold in world units/second */
    float threshold;
};

/**
 * contact friction, recovery velocity, and spring settings
 */
struct entasis_contact_material_t {
    /* nonnegative friction coefficient used by the contact solver */
    float friction_coefficient;
    /* spring frequency and damping settings */
    entasis_spring_settings_t spring_settings;
    /* maximum penetration recovery velocity */
    float maximum_recovery_velocity;
};

/**
 * per-collidable material used by the layer and material policy
 */
struct entasis_material_t {
    /* friction coefficient */
    float friction;
    /* maximum penetration recovery velocity */
    float maximum_recovery_velocity;
    /* spring frequency and damping settings */
    entasis_spring_settings_t spring;
};

/**
 * one nonconvex contact point with pair-local data
 */
struct entasis_contact_point_t {
    /* pair-local contact offset */
    entasis_vector3_t offset;
    /* contact penetration depth */
    float depth;
    /* contact or hit normal */
    entasis_vector3_t normal;
    /* pair-local contact feature ID */
    int32_t feature_id;
};

/**
 * one convex contact point using the manifold normal
 */
struct entasis_convex_contact_t {
    /* pair-local contact offset */
    entasis_vector3_t offset;
    /* contact penetration depth */
    float depth;
    /* pair-local contact feature ID */
    int32_t feature_id;
};

/**
 * copied optional restitution configuration. existing contact materials remain unchanged
 */
struct entasis_restitution_configuration_t {
    /* size of this structure */
    uint32_t struct_size;
    /* must be ENTASIS_STRUCT_VERSION */
    uint32_t struct_version;
    /* used when an instance has no override */
    entasis_restitution_settings_t fallback;
    /* explicit instance override capacity hint */
    int32_t collidable_capacity;
    /* retained impact history capacity hint */
    int32_t pair_capacity;
    /* optional pair combine callback, invoked before solver dispatch */
    entasis_restitution_combine_fn combine;
    /* borrowed until restitution is disabled or the world is destroyed */
    void * user_context;
};

/**
 * constant contact material used by the default narrow-phase policy
 */
struct entasis_default_narrow_policy_t {
    /* contact material assigned to every accepted manifold */
    entasis_contact_material_t material;
};

/**
 * caller-owned layer, material, and callback narrow-phase policy
 */
struct entasis_layer_material_policy_t {
    /* size of this struct in bytes */
    uint32_t struct_size;
    /* version of this struct layout */
    uint32_t struct_version;
    /* borrowed pointer to one caller-owned collision property table, which must outlive its use by the policy */
    entasis_collision_property_table_t * properties;
    /* borrowed layer matrix */
    const entasis_layer_matrix_t * layer_matrix;
    /* borrowed immutable material table */
    entasis_material_table_t materials;
    /* collision properties used when no table entry exists */
    entasis_collision_properties_t default_properties;
    /* contact material used when no material table entry exists */
    entasis_material_t fallback_material;
    /* pair filter callback */
    entasis_collision_pair_filter_proc_t pair_filter;
    /* child filter callback */
    entasis_collision_child_filter_proc_t child_filter;
    /* material combine callback */
    entasis_material_combine_proc_t material_combine;
    /* caller-owned context passed unchanged to associated callbacks */
    void * user_context;
};

/**
 * nonconvex contact manifold containing up to four contact points
 */
struct entasis_nonconvex_contact_manifold_t {
    /* body B offset relative to body A */
    entasis_vector3_t offset_b;
    /* number of valid entries */
    int32_t count;
    /* fixed storage for contacts */
    entasis_contact_point_t contacts[4];
};

/**
 * convex contact manifold containing up to four contacts
 */
struct entasis_convex_contact_manifold_t {
    /* body B offset relative to body A */
    entasis_vector3_t offset_b;
    /* number of valid entries */
    int32_t count;
    /* contact or hit normal */
    entasis_vector3_t normal;
    /* fixed storage for contacts */
    entasis_convex_contact_t contacts[4];
};

/**
 * versioned built-in narrow-phase policy selected by kind
 */
struct entasis_narrow_policy_t {
    /* size of this struct in bytes */
    uint32_t struct_size;
    /* version of this struct layout */
    uint32_t struct_version;
    /* active tagged variant */
    entasis_narrow_policy_kind_t kind;
    /* reserved for ABI compatibility */
    uint8_t reserved0[7];
    /* stored configuration for the default narrow-phase policy kind */
    entasis_default_narrow_policy_t default_policy;
    /* borrowed layer material policy */
    const entasis_layer_material_policy_t * layer_material_policy;
    /* reserved for ABI compatibility */
    uint64_t reserved1;
};

/**
 * pointer-free tagged convex or nonconvex contact manifold
 */
struct entasis_contact_manifold_t {
    /* active tagged variant */
    entasis_manifold_kind_t kind;
    /* reserved for ABI compatibility */
    uint8_t reserved[3];
    /* convex manifold payload */
    entasis_convex_contact_manifold_t convex;
    /* nonconvex manifold payload */
    entasis_nonconvex_contact_manifold_t nonconvex;
};

/**
 * builds spring settings from frequency and damping ratio
 *
 * allocation: none
 *
 * @param frequency spring frequency in hertz
 * @param damping_ratio dimensionless spring damping ratio
 *
 * @return returns the spring settings
 */
ENTASIS_API entasis_spring_settings_t ENTASIS_CALL entasis_spring_settings(float frequency, float damping_ratio);

/**
 * builds a constant contact material
 *
 * the policy is validated when its callbacks are activated by world_init. allocation: none
 *
 * @param friction_coefficient nonnegative friction coefficient
 * @param maximum_recovery_velocity maximum penetration recovery velocity
 * @param spring spring frequency and damping settings
 *
 * @return returns the contact material
 */
ENTASIS_API entasis_contact_material_t ENTASIS_CALL entasis_contact_material(float friction_coefficient, float maximum_recovery_velocity, entasis_spring_settings_t spring);

/**
 * returns the default contact material
 *
 * allocation: none
 *
 * @return returns the default contact material
 */
ENTASIS_API entasis_contact_material_t ENTASIS_CALL entasis_contact_material_default(void);

/**
 * returns the default constant-material narrow policy
 *
 * allocation: none
 *
 * @return returns the default narrow policy
 */
ENTASIS_API entasis_default_narrow_policy_t ENTASIS_CALL entasis_default_narrow_policy(void);

/**
 * builds a constant-material narrow policy
 *
 * it reuses the low-level allow, child, and dispose callbacks and adds no allocation, closure, or extra dispatch
 *
 * @param material contact material to copy
 *
 * @return returns the default narrow policy
 */
ENTASIS_API entasis_default_narrow_policy_t ENTASIS_CALL entasis_narrow_policy_default(entasis_contact_material_t material);

/**
 * constructs one layer and mask pair
 *
 * @param layer collision layer
 * @param mask collision layer mask
 *
 * @return returns the collision filter
 */
ENTASIS_API entasis_collision_filter_t ENTASIS_CALL entasis_collision_filter(entasis_collision_layer_t layer, entasis_layer_mask_t mask);

/**
 * applies both per-collidable masks and the optional global layer matrix
 *
 * @param a collision filter A
 * @param b collision filter B
 * @param layer_matrix caller-owned symmetric layer matrix used by the policy
 *
 * @return returns ENTASIS_TRUE when both filters and the optional matrix allow the pair
 */
ENTASIS_API entasis_bool_t ENTASIS_CALL entasis_collision_filter_allows(entasis_collision_filter_t a, entasis_collision_filter_t b, const entasis_layer_matrix_t * layer_matrix);

/**
 * returns layer zero accepting every layer
 *
 * @return returns the default collision filter
 */
ENTASIS_API entasis_collision_filter_t ENTASIS_CALL entasis_collision_filter_default(void);

/**
 * validates and constructs one compact layer index
 *
 * @param index zero-based table index
 * @param out_layer receives the collision layer
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collision_layer(uint32_t index, entasis_collision_layer_t * out_layer);

/**
 * returns the integer layer index
 *
 * @param layer collision layer
 *
 * @return returns the unsigned 32-bit integer
 */
ENTASIS_API uint32_t ENTASIS_CALL entasis_collision_layer_index(entasis_collision_layer_t layer);

/**
 * validates the compact layer value
 *
 * @param layer collision layer
 *
 * @return returns ENTASIS_TRUE when layer is in the public range
 */
ENTASIS_API entasis_bool_t ENTASIS_CALL entasis_collision_layer_is_valid(entasis_collision_layer_t layer);

/**
 * constructs one dense per-collidable policy record
 *
 * @param filter collision layer and accepted layer mask assigned to the collidable
 * @param material_id material table index assigned to the collidable
 *
 * @return returns the collision properties
 */
ENTASIS_API entasis_collision_properties_t ENTASIS_CALL entasis_collision_properties(entasis_collision_filter_t filter, entasis_material_id_t material_id);

/**
 * uses the default filter and fallback material
 *
 * @return returns the default collision properties
 */
ENTASIS_API entasis_collision_properties_t ENTASIS_CALL entasis_collision_properties_default(void);

/**
 * reconstructs the transient layer/mask view from the compact 16-byte property record
 *
 * @param value collision properties
 *
 * @return returns the collision filter
 */
ENTASIS_API entasis_collision_filter_t ENTASIS_CALL entasis_collision_properties_filter(entasis_collision_properties_t value);

/**
 * checks the stable record representation
 *
 * material table bounds are policy-specific and are checked by the narrow-phase adapter
 *
 * @param value collision properties
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collision_properties_validate(entasis_collision_properties_t value);

/**
 * invalidates every property while retaining capacity
 *
 * @param table target collision property table
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collision_property_clear(entasis_collision_property_table_t * table);

/**
 * releases caller-owned property storage
 *
 * @param table target collision property table
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collision_property_destroy(entasis_collision_property_table_t * table);

/**
 * grows both namespaces independently
 *
 * @param table target collision property table
 * @param body_capacity required body namespace capacity
 * @param static_capacity required static namespace capacity
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collision_property_ensure_capacity(entasis_collision_property_table_t * table, uint64_t body_capacity, uint64_t static_capacity);

/**
 * returns one body or static policy record
 *
 * @param table target collision property table
 * @param collidable target collidable reference
 * @param out_value receives the collision properties
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collision_property_get(entasis_collision_property_table_t * table, entasis_collidable_reference_t collidable, entasis_collision_properties_t * out_value);

/**
 * returns one body policy record
 *
 * @param table target collision property table
 * @param handle target body handle
 * @param out_value receives the collision properties
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collision_property_get_body(entasis_collision_property_table_t * table, entasis_body_handle_t handle, entasis_collision_properties_t * out_value);

/**
 * returns one static policy record
 *
 * @param table target collision property table
 * @param handle target static handle
 * @param out_value receives the collision properties
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collision_property_get_static(entasis_collision_property_table_t * table, entasis_static_handle_t handle, entasis_collision_properties_t * out_value);

/**
 * initializes the generation-aware body and static property spaces
 *
 * capacity hints may be zero and grow geometrically
 *
 * @param table target collision property table
 * @param body_capacity required body namespace capacity
 * @param static_capacity required static namespace capacity
 * @param allocator copied allocator callbacks for storage covered by the selected allocation scope. user_context remains borrowed until destruction
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collision_property_init(entasis_collision_property_table_t * table, uint64_t body_capacity, uint64_t static_capacity, const entasis_allocator_t * allocator, entasis_diagnostic_t * diagnostic);

/**
 * invalidates one body or static policy record
 *
 * @param table target collision property table
 * @param collidable target collidable reference
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collision_property_remove(entasis_collision_property_table_t * table, entasis_collidable_reference_t collidable);

/**
 * invalidates records in exact input order
 *
 * @param table target collision property table
 * @param collidables input collidable references
 * @param count number of entries in the input arrays
 * @param out_completed receives the number of successfully completed prefix entries
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collision_property_remove_batch(entasis_collision_property_table_t * table, const entasis_collidable_reference_t * collidables, uint64_t count, uint64_t * out_completed);

/**
 * invalidates one body policy lifetime
 *
 * @param table target collision property table
 * @param handle target body handle
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collision_property_remove_body(entasis_collision_property_table_t * table, entasis_body_handle_t handle);

/**
 * invalidates one static policy lifetime
 *
 * @param table target collision property table
 * @param handle target static handle
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collision_property_remove_static(entasis_collision_property_table_t * table, entasis_static_handle_t handle);

/**
 * creates or updates a body or static policy record
 *
 * @param table target collision property table
 * @param collidable target collidable reference
 * @param value collision properties
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collision_property_set(entasis_collision_property_table_t * table, entasis_collidable_reference_t collidable, entasis_collision_properties_t value);

/**
 * applies records in exact input order
 *
 * @param table target collision property table
 * @param collidables input collidable references
 * @param values input collision property array
 * @param count number of entries in the input arrays
 * @param out_completed receives the number of successfully completed prefix entries
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collision_property_set_batch(entasis_collision_property_table_t * table, const entasis_collidable_reference_t * collidables, const entasis_collision_properties_t * values, uint64_t count, uint64_t * out_completed);

/**
 * creates or updates one body policy record
 *
 * @param table target collision property table
 * @param handle target body handle
 * @param value collision properties
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collision_property_set_body(entasis_collision_property_table_t * table, entasis_body_handle_t handle, entasis_collision_properties_t value);

/**
 * creates or updates one static policy record
 *
 * @param table target collision property table
 * @param handle target static handle
 * @param value collision properties
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collision_property_set_static(entasis_collision_property_table_t * table, entasis_static_handle_t handle, entasis_collision_properties_t value);

/**
 * creates a mask containing one layer
 *
 * @param layer collision layer
 *
 * @return returns the collision layer mask
 */
ENTASIS_API entasis_layer_mask_t ENTASIS_CALL entasis_layer_mask(entasis_collision_layer_t layer);

/**
 * returns a copy with one layer enabled
 *
 * @param mask collision layer mask
 * @param layer collision layer
 *
 * @return returns the collision layer mask
 */
ENTASIS_API entasis_layer_mask_t ENTASIS_CALL entasis_layer_mask_add(entasis_layer_mask_t mask, entasis_collision_layer_t layer);

/**
 * returns a mask containing every public collision layer
 *
 * @return returns the collision layer mask
 */
ENTASIS_API entasis_layer_mask_t ENTASIS_CALL entasis_layer_mask_all(void);

/**
 * checks one layer bit
 *
 * @param mask collision layer mask
 * @param layer collision layer
 *
 * @return returns ENTASIS_TRUE when mask contains layer
 */
ENTASIS_API entasis_bool_t ENTASIS_CALL entasis_layer_mask_contains(entasis_layer_mask_t mask, entasis_collision_layer_t layer);

/**
 * returns an empty layer mask
 *
 * @return returns the collision layer mask
 */
ENTASIS_API entasis_layer_mask_t ENTASIS_CALL entasis_layer_mask_none(void);

/**
 * returns a copy with one layer disabled
 *
 * @param mask collision layer mask
 * @param layer collision layer
 *
 * @return returns the collision layer mask
 */
ENTASIS_API entasis_layer_mask_t ENTASIS_CALL entasis_layer_mask_remove(entasis_layer_mask_t mask, entasis_collision_layer_t layer);

/**
 * constructs a complete allocation-free narrow-phase policy
 *
 * nil property or matrix pointers select the documented defaults
 *
 * @param properties collision property table used by the policy
 * @param layer_matrix caller-owned symmetric layer matrix used by the policy
 * @param materials caller-owned material table used by the policy
 *
 * @return returns the layer material policy
 */
ENTASIS_API entasis_layer_material_policy_t ENTASIS_CALL entasis_layer_material_policy(entasis_collision_property_table_t * properties, const entasis_layer_matrix_t * layer_matrix, entasis_material_table_t materials);

/**
 * accepts every layer pair
 *
 * @return returns the layer matrix
 */
ENTASIS_API entasis_layer_matrix_t ENTASIS_CALL entasis_layer_matrix_all(void);

/**
 * enables one symmetric layer pair
 *
 * @param matrix target layer matrix
 * @param a collision layer A
 * @param b collision layer B
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_layer_matrix_allow(entasis_layer_matrix_t * matrix, entasis_collision_layer_t a, entasis_collision_layer_t b);

/**
 * checks both matrix directions
 *
 * requiring both directions makes direct row edits fail closed when symmetry is accidentally broken
 *
 * @param matrix target layer matrix
 * @param a collision layer A
 * @param b collision layer B
 *
 * @return returns ENTASIS_TRUE when both matrix directions allow the layer pair
 */
ENTASIS_API entasis_bool_t ENTASIS_CALL entasis_layer_matrix_allows(const entasis_layer_matrix_t * matrix, entasis_collision_layer_t a, entasis_collision_layer_t b);

/**
 * disables one symmetric layer pair
 *
 * @param matrix target layer matrix
 * @param a collision layer A
 * @param b collision layer B
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_layer_matrix_deny(entasis_layer_matrix_t * matrix, entasis_collision_layer_t a, entasis_collision_layer_t b);

/**
 * rejects every layer pair
 *
 * @return returns the layer matrix
 */
ENTASIS_API entasis_layer_matrix_t ENTASIS_CALL entasis_layer_matrix_none(void);

/**
 * updates both directions of one layer pair
 *
 * @param matrix target layer matrix
 * @param a collision layer A
 * @param b collision layer B
 * @param allow whether to allow the layer pair
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_layer_matrix_set(entasis_layer_matrix_t * matrix, entasis_collision_layer_t a, entasis_collision_layer_t b, entasis_bool_t allow);

/**
 * constructs one per-collidable material without allocation
 *
 * @param friction friction coefficient
 * @param maximum_recovery_velocity maximum penetration recovery velocity
 * @param spring spring frequency and damping settings
 *
 * @return returns the material
 */
ENTASIS_API entasis_material_t ENTASIS_CALL entasis_material(float friction, float maximum_recovery_velocity, entasis_spring_settings_t spring);

/**
 * implements a commutative order-independent combination: friction is multiplied, maximum recovery velocity is the larger value, and spring settings come from the material with the larger recovery velocity
 *
 * ties select the stiffer spring and then the more damped spring. the rule is independent of collidable ordering and worker count
 *
 * @param a material A
 * @param b material B
 *
 * @return returns the default material
 */
ENTASIS_API entasis_material_t ENTASIS_CALL entasis_material_combine_default(entasis_material_t a, entasis_material_t b);

/**
 * returns the material used by the default narrow phase when two default collidables interact
 *
 * @return returns the default material
 */
ENTASIS_API entasis_material_t ENTASIS_CALL entasis_material_default(void);

/**
 * converts a nonnegative table index into an entasis_material_id_t
 *
 * the sentinel value is reserved for fallback-material selection
 *
 * @param index zero-based table index
 * @param out_id receives the material ID
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_material_id(uint32_t index, entasis_material_id_t * out_id);

/**
 * returns the fallback-material sentinel
 *
 * @return returns the invalid material ID sentinel
 */
ENTASIS_API entasis_material_id_t ENTASIS_CALL entasis_material_id_invalid(void);

/**
 * checks only the sentinel representation
 *
 * table bounds are validated by entasis_material_table_get
 *
 * @param id material ID
 *
 * @return returns ENTASIS_TRUE when id is not the fallback-material sentinel
 */
ENTASIS_API entasis_bool_t ENTASIS_CALL entasis_material_id_is_valid(entasis_material_id_t id);

/**
 * binds caller-owned material storage
 *
 * allocation: none
 *
 * @param values input material array
 * @param count number of entries in the input arrays
 *
 * @return returns the material table
 */
ENTASIS_API entasis_material_table_t ENTASIS_CALL entasis_material_table(const entasis_material_t * values, uint64_t count);

/**
 * checks the table bounds and copies one material into caller-owned output
 *
 * allocation: none
 *
 * @param table material table to query
 * @param id material ID
 * @param out_value receives the material
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_material_table_get(entasis_material_table_t table, entasis_material_id_t id, entasis_material_t * out_value);

/**
 * converts the facade material to the exact low-level contact material consumed by contact constraints
 *
 * @param value material value to validate or convert
 *
 * @return returns the contact material
 */
ENTASIS_API entasis_contact_material_t ENTASIS_CALL entasis_material_to_contact(entasis_material_t value);

/**
 * applies the same validation used by the contact constraint path
 *
 * @param value material value to validate or convert
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_material_validate(entasis_material_t value);

/**
 * builds the stable layer, mask, pair-filter, child-filter, and material-table adapter around caller-owned context
 *
 * allocation: none after optional property-table growth during world_init
 *
 * @param policy layer material policy to copy
 *
 * @return returns the narrow policy
 */
ENTASIS_API entasis_narrow_policy_t ENTASIS_CALL entasis_narrow_policy_layers_materials(const entasis_layer_material_policy_t * policy);

/**
 * constructs the versioned restitution defaults
 *
 * coefficient zero, threshold one. no response is enabled by this constructor
 *
 * @return returns the default configuration
 */
ENTASIS_API entasis_restitution_configuration_t ENTASIS_CALL entasis_restitution_configuration_default(void);

/**
 * enables optional restitution for accepted solid contacts
 *
 * velocity is captured after integration and before all warmstart impulses. triggers and rejected pairs do not bounce. zero effective coefficients use ordinary solving. callback user data remains borrowed
 *
 * @param world idle world outside callbacks and read phases
 * @param configuration copied configuration. NULL selects defaults
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_enable_restitution(entasis_world_t * world, const entasis_restitution_configuration_t * configuration, entasis_diagnostic_t * diagnostic);

/**
 * disables restitution and releases its settings, history and scratch
 *
 * @param world idle world outside callbacks and read phases
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_disable_restitution(entasis_world_t * world, entasis_diagnostic_t * diagnostic);

/**
 * reserves optional settings/history without shrinking
 *
 * packed target buffers grow as needed before worker dispatch and are reused. capacity failure preserves existing ownership
 *
 * @param world idle world outside callbacks and read phases
 * @param collidable_capacity override capacity hint
 * @param pair_capacity impact history capacity hint
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_restitution_reserve(entasis_world_t * world, int32_t collidable_capacity, int32_t pair_capacity, entasis_diagnostic_t * diagnostic);

/**
 * sets a copied per-instance override
 *
 * changing settings invalidates that instance impact history and does not wake sleeping bodies
 *
 * @param world idle world outside callbacks and read phases
 * @param reference live body or static collidable instance
 * @param settings required finite settings, copied before application allocation
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_restitution_set(entasis_world_t * world, entasis_collidable_reference_t reference, const entasis_restitution_settings_t * settings, entasis_diagnostic_t * diagnostic);

/**
 * reads an effective instance setting including fallback
 *
 * @param world idle world outside callbacks and read phases
 * @param reference live body or static collidable instance
 * @param out_settings effective settings, written only on success
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_restitution_get(entasis_world_t * world, entasis_collidable_reference_t reference, entasis_restitution_settings_t * out_settings, entasis_diagnostic_t * diagnostic);

/**
 * removes an explicit override without removing its collidable
 *
 * the instance uses fallback settings at the next collision sample. missing overrides return NOT_FOUND
 *
 * @param world idle world outside callbacks and read phases
 * @param reference live body or static collidable instance
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_restitution_remove(entasis_world_t * world, entasis_collidable_reference_t reference, entasis_diagnostic_t * diagnostic);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* ENTASIS_COLLISION_H */
