// generated by tools/abi/generate_abi. do not edit
#ifndef ENTASIS_CONSTRAINTS_H
#define ENTASIS_CONSTRAINTS_H

#include <entasis/bodies.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * validates custom descriptions on add, apply and awakening
 *
 * @param user_context borrowed registration state
 * @param type_id owning registered ID
 * @param description read-only tightly packed f32 description
 * @param description_size exact scalar description size
 *
 * @return returns OK or a public failure status
 */
typedef entasis_status_t (ENTASIS_CALL *entasis_constraint_validate_fn)(void * user_context, entasis_constraint_type_id_t type_id, const void * description, uint32_t description_size);
/**
 * runs a native batched constraint phase through the C ABI
 *
 * @param user_context borrowed registration state
 * @param view callback-local masked kernel views
 *
 * @return no return value. unwinding through the runtime is forbidden
 */
typedef void (ENTASIS_CALL *entasis_constraint_kernel_fn)(void * user_context, const entasis_constraint_kernel_view_t * view);
/**
 * reads physical impulses for one watched custom constraint lane
 *
 * all views expire on return. do not retain pointers, mutate the world or unwind through the callback. return impulses about body centers of mass, not forces
 *
 * @param user_context borrowed provider state
 * @param input callback-local input record
 * @param output four writable wrench slots, fill the first body_count
 *
 * @return returns OK or a public failure status. failure publishes no reaction from the bundle
 */
typedef entasis_status_t (ENTASIS_CALL *entasis_joint_reaction_provider_fn)(void * user_context, const entasis_joint_reaction_provider_input_t * input, entasis_joint_impulse_wrench_t * output);

/**
 * motor force and softness settings
 */
struct entasis_motor_settings_t {
    /* maximum applied force */
    float maximum_force;
    /* velocity-proportional motor damping */
    float damping;
};

/**
 * servo speed and force settings
 */
struct entasis_servo_settings_t {
    /* maximum servo speed */
    float maximum_speed;
    /* base servo speed */
    float base_speed;
    /* maximum applied force */
    float maximum_force;
};

/**
 * caller-owned fixed-step accumulator with bounded catch-up
 */
struct entasis_fixed_stepper_t {
    /* fixed simulation timestep in seconds */
    float timestep;
    /* unconsumed elapsed time in seconds */
    float accumulator;
    /* maximum simulation steps executed by one update */
    uint8_t maximum_steps;
    /* reserved for ABI compatibility */
    uint8_t reserved[3];
};

/**
 * tagged caller-owned structural command built by entasis_command_* helpers
 */
struct entasis_command_t {
    /* active tagged variant */
    entasis_command_kind_t kind;
    /* reserved for ABI compatibility */
    uint8_t reserved0[3];
    /* caller-selected result slot used by add commands */
    int32_t result_index;
    /* fixed storage for payload */
    uint8_t payload[132];
};

/**
 * nonowning view over caller-owned command and result arrays
 */
struct entasis_command_buffer_t {
    /* borrowed command array */
    const entasis_command_t * commands;
    /* number of commands */
    uint64_t command_count;
    /* caller-owned per-command status output array */
    entasis_status_t * statuses;
    /* reserved capacity for status */
    uint64_t status_capacity;
    /* caller-owned body handle output array */
    entasis_body_handle_t * body_results;
    /* reserved capacity for body result */
    uint64_t body_result_capacity;
    /* caller-owned static handle output array */
    entasis_static_handle_t * static_results;
    /* reserved capacity for static result */
    uint64_t static_result_capacity;
};

/**
 * callback-local pointers to one eight-lane body bundle
 *
 * every non-NULL target is 32-byte aligned. only fields declared by the registration are exposed. pointers expire at callback return. do not retain them or mutate read-only targets
 */
struct entasis_constraint_body_view_t {
    /* read-only positions, NULL when access is not declared */
    const entasis_vector3_wide_t * position;
    /* read-only orientations, NULL when access is not declared */
    const entasis_quaternion_wide_t * orientation;
    /* read-only inverse masses, NULL when access is not declared */
    const entasis_f32x8_t * inverse_mass;
    /* read-only inverse inertia, NULL when access is not declared */
    const entasis_symmetric3x3_wide_t * inverse_inertia;
    /* writable linear velocities, NULL when access is not declared */
    entasis_vector3_wide_t * linear_velocity;
    /* writable angular velocities, NULL when access is not declared */
    entasis_vector3_wide_t * angular_velocity;
};

/**
 * one pointer-based custom constraint kernel invocation
 *
 * one invocation per native SIMD bundle and phase. sequential fallback invokes a single active lane in source order. leave every inactive lane unchanged, including prestep and impulse storage. pointers and access flags apply only during this callback. no ordinary world API reentry, exceptions or longjmp are permitted. caller state must support concurrent worker calls
 */
struct entasis_constraint_kernel_view_t {
    /* body_count views, not stable body IDs */
    const entasis_constraint_body_view_t * bodies;
    /* constraint arity from one through four */
    uint32_t body_count;
    /* current kernel phase */
    entasis_constraint_kernel_phase_t phase;
    /* writable structure-of-arrays prestep fields */
    entasis_f32x8_t * prestep;
    /* number of eight-lane prestep fields */
    uint32_t prestep_field_count;
    /* number of eight-lane accumulated-impulse fields */
    uint32_t impulse_field_count;
    /* writable accumulated impulses */
    entasis_f32x8_t * impulses;
    /* eight lanes: -1 active, 0 inactive */
    const entasis_i32x8_t * active_mask;
    /* substep duration */
    float dt;
    /* reciprocal substep duration */
    float inverse_dt;
};

/**
 * copied per-world custom constraint registration
 *
 * register before the first step and before adding any constraints. descriptors and callback pointers are copied before allocator calls. user state remains borrowed. registration preserves the native type range, body/prestep/impulse layouts and sleeping limits. invalid descriptors and allocation failure consume no ID
 */
struct entasis_custom_constraint_registration_t {
    /* initialize to sizeof this descriptor */
    uint32_t struct_size;
    /* initialize to 1 */
    uint32_t struct_version;
    /* unused custom ID from 56 through 63 */
    entasis_constraint_type_id_t type_id;
    /* constraint arity from one through four */
    uint32_t body_count;
    /* tightly packed f32 scalar bytes, positive and at most 256 */
    uint32_t description_size;
    /* exactly eight times description_size */
    uint32_t prestep_bundle_size;
    /* positive multiple of 32, at most 1024 */
    uint32_t impulse_bundle_size;
    /* initialize to zero */
    uint32_t _reserved0;
    /* per-body access. entries beyond body_count must be zero */
    entasis_body_access_mask_t initial_access[4];
    /* per-body access. entries beyond body_count must be zero */
    entasis_body_access_mask_t solve_access[4];
    /* caller state borrowed until world destruction */
    void * user_context;
    /* required scalar validation callback */
    entasis_constraint_validate_fn validate;
    /* required prestep/warmstart/solve callback */
    entasis_constraint_kernel_fn kernel;
    /* NULL reuses kernel for incremental updates */
    entasis_constraint_kernel_fn incremental_kernel;
};

/**
 * copied per-world custom reaction provider
 */
struct entasis_joint_reaction_provider_t {
    /* initialize to sizeof this descriptor */
    uint32_t struct_size;
    /* initialize to 1 */
    uint32_t struct_version;
    /* required scalar reaction callback */
    entasis_joint_reaction_provider_fn read;
    /* borrowed until provider replacement, clearing, joint-break disable or world destruction */
    void * user_context;
};

/**
 * strict independent thresholds for one constraint lifetime
 */
struct entasis_joint_break_limits_t {
    /* enabled force and torque comparisons */
    entasis_joint_break_metrics_t metrics;
    /* finite nonnegative force threshold when selected */
    float force;
    /* finite nonnegative torque threshold when selected */
    float torque;
    /* initialize to zero */
    uint32_t reserved;
    /* application identity captured in a break event */
    uint64_t user_id;
};

/**
 * built-in angular axis gear motor constraint description
 */
struct entasis_angular_axis_gear_motor_t {
    /* axis in body A local space */
    entasis_vector3_t local_axis_a;
    /* scale applied to body A angular velocity around the constrained axis */
    float velocity_scale;
    /* motor force and softness settings */
    entasis_motor_settings_t settings;
};

/**
 * built-in angular axis motor constraint description
 */
struct entasis_angular_axis_motor_t {
    /* axis in body A local space */
    entasis_vector3_t local_axis_a;
    /* target relative angular velocity around the constrained axis */
    float target_velocity;
    /* motor force and softness settings */
    entasis_motor_settings_t settings;
};

/**
 * built-in angular hinge constraint description
 */
struct entasis_angular_hinge_t {
    /* hinge axis in body A local space */
    entasis_vector3_t local_hinge_axis_a;
    /* hinge axis in body B local space */
    entasis_vector3_t local_hinge_axis_b;
    /* spring frequency and damping settings */
    entasis_spring_settings_t spring_settings;
};

/**
 * built-in angular motor constraint description
 */
struct entasis_angular_motor_t {
    /* target velocity in body A local space */
    entasis_vector3_t target_velocity_local_a;
    /* motor force and softness settings */
    entasis_motor_settings_t settings;
};

/**
 * built-in angular servo constraint description
 */
struct entasis_angular_servo_t {
    /* target orientation of body B relative to body A in body A local space */
    entasis_quaternion_t target_relative_rotation_local_a;
    /* spring frequency and damping settings */
    entasis_spring_settings_t spring_settings;
    /* servo speed and force settings */
    entasis_servo_settings_t servo_settings;
};

/**
 * built-in angular swivel hinge constraint description
 */
struct entasis_angular_swivel_hinge_t {
    /* swivel axis in body A local space */
    entasis_vector3_t local_swivel_axis_a;
    /* hinge axis in body B local space */
    entasis_vector3_t local_hinge_axis_b;
    /* spring frequency and damping settings */
    entasis_spring_settings_t spring_settings;
};

/**
 * built-in area constraint description
 */
struct entasis_area_constraint_t {
    /* target scaled triangle area enforced by the constraint */
    float target_scaled_area;
    /* spring frequency and damping settings */
    entasis_spring_settings_t spring_settings;
};

/**
 * built-in ball socket constraint description
 */
struct entasis_ball_socket_t {
    /* anchor offset in body A local space */
    entasis_vector3_t local_offset_a;
    /* anchor offset in body B local space */
    entasis_vector3_t local_offset_b;
    /* spring frequency and damping settings */
    entasis_spring_settings_t spring_settings;
};

/**
 * built-in ball socket motor constraint description
 */
struct entasis_ball_socket_motor_t {
    /* anchor offset in body B local space */
    entasis_vector3_t local_offset_b;
    /* target velocity in body A local space */
    entasis_vector3_t target_velocity_local_a;
    /* motor force and softness settings */
    entasis_motor_settings_t settings;
};

/**
 * built-in ball socket servo constraint description
 */
struct entasis_ball_socket_servo_t {
    /* anchor offset in body A local space */
    entasis_vector3_t local_offset_a;
    /* anchor offset in body B local space */
    entasis_vector3_t local_offset_b;
    /* spring frequency and damping settings */
    entasis_spring_settings_t spring_settings;
    /* servo speed and force settings */
    entasis_servo_settings_t servo_settings;
};

/**
 * built-in center distance constraint description
 */
struct entasis_center_distance_constraint_t {
    /* target distance between the two body centers */
    float target_distance;
    /* spring frequency and damping settings */
    entasis_spring_settings_t spring_settings;
};

/**
 * built-in center distance limit constraint description
 */
struct entasis_center_distance_limit_t {
    /* minimum allowed distance */
    float minimum_distance;
    /* maximum allowed distance */
    float maximum_distance;
    /* spring frequency and damping settings */
    entasis_spring_settings_t spring_settings;
};

/**
 * built-in distance limit constraint description
 */
struct entasis_distance_limit_t {
    /* anchor offset in body A local space */
    entasis_vector3_t local_offset_a;
    /* anchor offset in body B local space */
    entasis_vector3_t local_offset_b;
    /* minimum allowed distance */
    float minimum_distance;
    /* maximum allowed distance */
    float maximum_distance;
    /* spring frequency and damping settings */
    entasis_spring_settings_t spring_settings;
};

/**
 * built-in distance servo constraint description
 */
struct entasis_distance_servo_t {
    /* anchor offset in body A local space */
    entasis_vector3_t local_offset_a;
    /* anchor offset in body B local space */
    entasis_vector3_t local_offset_b;
    /* target distance between the two local attachment points */
    float target_distance;
    /* servo speed and force settings */
    entasis_servo_settings_t servo_settings;
    /* spring frequency and damping settings */
    entasis_spring_settings_t spring_settings;
};

/**
 * built-in hinge constraint description
 */
struct entasis_hinge_t {
    /* anchor offset in body A local space */
    entasis_vector3_t local_offset_a;
    /* hinge axis in body A local space */
    entasis_vector3_t local_hinge_axis_a;
    /* anchor offset in body B local space */
    entasis_vector3_t local_offset_b;
    /* hinge axis in body B local space */
    entasis_vector3_t local_hinge_axis_b;
    /* spring frequency and damping settings */
    entasis_spring_settings_t spring_settings;
};

/**
 * built-in linear axis limit constraint description
 */
struct entasis_linear_axis_limit_t {
    /* anchor offset in body A local space */
    entasis_vector3_t local_offset_a;
    /* anchor offset in body B local space */
    entasis_vector3_t local_offset_b;
    /* axis in body-local space */
    entasis_vector3_t local_axis;
    /* minimum allowed offset along the constrained axis */
    float minimum_offset;
    /* maximum allowed offset along the constrained axis */
    float maximum_offset;
    /* spring frequency and damping settings */
    entasis_spring_settings_t spring_settings;
};

/**
 * built-in linear axis motor constraint description
 */
struct entasis_linear_axis_motor_t {
    /* anchor offset in body A local space */
    entasis_vector3_t local_offset_a;
    /* anchor offset in body B local space */
    entasis_vector3_t local_offset_b;
    /* axis in body-local space */
    entasis_vector3_t local_axis;
    /* target relative velocity along the constrained axis */
    float target_velocity;
    /* motor force and softness settings */
    entasis_motor_settings_t settings;
};

/**
 * built-in linear axis servo constraint description
 */
struct entasis_linear_axis_servo_t {
    /* anchor offset in body A local space */
    entasis_vector3_t local_offset_a;
    /* anchor offset in body B local space */
    entasis_vector3_t local_offset_b;
    /* constraint plane normal in body A local space */
    entasis_vector3_t local_plane_normal;
    /* target offset from the constraint plane */
    float target_offset;
    /* servo speed and force settings */
    entasis_servo_settings_t servo_settings;
    /* spring frequency and damping settings */
    entasis_spring_settings_t spring_settings;
};

/**
 * built-in one body angular motor constraint description
 */
struct entasis_one_body_angular_motor_t {
    /* target world-space angular velocity */
    entasis_vector3_t target_velocity;
    /* motor force and softness settings */
    entasis_motor_settings_t settings;
};

/**
 * built-in one body angular servo constraint description
 */
struct entasis_one_body_angular_servo_t {
    /* target world-space body orientation */
    entasis_quaternion_t target_orientation;
    /* spring frequency and damping settings */
    entasis_spring_settings_t spring_settings;
    /* servo speed and force settings */
    entasis_servo_settings_t servo_settings;
};

/**
 * built-in one body linear motor constraint description
 */
struct entasis_one_body_linear_motor_t {
    /* anchor offset in body-local space */
    entasis_vector3_t local_offset;
    /* target world-space velocity at the local attachment point */
    entasis_vector3_t target_velocity;
    /* motor force and softness settings */
    entasis_motor_settings_t settings;
};

/**
 * built-in one body linear servo constraint description
 */
struct entasis_one_body_linear_servo_t {
    /* anchor offset in body-local space */
    entasis_vector3_t local_offset;
    /* target point in world space */
    entasis_vector3_t target;
    /* spring frequency and damping settings */
    entasis_spring_settings_t spring_settings;
    /* servo speed and force settings */
    entasis_servo_settings_t servo_settings;
};

/**
 * built-in point on line servo constraint description
 */
struct entasis_point_on_line_servo_t {
    /* anchor offset in body A local space */
    entasis_vector3_t local_offset_a;
    /* anchor offset in body B local space */
    entasis_vector3_t local_offset_b;
    /* line direction in body A local space */
    entasis_vector3_t local_direction;
    /* servo speed and force settings */
    entasis_servo_settings_t servo_settings;
    /* spring frequency and damping settings */
    entasis_spring_settings_t spring_settings;
};

/**
 * built-in swing limit constraint description
 */
struct entasis_swing_limit_t {
    /* swing axis in body A local space */
    entasis_vector3_t axis_local_a;
    /* swing axis in body B local space */
    entasis_vector3_t axis_local_b;
    /* minimum allowed dot product between the two swing axes */
    float minimum_dot;
    /* spring frequency and damping settings */
    entasis_spring_settings_t spring_settings;
};

/**
 * built-in swivel hinge constraint description
 */
struct entasis_swivel_hinge_t {
    /* anchor offset in body A local space */
    entasis_vector3_t local_offset_a;
    /* swivel axis in body A local space */
    entasis_vector3_t local_swivel_axis_a;
    /* anchor offset in body B local space */
    entasis_vector3_t local_offset_b;
    /* hinge axis in body B local space */
    entasis_vector3_t local_hinge_axis_b;
    /* spring frequency and damping settings */
    entasis_spring_settings_t spring_settings;
};

/**
 * built-in twist limit constraint description
 */
struct entasis_twist_limit_t {
    /* constraint basis in body A local space */
    entasis_quaternion_t local_basis_a;
    /* constraint basis in body B local space */
    entasis_quaternion_t local_basis_b;
    /* minimum allowed relative twist angle */
    float minimum_angle;
    /* maximum allowed relative twist angle */
    float maximum_angle;
    /* spring frequency and damping settings */
    entasis_spring_settings_t spring_settings;
};

/**
 * built-in twist motor constraint description
 */
struct entasis_twist_motor_t {
    /* axis in body A local space */
    entasis_vector3_t local_axis_a;
    /* axis in body B local space */
    entasis_vector3_t local_axis_b;
    /* target relative angular velocity around the twist axes */
    float target_velocity;
    /* motor force and softness settings */
    entasis_motor_settings_t settings;
};

/**
 * built-in twist servo constraint description
 */
struct entasis_twist_servo_t {
    /* constraint basis in body A local space */
    entasis_quaternion_t local_basis_a;
    /* constraint basis in body B local space */
    entasis_quaternion_t local_basis_b;
    /* target relative twist angle */
    float target_angle;
    /* spring frequency and damping settings */
    entasis_spring_settings_t spring_settings;
    /* servo speed and force settings */
    entasis_servo_settings_t servo_settings;
};

/**
 * built-in volume constraint description
 */
struct entasis_volume_constraint_t {
    /* target scaled tetrahedron volume enforced by the constraint */
    float target_scaled_volume;
    /* spring frequency and damping settings */
    entasis_spring_settings_t spring_settings;
};

/**
 * built-in weld constraint description
 */
struct entasis_weld_t {
    /* anchor offset in body-local space */
    entasis_vector3_t local_offset;
    /* target orientation of body B relative to body A in body A local space */
    entasis_quaternion_t local_orientation;
    /* spring frequency and damping settings */
    entasis_spring_settings_t spring_settings;
};

/**
 * pointer-free active or sleeping constraint inspection record
 */
struct entasis_constraint_info_t {
    /* object handle */
    entasis_constraint_handle_t handle;
    /* registered public type ID */
    entasis_constraint_type_id_t type_id;
    /* fixed storage for bodies */
    entasis_body_handle_t bodies[4];
    /* number of bodies referenced by the record */
    uint8_t body_count;
    /* current state */
    entasis_constraint_state_t state;
    /* reserved for ABI compatibility */
    uint8_t reserved[2];
};

/**
 * pointer-free solver contact point snapshot
 */
struct entasis_solver_contact_point_t {
    /* contact offset from pair member A */
    entasis_vector3_t offset_a;
    /* contact or hit normal */
    entasis_vector3_t normal;
    /* contact penetration depth */
    float depth;
    /* pair-local contact feature ID */
    int32_t feature_id;
    /* accumulated normal impulse for this contact point */
    float normal_impulse;
};

/**
 * physical impulses returned by a custom reaction provider
 */
struct entasis_joint_impulse_wrench_t {
    /* world-space linear impulse */
    entasis_vector3_t linear;
    /* world-space angular impulse about the body center of mass */
    entasis_vector3_t angular;
};

/**
 * physical reaction at one completed substep
 */
struct entasis_joint_force_wrench_t {
    /* world-space force */
    entasis_vector3_t linear;
    /* world-space torque about the body center of mass */
    entasis_vector3_t angular;
};

/**
 * pointer-free snapshot of one built-in contact constraint
 */
struct entasis_solver_contact_data_t {
    /* constraint handle */
    entasis_constraint_handle_t constraint;
    /* collidable reference for pair member A */
    entasis_collidable_reference_t pair_a;
    /* collidable reference for pair member B */
    entasis_collidable_reference_t pair_b;
    /* active tagged variant */
    entasis_contact_constraint_kind_t kind;
    /* number of bodies referenced by the record */
    uint8_t body_count;
    /* number of valid contacts */
    uint8_t contact_count;
    /* number of valid impulse scalars */
    uint8_t impulse_count;
    /* fixed storage for body handles */
    entasis_body_handle_t body_handles[4];
    /* body B offset relative to body A */
    entasis_vector3_t offset_b;
    /* contact or hit normal */
    entasis_vector3_t normal;
    /* combined contact material */
    entasis_contact_material_t material;
    /* fixed storage for contacts */
    entasis_solver_contact_point_t contacts[4];
    /* fixed storage for impulses */
    float impulses[32];
};

/**
 * borrowed scalar inputs to the custom reaction provider
 */
struct entasis_joint_reaction_provider_input_t {
    /* registered custom type */
    entasis_constraint_type_id_t type_id;
    /* active bodies, one through four */
    uint32_t body_count;
    /* body poses for this scalar lane */
    entasis_rigid_pose_t poses[4];
    /* borrowed scalar description, valid only during the callback */
    const void * description;
    /* scalar description bytes */
    uint32_t description_size;
    /* valid scalar impulses, at most 32 */
    uint32_t impulse_count;
    /* solved scalar impulses in registered field order */
    float impulses[32];
    /* actual positive substep duration in seconds */
    float substep_duration;
    /* zero */
    uint32_t reserved;
};

/**
 * representative scalar reaction sample
 */
struct entasis_joint_reaction_sample_t {
    /* number of bodies in the sample */
    uint32_t body_count;
    /* captured body handles */
    entasis_body_handle_t bodies[4];
    /* physical forces and torques */
    entasis_joint_force_wrench_t forces[4];
    /* duration used to convert impulse into force */
    float substep_duration;
    /* largest force magnitude across bodies in this sample */
    float maximum_force;
    /* largest torque magnitude across bodies in this sample */
    float maximum_torque;
};

/**
 * last committed watched reaction, unchanged by failed physics
 */
struct entasis_joint_reaction_t {
    /* strongest normalized selected load in the completed step */
    entasis_joint_reaction_sample_t sample;
    /* completed physics step index */
    uint64_t step;
    /* sampled substep index */
    uint32_t substep;
    /* whether a solved sample has been committed */
    entasis_joint_reaction_state_t state;
    /* peak force across completed substeps */
    float maximum_force;
    /* peak torque across completed substeps */
    float maximum_torque;
};

/**
 * immutable threshold break captured after successful physics
 */
struct entasis_joint_break_event_t {
    /* retired constraint handle */
    entasis_constraint_handle_t constraint;
    /* captured constraint type */
    entasis_constraint_type_id_t type_id;
    /* monotonic watch lifetime */
    uint64_t lifetime;
    /* application identity captured from the limits */
    uint64_t user_id;
    /* metrics that strictly exceeded their limits */
    entasis_joint_break_metrics_t exceeded;
    /* zero */
    uint32_t reserved;
    /* committed physical sample retained after removal */
    entasis_joint_reaction_t reaction;
};

/**
 * constructs exact built-in servo settings without allocation
 *
 * allocation: none
 *
 * @param maximum_speed maximum correction speed
 * @param base_speed minimum correction speed used while error remains
 * @param maximum_force maximum force the servo may apply
 *
 * @return returns the servo settings
 */
ENTASIS_API entasis_servo_settings_t ENTASIS_CALL entasis_servo_settings(float maximum_speed, float base_speed, float maximum_force);

/**
 * constructs motor settings from maximum force and stable softness semantics
 *
 * softness is zero for a rigid motor and increases as the motor becomes softer. allocation: none
 *
 * @param maximum_force maximum force the motor may apply
 * @param softness motor softness
 *
 * @return returns the motor settings
 */
ENTASIS_API entasis_motor_settings_t ENTASIS_CALL entasis_motor_settings(float maximum_force, float softness);

/**
 * returns candidate for a supported built-in description type or ENTASIS_CONSTRAINT_TYPE_INVALID
 *
 * contact constraints and unsupported/custom descriptions return invalid
 *
 * @param candidate candidate constraint type ID
 *
 * @return returns the constraint type ID
 */
ENTASIS_API entasis_constraint_type_id_t ENTASIS_CALL entasis_constraint_type_id(entasis_constraint_type_id_t candidate);

/**
 * returns the required body count for one built-in constraint type, or zero when unsupported
 *
 * @param type_id registered constraint type ID
 *
 * @return returns the unsigned 32-bit integer
 */
ENTASIS_API uint32_t ENTASIS_CALL entasis_constraint_body_count(entasis_constraint_type_id_t type_id);

/**
 * adds one built-in constraint
 *
 * allocation: world storage may grow. ownership: owner thread while world idle
 *
 * @param world target world
 * @param type_id registered constraint type ID
 * @param bodies input body handle array
 * @param body_count number of bodies referenced by the constraint
 * @param description memory to copy
 * @param description_size size of one constraint description in bytes
 * @param out_handle receives the created constraint handle
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_constraint_add(entasis_world_t * world, entasis_constraint_type_id_t type_id, const entasis_body_handle_t * bodies, uint32_t body_count, const void * description, uint32_t description_size, entasis_constraint_handle_t * out_handle, entasis_diagnostic_t * diagnostic);

/**
 * copies one active or sleeping built-in constraint description into a matching typed output value
 *
 * allocation: none. ownership: owner thread while world idle
 *
 * @param world target world
 * @param handle target constraint handle
 * @param type_id registered constraint type ID
 * @param out_description receives the copied constraint description bytes
 * @param description_size size of one constraint description in bytes
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_constraint_get(entasis_world_t * world, entasis_constraint_handle_t handle, entasis_constraint_type_id_t type_id, void * out_description, uint32_t description_size, entasis_diagnostic_t * diagnostic);

/**
 * applies one matching built-in constraint description and awakens a sleeping island when required
 *
 * applying a sleeping constraint awakens its island through the low-level path. ownership: owner thread while world idle
 *
 * @param world target world
 * @param handle target constraint handle
 * @param type_id registered constraint type ID
 * @param description memory to copy
 * @param description_size size of one constraint description in bytes
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_constraint_apply(entasis_world_t * world, entasis_constraint_handle_t handle, entasis_constraint_type_id_t type_id, const void * description, uint32_t description_size, entasis_diagnostic_t * diagnostic);

/**
 * removes one active or sleeping constraint
 *
 * removing a sleeping constraint may awaken its island before removal. ownership: owner thread while world idle
 *
 * @param world target world
 * @param handle target constraint handle
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_constraint_remove(entasis_world_t * world, entasis_constraint_handle_t handle, entasis_diagnostic_t * diagnostic);

/**
 * adds a homogeneous constraint batch using flattened body handles and contiguous typed descriptions
 *
 * @param world target world
 * @param type_id registered constraint type ID
 * @param bodies input body handle array
 * @param body_handle_count number of body handles
 * @param descriptions packed input constraint descriptions
 * @param description_stride byte stride between consecutive constraint descriptions
 * @param count number of entries in the input arrays
 * @param out_handles receives constraint handles in input order
 * @param out_completed receives the number of successfully completed prefix entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_constraint_add_batch(entasis_world_t * world, entasis_constraint_type_id_t type_id, const entasis_body_handle_t * bodies, uint64_t body_handle_count, const void * descriptions, uint32_t description_stride, uint64_t count, entasis_constraint_handle_t * out_handles, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * applies matching homogeneous descriptions in input order and reports how many succeeded before the first failure
 *
 * @param world target world
 * @param type_id registered constraint type ID
 * @param handles input constraint handles
 * @param descriptions packed input constraint descriptions
 * @param description_stride byte stride between consecutive constraint descriptions
 * @param count number of entries in the input arrays
 * @param out_completed receives the number of successfully completed prefix entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_constraint_apply_batch(entasis_world_t * world, entasis_constraint_type_id_t type_id, const entasis_constraint_handle_t * handles, const void * descriptions, uint32_t description_stride, uint64_t count, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * removes constraints in input order and reports how many succeeded before the first failure
 *
 * @param world target world
 * @param handles input constraint handles
 * @param count number of entries in the input arrays
 * @param out_completed receives the number of successfully completed prefix entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_constraint_remove_batch(entasis_world_t * world, const entasis_constraint_handle_t * handles, uint64_t count, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * returns a pointer-free constraint storage and connectivity snapshot
 *
 * allocation: none
 *
 * @param world target world
 * @param handle target constraint handle
 * @param out_info receives the constraint info
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_constraint_inspect(entasis_world_t * world, entasis_constraint_handle_t handle, entasis_constraint_info_t * out_info, entasis_diagnostic_t * diagnostic);

/**
 * returns the total active and sleeping constraint count
 *
 * @param world target world
 * @param out_count receives the number of returned entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_constraint_count(entasis_world_t * world, uint64_t * out_count, entasis_diagnostic_t * diagnostic);

/**
 * writes live constraints in ascending numeric handle order without allocation
 *
 * if output is too small, it writes the prefix and returns total with ENTASIS_STATUS_CAPACITY_MISSING. allocation: none
 *
 * @param world target world
 * @param out_infos receives constraint inspection records in handle order
 * @param capacity number of entries available in the output array
 * @param out_written receives the number of output entries written
 * @param out_required receives the total required output capacity
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_constraint_enumerate(entasis_world_t * world, entasis_constraint_info_t * out_infos, uint64_t capacity, uint64_t * out_written, uint64_t * out_required, entasis_diagnostic_t * diagnostic);

/**
 * returns the number of constraints connected to one body
 *
 * @param world target world
 * @param handle target body handle
 * @param out_count receives the number of returned entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_constraint_count(entasis_world_t * world, entasis_body_handle_t handle, uint64_t * out_count, entasis_diagnostic_t * diagnostic);

/**
 * writes connected constraint handles in runtime body-list order
 *
 * if output is too small, the prefix is written and ENTASIS_STATUS_CAPACITY_MISSING is returned with the required count. allocation: none
 *
 * @param world target world
 * @param handle target body handle
 * @param output caller-owned output array
 * @param capacity number of entries available in the output array
 * @param out_written receives the number of output entries written
 * @param out_required receives the total required output capacity
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_constraints(entasis_world_t * world, entasis_body_handle_t handle, entasis_constraint_handle_t * output, uint64_t capacity, uint64_t * out_written, uint64_t * out_required, entasis_diagnostic_t * diagnostic);

/**
 * writes connected body edges while preserving duplicates
 *
 * duplicate body handles are preserved when multiple constraints connect the same pair. allocation: none
 *
 * @param world target world
 * @param handle target body handle
 * @param output caller-owned output array
 * @param capacity number of entries available in the output array
 * @param out_written receives the number of output entries written
 * @param out_required receives the total required output capacity
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_connected_bodies(entasis_world_t * world, entasis_body_handle_t handle, entasis_body_handle_t * output, uint64_t capacity, uint64_t * out_written, uint64_t * out_required, entasis_diagnostic_t * diagnostic);

/**
 * writes body handles referenced by one constraint
 *
 * allocation: none
 *
 * @param world target world
 * @param handle target constraint handle
 * @param output caller-owned output array
 * @param capacity number of entries available in the output array
 * @param out_written receives the number of output entries written
 * @param out_required receives the total required output capacity
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_constraint_connected_bodies(entasis_world_t * world, entasis_constraint_handle_t handle, entasis_body_handle_t * output, uint64_t capacity, uint64_t * out_written, uint64_t * out_required, entasis_diagnostic_t * diagnostic);

/**
 * reports whether one live body is active or sleeping
 *
 * allocation: none. ownership: read-only while the world is idle
 *
 * @param world target world
 * @param handle target body handle
 * @param out_state receives the copied body activation state
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_activation_state(entasis_world_t * world, entasis_body_handle_t handle, entasis_body_activation_state_t * out_state, entasis_diagnostic_t * diagnostic);

/**
 * reports whether one live body is active
 *
 * missing handles return false and preserve the low-level ENTASIS_STATUS_NOT_FOUND status
 *
 * @param world target world
 * @param handle target body handle
 * @param out_value receives ENTASIS_TRUE when the condition holds, otherwise ENTASIS_FALSE
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_is_active(entasis_world_t * world, entasis_body_handle_t handle, entasis_bool_t * out_value, entasis_diagnostic_t * diagnostic);

/**
 * reports whether one live body is sleeping
 *
 * missing handles return false and preserve the low-level ENTASIS_STATUS_NOT_FOUND status
 *
 * @param world target world
 * @param handle target body handle
 * @param out_value receives ENTASIS_TRUE when the condition holds, otherwise ENTASIS_FALSE
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_is_sleeping(entasis_world_t * world, entasis_body_handle_t handle, entasis_bool_t * out_value, entasis_diagnostic_t * diagnostic);

/**
 * awakens the complete constraint-connected sleeping island containing one body
 *
 * the initialized world dispatcher is used unless an explicit dispatcher is supplied. an already active body is a successful no-op. allocation may occur only when existing active storage must grow. ownership: owner thread only while the world is idle
 *
 * @param world target world
 * @param handle target body handle
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_awaken(entasis_world_t * world, entasis_body_handle_t handle, entasis_diagnostic_t * diagnostic);

/**
 * applies one instantaneous linear impulse without forcing activation
 *
 * this matches the low-level body-reference behavior. ownership: owner thread while the world is idle. allocation: none
 *
 * @param world target world
 * @param handle target body handle
 * @param impulse world-space impulse
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_apply_linear_impulse(entasis_world_t * world, entasis_body_handle_t handle, entasis_vector3_t impulse, entasis_diagnostic_t * diagnostic);

/**
 * applies one instantaneous angular impulse using current world inverse inertia
 *
 * ownership: owner thread while the world is idle. allocation: none
 *
 * @param world target world
 * @param handle target body handle
 * @param impulse world-space impulse
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_apply_angular_impulse(entasis_world_t * world, entasis_body_handle_t handle, entasis_vector3_t impulse, entasis_diagnostic_t * diagnostic);

/**
 * applies an impulse at a world-space offset from center of mass
 *
 * the body is not implicitly awakened. ownership: owner thread while the world is idle. allocation: none
 *
 * @param world target world
 * @param handle target body handle
 * @param impulse world-space impulse
 * @param offset offset applied by the operation
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_apply_impulse(entasis_world_t * world, entasis_body_handle_t handle, entasis_vector3_t impulse, entasis_vector3_t offset, entasis_diagnostic_t * diagnostic);

/**
 * returns world-space velocity at an offset from center of mass
 *
 * allocation: none
 *
 * @param world target world
 * @param handle target body handle
 * @param offset offset applied by the operation
 * @param out_velocity receives the requested body velocity component
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_velocity_at_offset(entasis_world_t * world, entasis_body_handle_t handle, entasis_vector3_t offset, entasis_vector3_t * out_velocity, entasis_diagnostic_t * diagnostic);

/**
 * returns current broad-phase bounds of one body
 *
 * sleeping bodies are read from the static broad-phase tree. allocation: none
 *
 * @param world target world
 * @param handle target body handle
 * @param out_bounds receives the bounding box
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_bounds(entasis_world_t * world, entasis_body_handle_t handle, entasis_bounding_box_t * out_bounds, entasis_diagnostic_t * diagnostic);

/**
 * recomputes broad-phase bounds after an advanced direct pose write
 *
 * it does not refit the complete tree. ownership: owner thread while the world is idle. allocation: none
 *
 * @param world target world
 * @param handle target body handle
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_update_bounds(entasis_world_t * world, entasis_body_handle_t handle, entasis_diagnostic_t * diagnostic);

/**
 * returns current broad-phase bounds of one static
 *
 * allocation: none
 *
 * @param world target world
 * @param handle target static handle
 * @param out_bounds receives the bounding box
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_bounds(entasis_world_t * world, entasis_static_handle_t handle, entasis_bounding_box_t * out_bounds, entasis_diagnostic_t * diagnostic);

/**
 * recomputes broad-phase bounds after an advanced direct pose write
 *
 * it does not awaken overlapping bodies. ownership: owner thread while the world is idle. allocation: none
 *
 * @param world target world
 * @param handle target static handle
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_update_bounds(entasis_world_t * world, entasis_static_handle_t handle, entasis_diagnostic_t * diagnostic);

/**
 * writes all scalar warmstart impulses for one active or sleeping constraint
 *
 * allocation: none
 *
 * @param world target world
 * @param handle target constraint handle
 * @param output caller-owned output array
 * @param capacity number of entries available in the output array
 * @param out_written receives the number of output entries written
 * @param out_required receives the total required output capacity
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_constraint_accumulated_impulses(entasis_world_t * world, entasis_constraint_handle_t handle, float * output, uint64_t capacity, uint64_t * out_written, uint64_t * out_required, entasis_diagnostic_t * diagnostic);

/**
 * returns the accumulated impulse magnitude for one constraint
 *
 * @param world target world
 * @param handle target constraint handle
 * @param out_value receives the floating-point value
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_constraint_accumulated_impulse_magnitude(entasis_world_t * world, entasis_constraint_handle_t handle, float * out_value, entasis_diagnostic_t * diagnostic);

/**
 * returns the accumulated impulse magnitude squared for one constraint
 *
 * @param world target world
 * @param handle target constraint handle
 * @param out_value receives the floating-point value
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_constraint_accumulated_impulse_magnitude_squared(entasis_world_t * world, entasis_constraint_handle_t handle, float * out_value, entasis_diagnostic_t * diagnostic);

/**
 * rescales active warmstart impulses after a timestep change
 *
 * use new_effective_dt / old_effective_dt after a timestep or substep change
 *
 * @param world target world
 * @param scale scalar multiplier for accumulated impulses, typically new_effective_dt / old_effective_dt
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_scale_active_accumulated_impulses(entasis_world_t * world, float scale, entasis_diagnostic_t * diagnostic);

/**
 * rescales active and sleeping warmstart impulses after a timestep change
 *
 * this touches all constraint impulse storage
 *
 * @param world target world
 * @param scale scalar multiplier for accumulated impulses, typically new_effective_dt / old_effective_dt
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_scale_accumulated_impulses(entasis_world_t * world, float scale, entasis_diagnostic_t * diagnostic);

/**
 * extracts one built-in active or sleeping solver contact snapshot
 *
 * it supports active and sleeping contacts. allocation: none
 *
 * @param world target world
 * @param handle target constraint handle
 * @param out_data receives the solver contact data
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_solver_contact_data(entasis_world_t * world, entasis_constraint_handle_t handle, entasis_solver_contact_data_t * out_data, entasis_diagnostic_t * diagnostic);

/**
 * constructs caller-owned fixed-step accumulator state
 *
 * @param timestep fixed simulation timestep in seconds
 * @param maximum_steps maximum fixed steps allowed for one update
 *
 * @return returns the fixed stepper
 */
ENTASIS_API entasis_fixed_stepper_t ENTASIS_CALL entasis_fixed_stepper(float timestep, uint8_t maximum_steps);

/**
 * clears accumulated elapsed time without changing fixed-step policy
 *
 * @param stepper caller-owned fixed-step accumulator
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_fixed_stepper_reset(entasis_fixed_stepper_t * stepper);

/**
 * advances a world in bounded exact fixed steps and returns interpolation alpha
 *
 * after success, alpha is the remaining accumulator fraction in [0, 1). a failed step leaves its time in the accumulator, but does not roll back physics already performed. inspect the failure before deciding whether the world can continue
 *
 * @param stepper caller-owned fixed-step accumulator
 * @param world target world
 * @param elapsed elapsed real time added to the accumulator in seconds
 * @param out_steps receives the number of fixed simulation steps performed
 * @param out_alpha receives the remaining accumulator fraction after stepping
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_fixed_stepper_update(entasis_fixed_stepper_t * stepper, entasis_world_t * world, float elapsed, uint32_t * out_steps, float * out_alpha, entasis_diagnostic_t * diagnostic);

/**
 * constructs fixed substep and velocity-iteration solve settings
 *
 * each substep executes velocity_iterations solver iterations
 *
 * @param substeps number of solver substeps
 * @param velocity_iterations velocity solve iterations per substep
 * @param fallback_batch_threshold batch index reserved for fallback constraints
 *
 * @return returns the solve description
 */
ENTASIS_API entasis_solve_description_t ENTASIS_CALL entasis_solve_description_substeps(int32_t substeps, int32_t velocity_iterations, int32_t fallback_batch_threshold);

/**
 * constructs a body-add command with caller-selected result slot
 *
 * @param description body description to copy
 * @param result_index caller-selected slot in the matching command-buffer handle result array
 *
 * @return returns the command
 */
ENTASIS_API entasis_command_t ENTASIS_CALL entasis_command_body_add(entasis_body_description_t description, int32_t result_index);

/**
 * constructs a body-apply command
 *
 * @param handle target body handle
 * @param description body description to copy
 *
 * @return returns the command
 */
ENTASIS_API entasis_command_t ENTASIS_CALL entasis_command_body_apply(entasis_body_handle_t handle, entasis_body_description_t description);

/**
 * constructs a body-remove command
 *
 * @param handle target body handle
 *
 * @return returns the command
 */
ENTASIS_API entasis_command_t ENTASIS_CALL entasis_command_body_remove(entasis_body_handle_t handle);

/**
 * constructs a static-add command with result slot and awakening policy
 *
 * @param description static description to copy
 * @param result_index caller-selected slot in the matching command-buffer handle result array
 * @param awakening static mutation awakening policy
 *
 * @return returns the command
 */
ENTASIS_API entasis_command_t ENTASIS_CALL entasis_command_static_add(entasis_static_description_t description, int32_t result_index, entasis_awakening_policy_t awakening);

/**
 * constructs a static-apply command with awakening policy
 *
 * @param handle target static handle
 * @param description static description to copy
 * @param awakening static mutation awakening policy
 *
 * @return returns the command
 */
ENTASIS_API entasis_command_t ENTASIS_CALL entasis_command_static_apply(entasis_static_handle_t handle, entasis_static_description_t description, entasis_awakening_policy_t awakening);

/**
 * constructs a static-remove command with awakening policy
 *
 * @param handle target static handle
 * @param awakening static mutation awakening policy
 *
 * @return returns the command
 */
ENTASIS_API entasis_command_t ENTASIS_CALL entasis_command_static_remove(entasis_static_handle_t handle, entasis_awakening_policy_t awakening);

/**
 * constructs a nonowning caller-owned structural command buffer view
 *
 * no allocation is performed and every supplied slice must outlive entasis_world_apply_commands
 *
 * @param commands input structural command array
 * @param command_count number of commands
 * @param statuses caller-owned per-command status array
 * @param status_capacity number of entries available in the status array
 * @param body_results caller-owned body handle result array
 * @param body_result_capacity number of entries available in the body result array
 * @param static_results caller-owned static handle result array
 * @param static_result_capacity number of entries available in the static result array
 *
 * @return returns the command buffer
 */
ENTASIS_API entasis_command_buffer_t ENTASIS_CALL entasis_command_buffer(const entasis_command_t * commands, uint64_t command_count, entasis_status_t * statuses, uint64_t status_capacity, entasis_body_handle_t * body_results, uint64_t body_result_capacity, entasis_static_handle_t * static_results, uint64_t static_result_capacity);

/**
 * applies caller-owned structural commands in exact input order after one capacity preflight
 *
 * one combined capacity check covers all body and static additions. the operation commits a successful prefix and stops at the first failure. out_processed receives the first failing command index. add commands write handles into caller-selected result slots. commands cannot reference handles created by another command in the same buffer. allocation: the initial capacity check may grow world storage. ownership: owner thread only while the world is idle
 *
 * @param world target world
 * @param buffer caller-owned command buffer
 * @param out_processed receives the number of commands processed before the operation stopped
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_apply_commands(entasis_world_t * world, const entasis_command_buffer_t * buffer, uint64_t * out_processed, entasis_diagnostic_t * diagnostic);

/**
 * initializes custom constraint descriptor size and version
 *
 * fill storage sizes, masks, unused type_id and callbacks before registration
 *
 * @return returns an initialized descriptor
 */
ENTASIS_API entasis_custom_constraint_registration_t ENTASIS_CALL entasis_custom_constraint_registration_default(void);

/**
 * returns the first unused custom constraint ID
 *
 * read-only. IDs are scoped to one world. no ID is consumed by this operation
 *
 * @param world initialized world
 * @param out_type_id required output. invalid on failure
 * @param diagnostic optional diagnostic output
 *
 * @return returns the operation status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_custom_constraint_next_type_id(entasis_world_t * world, entasis_constraint_type_id_t * out_type_id, entasis_diagnostic_t * diagnostic);

/**
 * registers copied contextual constraint callbacks
 *
 * rejected during a read phase, callback reentry, after stepping or after adding any constraint. world clear retains registrations. caller callback state is released by its owner after world destruction
 *
 * @param world initialized world
 * @param registration complete registration descriptor
 * @param diagnostic optional diagnostic output
 *
 * @return returns the operation status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_custom_constraint_register(entasis_world_t * world, const entasis_custom_constraint_registration_t * registration, entasis_diagnostic_t * diagnostic);

/**
 * adds one custom constraint
 *
 * input and output buffers must not overlap. reuses native validation, awakening and storage. no extra per-constraint callback metadata
 *
 * @param world initialized world
 * @param type_id registered custom type ID
 * @param bodies body_count body handles
 * @param body_count must match the registered arity
 * @param description 4-byte aligned scalar description
 * @param description_size must match the registered size
 * @param out_handle required output, invalid on failure
 * @param diagnostic optional diagnostic output
 *
 * @return returns the operation status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_custom_constraint_add(entasis_world_t * world, entasis_constraint_type_id_t type_id, const entasis_body_handle_t * bodies, uint32_t body_count, const void * description, uint32_t description_size, entasis_constraint_handle_t * out_handle, entasis_diagnostic_t * diagnostic);

/**
 * copies one custom constraint description
 *
 * preserves the native active/sleeping description semantics. buffers must not overlap other inputs. no output is promised on invalid usage
 *
 * @param world initialized world
 * @param handle existing constraint handle
 * @param type_id registered custom type ID
 * @param description 4-byte aligned output scalar storage
 * @param description_size must match the registered size
 * @param diagnostic optional diagnostic output
 *
 * @return returns the operation status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_custom_constraint_get(entasis_world_t * world, entasis_constraint_handle_t handle, entasis_constraint_type_id_t type_id, void * description, uint32_t description_size, entasis_diagnostic_t * diagnostic);

/**
 * replaces one custom constraint description
 *
 * preserves the native active/sleeping description semantics. buffers must not overlap other inputs. validation failure does not apply the new description
 *
 * @param world initialized world
 * @param handle existing constraint handle
 * @param type_id registered custom type ID
 * @param description 4-byte aligned input scalar storage
 * @param description_size must match the registered size
 * @param diagnostic optional diagnostic output
 *
 * @return returns the operation status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_custom_constraint_apply(entasis_world_t * world, entasis_constraint_handle_t handle, entasis_constraint_type_id_t type_id, const void * description, uint32_t description_size, entasis_diagnostic_t * diagnostic);

/**
 * adds a strided batch of custom constraints
 *
 * stops at first failure. successful prefix handles are valid, failing slot is invalid, later slots are untouched. empty batches accept NULL buffers. no rollback or implicit allocation of adapter arrays
 *
 * @param world initialized world
 * @param type_id registered custom type ID
 * @param bodies flattened body handles, body_count per item
 * @param body_handle_count exactly count times the registered arity
 * @param descriptions 4-byte aligned strided scalar inputs
 * @param description_stride at least the registered size and divisible by four
 * @param count number of items. buffers must have this capacity
 * @param out_handles count outputs, not overlapping inputs
 * @param out_completed required successful prefix count, zero on preflight failure
 * @param diagnostic optional diagnostic output
 *
 * @return returns the operation status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_custom_constraint_add_batch(entasis_world_t * world, entasis_constraint_type_id_t type_id, const entasis_body_handle_t * bodies, uint64_t body_handle_count, const void * descriptions, uint64_t description_stride, uint64_t count, entasis_constraint_handle_t * out_handles, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * copies strided custom descriptions
 *
 * stops at the first error with the successful prefix count. input/output buffers must not overlap. empty batches accept NULL buffers. existing removal and inspection APIs also support these handles
 *
 * @param world initialized world
 * @param type_id registered custom type ID
 * @param handles count existing handles
 * @param count number of items. buffers must have this capacity
 * @param descriptions 4-byte aligned strided outputs
 * @param description_stride at least the registered size and divisible by four
 * @param out_completed required successful prefix count, zero on preflight failure
 * @param diagnostic optional diagnostic output
 *
 * @return returns the operation status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_custom_constraint_get_batch(entasis_world_t * world, entasis_constraint_type_id_t type_id, const entasis_constraint_handle_t * handles, uint64_t count, void * descriptions, uint64_t description_stride, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * applies strided custom descriptions
 *
 * stops at the first error with the successful prefix count. input/output buffers must not overlap. empty batches accept NULL buffers. existing removal and inspection APIs also support these handles
 *
 * @param world initialized world
 * @param type_id registered custom type ID
 * @param handles count existing handles
 * @param count number of items. buffers must have this capacity
 * @param descriptions 4-byte aligned strided inputs
 * @param description_stride at least the registered size and divisible by four
 * @param out_completed required successful prefix count, zero on preflight failure
 * @param diagnostic optional diagnostic output
 *
 * @return returns the operation status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_custom_constraint_apply_batch(entasis_world_t * world, entasis_constraint_type_id_t type_id, const entasis_constraint_handle_t * handles, uint64_t count, const void * descriptions, uint64_t description_stride, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * enables optional watched-joint breaking
 *
 * @param world idle world without joint breaks
 * @param watch_capacity positive initial watch capacity
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK or the original failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_enable_joint_breaks(entasis_world_t * world, int32_t watch_capacity, entasis_diagnostic_t * diagnostic);

/**
 * disables joint breaks after pending delivery is acknowledged
 *
 * ends provider borrowing and releases optional watch storage
 *
 * @param world idle world with joint breaks enabled
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK or the original failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_disable_joint_breaks(entasis_world_t * world, entasis_diagnostic_t * diagnostic);

/**
 * reserves watched-joint storage outside stepping
 *
 * @param world idle world with joint breaks enabled
 * @param watch_capacity positive capacity to reserve
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK or the original failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_joint_break_reserve(entasis_world_t * world, int32_t watch_capacity, entasis_diagnostic_t * diagnostic);

/**
 * sets the explicit custom physical-reaction provider
 *
 * registration cannot change while the type has watches. rejected registration preserves the previous provider
 *
 * @param world idle world with joint breaks enabled
 * @param type_id custom type registered in this world
 * @param provider descriptor copied on success, NULL clears the provider
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK or the original failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_constraint_set_reaction_provider(entasis_world_t * world, entasis_constraint_type_id_t type_id, const entasis_joint_reaction_provider_t * provider, entasis_diagnostic_t * diagnostic);

/**
 * sets or replaces the watched limits
 *
 * zero metric flags cancel the watch without removing the constraint. enabled metrics compare strict greater-than physical force or torque
 *
 * @param world idle world with joint breaks enabled
 * @param constraint live constraint handle
 * @param limits copied limits with reserved zero
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK or the original failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_constraint_set_break_limits(entasis_world_t * world, entasis_constraint_handle_t constraint, const entasis_joint_break_limits_t * limits, entasis_diagnostic_t * diagnostic);

/**
 * reads the current watched limits
 *
 * @param world live world with joint breaks, idle or within an explicit read phase
 * @param constraint live constraint handle
 * @param out_limits written only on success
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK or the original failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_constraint_get_break_limits(entasis_world_t * world, entasis_constraint_handle_t constraint, entasis_joint_break_limits_t * out_limits, entasis_diagnostic_t * diagnostic);

/**
 * cancels a watch without threshold removal
 *
 * @param world idle world with joint breaks enabled
 * @param constraint live constraint handle
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK or the original failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_constraint_clear_break_limits(entasis_world_t * world, entasis_constraint_handle_t constraint, entasis_diagnostic_t * diagnostic);

/**
 * reads the last committed watched reaction
 *
 * sleeping joints do not acquire fresh force from cached impulses. inspect state and step to distinguish an older sample
 *
 * @param world live world with joint breaks, idle or within an explicit read phase
 * @param constraint live constraint handle
 * @param out_reaction written only on success
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK or the original failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_constraint_reaction(entasis_world_t * world, entasis_constraint_handle_t constraint, entasis_joint_reaction_t * out_reaction, entasis_diagnostic_t * diagnostic);

/**
 * drains one immutable break batch
 *
 * short capacity writes no events and permits retry. pending publication may awaken and remove crossed joints, invalidating borrowed world views
 *
 * @param world idle world with joint breaks enabled
 * @param output caller-owned output, NULL only at zero capacity
 * @param capacity output element capacity
 * @param out_written receives copied element count
 * @param out_required receives required element count
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK or the original failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_constraint_break_events_drain(entasis_world_t * world, entasis_joint_break_event_t * output, uint64_t capacity, uint64_t * out_written, uint64_t * out_required, entasis_diagnostic_t * diagnostic);

/**
 * acknowledges pending breaks without copying events
 *
 * retries pending publication before discarding. allocation failure retains pending state
 *
 * @param world idle world with joint breaks enabled
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK or the original failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_constraint_break_events_discard(entasis_world_t * world, entasis_diagnostic_t * diagnostic);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* ENTASIS_CONSTRAINTS_H */
