// generated by tools/abi/generate_abi. do not edit
#ifndef ENTASIS_COOKING_H
#define ENTASIS_COOKING_H

#include <entasis/shapes.h>

#if defined(_WIN32)
#  define ENTASIS_COOKING_CALL __cdecl
#  if defined(ENTASIS_COOKING_BUILD_SHARED)
#    define ENTASIS_COOKING_API __declspec(dllexport)
#  elif defined(ENTASIS_COOKING_USE_SHARED)
#    define ENTASIS_COOKING_API __declspec(dllimport)
#  else
#    define ENTASIS_COOKING_API
#  endif
#elif defined(__GNUC__) || defined(__clang__)
#  define ENTASIS_COOKING_CALL
#  define ENTASIS_COOKING_API __attribute__((visibility("default")))
#else
#  define ENTASIS_COOKING_CALL
#  define ENTASIS_COOKING_API
#endif

#ifdef __cplusplus
extern "C" {
#endif

#define ENTASIS_COOKING_ABI_VERSION UINT32_C(1)

/**
 * opaque caller-owned cooking context kept at a stable address while assets are live
 */
struct entasis_cooking_context_t {
    /* internal cooking context state managed by Entasis */
    void * opaque;
};

/**
 * returns the cooking C ABI generation used by this library
 *
 * @return returns ENTASIS_COOKING_ABI_VERSION for a compatible cooking library
 */
ENTASIS_COOKING_API uint32_t ENTASIS_COOKING_CALL entasis_cooking_abi_version(void);

/**
 * builds a portable tree-accelerated compound from caller-provided child bounds
 *
 * child bounds are supplied by the asset pipeline
 *
 * @param context target cooking context
 * @param children input cooked big compound child array
 * @param count number of entries in the input arrays
 * @param out_cooked receives the cooked big compound
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_COOKING_API entasis_status_t ENTASIS_COOKING_CALL entasis_cook_big_compound(entasis_cooking_context_t * context, const entasis_cooked_big_compound_child_t * children, uint64_t count, entasis_cooked_big_compound_t * out_cooked, entasis_diagnostic_t * diagnostic);

/**
 * copies portable compound children into a cooking-context-owned asset
 *
 * import maps each slot through a caller-provided shape-handle table
 *
 * @param context target cooking context
 * @param children input cooked compound child array
 * @param count number of entries in the input arrays
 * @param out_cooked receives the cooked compound
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_COOKING_API entasis_status_t ENTASIS_COOKING_CALL entasis_cook_compound(entasis_cooking_context_t * context, const entasis_cooked_compound_child_t * children, uint64_t count, entasis_cooked_compound_t * out_cooked, entasis_diagnostic_t * diagnostic);

/**
 * builds immutable convex hull data from a caller-provided point cloud
 *
 * safe on a background worker when the context and input are owned by that worker
 *
 * @param context target cooking context
 * @param points input point cloud
 * @param count number of entries in the input arrays
 * @param out_cooked receives the cooked hull
 * @param out_center receives the computed center of mass
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_COOKING_API entasis_status_t ENTASIS_COOKING_CALL entasis_cook_hull(entasis_cooking_context_t * context, const entasis_vector3_t * points, uint64_t count, entasis_cooked_hull_t * out_cooked, entasis_vector3_t * out_center, entasis_diagnostic_t * diagnostic);

/**
 * builds immutable mesh data and its bounds tree from caller-provided triangles
 *
 * @param context target cooking context
 * @param triangles input triangle array
 * @param count number of entries in the input arrays
 * @param scale per-axis mesh scale
 * @param out_cooked receives the cooked mesh
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_COOKING_API entasis_status_t ENTASIS_COOKING_CALL entasis_cook_mesh(entasis_cooking_context_t * context, const entasis_triangle_t * triangles, uint64_t count, entasis_vector3_t scale, entasis_cooked_mesh_t * out_cooked, entasis_diagnostic_t * diagnostic);

/**
 * releases a cooked big compound and returns its storage to the owning cooking context
 *
 * @param cooked target cooked asset
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_COOKING_API entasis_status_t ENTASIS_COOKING_CALL entasis_cooked_big_compound_destroy(entasis_cooked_big_compound_t * cooked, entasis_diagnostic_t * diagnostic);

/**
 * maps cooked big-compound child slots and imports its prepared tree into a world
 *
 * @param world target world
 * @param cooked target cooked asset
 * @param shape_slots shape handles indexed by cooked child shape slot
 * @param shape_slot_count number of entries in the shape slot table
 * @param out_handle receives the created shape handle
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_COOKING_API entasis_status_t ENTASIS_COOKING_CALL entasis_cooked_big_compound_import(entasis_world_t * world, const entasis_cooked_big_compound_t * cooked, const entasis_shape_handle_t * shape_slots, uint64_t shape_slot_count, entasis_shape_handle_t * out_handle, entasis_diagnostic_t * diagnostic);

/**
 * releases a cooked compound and returns its storage to the owning cooking context
 *
 * @param cooked target cooked asset
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_COOKING_API entasis_status_t ENTASIS_COOKING_CALL entasis_cooked_compound_destroy(entasis_cooked_compound_t * cooked, entasis_diagnostic_t * diagnostic);

/**
 * maps cooked compound child slots through a shape table and imports the result
 *
 * @param world target world
 * @param cooked target cooked asset
 * @param shape_slots shape handles indexed by cooked child shape slot
 * @param shape_slot_count number of entries in the shape slot table
 * @param out_handle receives the created shape handle
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_COOKING_API entasis_status_t ENTASIS_COOKING_CALL entasis_cooked_compound_import(entasis_world_t * world, const entasis_cooked_compound_t * cooked, const entasis_shape_handle_t * shape_slots, uint64_t shape_slot_count, entasis_shape_handle_t * out_handle, entasis_diagnostic_t * diagnostic);

/**
 * releases a cooked hull and returns its storage to the owning cooking context
 *
 * @param cooked target cooked asset
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_COOKING_API entasis_status_t ENTASIS_COOKING_CALL entasis_cooked_hull_destroy(entasis_cooked_hull_t * cooked, entasis_diagnostic_t * diagnostic);

/**
 * imports a ready cooked hull into a live world as a registered shape
 *
 * @param world target world
 * @param cooked target cooked asset
 * @param out_handle receives the created shape handle
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_COOKING_API entasis_status_t ENTASIS_COOKING_CALL entasis_cooked_hull_import(entasis_world_t * world, const entasis_cooked_hull_t * cooked, entasis_shape_handle_t * out_handle, entasis_diagnostic_t * diagnostic);

/**
 * validates a ready cooked hull and its internal topology
 *
 * @param cooked target cooked asset
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_COOKING_API entasis_status_t ENTASIS_COOKING_CALL entasis_cooked_hull_validate(const entasis_cooked_hull_t * cooked);

/**
 * computes closed-solid mass properties for a cooked mesh
 *
 * when recenter is true, the cooked mesh geometry and acceleration tree are shifted so the returned center becomes the body pose offset
 *
 * @param cooked target cooked asset
 * @param mass positive mass used to compute inertia or mass properties
 * @param recenter whether geometry is shifted around the computed center of mass
 * @param out_properties receives the mesh mass properties
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_COOKING_API entasis_status_t ENTASIS_COOKING_CALL entasis_cooked_mesh_closed_mass_properties(entasis_cooked_mesh_t * cooked, float mass, entasis_bool_t recenter, entasis_mesh_mass_properties_t * out_properties, entasis_diagnostic_t * diagnostic);

/**
 * releases a cooked mesh and returns its storage to the owning cooking context
 *
 * @param cooked target cooked asset
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_COOKING_API entasis_status_t ENTASIS_COOKING_CALL entasis_cooked_mesh_destroy(entasis_cooked_mesh_t * cooked, entasis_diagnostic_t * diagnostic);

/**
 * imports a ready cooked mesh into a live world as a registered shape
 *
 * @param world target world
 * @param cooked target cooked asset
 * @param out_handle receives the created shape handle
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_COOKING_API entasis_status_t ENTASIS_COOKING_CALL entasis_cooked_mesh_import(entasis_world_t * world, const entasis_cooked_mesh_t * cooked, entasis_shape_handle_t * out_handle, entasis_diagnostic_t * diagnostic);

/**
 * computes triangle-soup mass properties for a cooked mesh
 *
 * @param cooked target cooked asset
 * @param mass positive mass used to compute inertia or mass properties
 * @param recenter whether geometry is shifted around the computed center of mass
 * @param out_properties receives the mesh mass properties
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_COOKING_API entasis_status_t ENTASIS_COOKING_CALL entasis_cooked_mesh_open_mass_properties(entasis_cooked_mesh_t * cooked, float mass, entasis_bool_t recenter, entasis_mesh_mass_properties_t * out_properties, entasis_diagnostic_t * diagnostic);

/**
 * releases cooking pool blocks while retaining context metadata
 *
 * all assets must be destroyed first
 *
 * @param context target cooking context
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_COOKING_API entasis_status_t ENTASIS_COOKING_CALL entasis_cooking_context_clear(entasis_cooking_context_t * context, entasis_diagnostic_t * diagnostic);

/**
 * destroys an idle cooking context after all cooked assets are released
 *
 * all assets must be destroyed first
 *
 * @param context target cooking context
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_COOKING_API entasis_status_t ENTASIS_COOKING_CALL entasis_cooking_context_destroy(entasis_cooking_context_t * context, entasis_diagnostic_t * diagnostic);

/**
 * initializes one caller-owned cooking context
 *
 * @param context target cooking context
 * @param minimum_block_size minimum native block size in bytes
 * @param expected_resource_count expected number of retained resources
 * @param allocator copied allocator callbacks for storage covered by the selected allocation scope. user_context remains borrowed until destruction
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_COOKING_API entasis_status_t ENTASIS_COOKING_CALL entasis_cooking_context_init(entasis_cooking_context_t * context, int32_t minimum_block_size, int32_t expected_resource_count, const entasis_allocator_t * allocator, entasis_diagnostic_t * diagnostic);

/**
 * initializes one caller-owned cooking context with explicit Legacy/All_Owned allocation scope. allocator callbacks and user data remain alive through resource destruction
 *
 * @param context target cooking context
 * @param minimum_block_size minimum native block size in bytes
 * @param expected_resource_count expected number of retained resources
 * @param allocator copied allocator callbacks for storage covered by the selected allocation scope. user_context remains borrowed until destruction
 * @param allocation_scope Legacy preserves existing behavior. All_Owned includes pool metadata, native blocks and included thread records
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_COOKING_API entasis_status_t ENTASIS_COOKING_CALL entasis_cooking_context_init_extended(entasis_cooking_context_t * context, int32_t minimum_block_size, int32_t expected_resource_count, const entasis_allocator_t * allocator, entasis_allocation_scope_t allocation_scope, entasis_diagnostic_t * diagnostic);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* ENTASIS_COOKING_H */
