// generated by tools/abi/generate_abi. do not edit
#ifndef ENTASIS_EVENTS_H
#define ENTASIS_EVENTS_H

#include <entasis/constraints.h>
#include <entasis/queries.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * caller-owned contact pair history
 */
struct entasis_contact_tracker_t {
    /* internal contact tracker state managed by Entasis */
    void * opaque;
};

/**
 * generation-aware collidable-to-caller-ID table
 */
struct entasis_contact_user_table_t {
    /* internal contact user table state managed by Entasis */
    void * opaque;
};

/**
 * optional trigger capacities. use entasis_trigger_configuration_default
 */
struct entasis_trigger_configuration_t {
    /* size of this structure */
    uint32_t struct_size;
    /* must be 1 */
    uint32_t struct_version;
    /* retained unique parent-pair capacity */
    int32_t pair_capacity;
    /* broad-phase candidate capacity per worker */
    int32_t candidates_per_worker;
    /* compound child collision scratch capacity per worker */
    int32_t child_capacity;
};

/**
 * per-collidable sensor settings. zero initialization enables Enter and Exit only
 */
struct entasis_trigger_settings_t {
    /* application value captured in events */
    uint64_t user_id;
    /* emit Stay for retained pairs */
    entasis_bool_t stay;
    /* include static/static overlaps */
    entasis_bool_t static_static;
    /* must be zero */
    uint8_t reserved[6];
};

/**
 * backpressure-aware fixed-step result. completed time is never repeated
 */
struct entasis_trigger_update_result_t {
    /* physics steps consumed by this call */
    int32_t completed_steps;
    /* events copied into the caller array */
    int32_t events_written;
    /* capacity required for the pending batch */
    int32_t required;
    /* interpolation fraction, clamped while backlog is pending */
    float alpha;
    /* a batch or notification error prevents advancing */
    entasis_bool_t notification_pending;
    /* reserved. zero */
    uint8_t reserved[3];
};

/**
 * sparse part capacities. does not enable whole-trigger mode
 */
struct entasis_collider_part_configuration_t {
    /* size of this structure */
    uint32_t struct_size;
    /* must be one */
    uint32_t struct_version;
    /* configured and observed live instances */
    int32_t instance_capacity;
    /* configured and observed live part identities */
    int32_t part_capacity;
    /* retained unique part pairs */
    int32_t pair_capacity;
    /* geometric part observations before deduplication */
    int32_t observations_per_worker;
    /* fixed until trigger storage is destroyed */
    entasis_collider_part_subscription_t event_subscription;
    /* must be zero */
    uint8_t reserved[3];
};

/**
 * per-instance part override. unspecified parts are solid
 */
struct entasis_collider_part_settings_t {
    /* application identifier copied into events */
    uint64_t user_id;
    /* Solid or non-solving trigger */
    entasis_collider_part_role_t role;
    /* stay and static/static option bits */
    entasis_collider_part_options_t options;
    /* must be zero */
    uint8_t reserved[6];
};

/**
 * lifetime-qualified top-level part identity
 */
struct entasis_collider_part_identity_t {
    /* owning instance lifetime */
    uint64_t instance;
    /* shape binding lifetime */
    uint64_t incarnation;
    /* part lifetime serial */
    uint64_t serial;
    /* top-level child or zero for a root shape */
    int32_t child_index;
    /* zero */
    uint32_t reserved;
};

/**
 * completed time and output counts for both notification streams
 */
struct entasis_collider_part_update_result_t {
    /* physics steps consumed exactly once */
    int32_t completed_steps;
    /* parent events copied */
    int32_t events_written;
    /* part events copied */
    int32_t part_events_written;
    /* exact pending parent batch size, zero after success */
    int32_t required;
    /* exact pending part batch size, zero after success */
    int32_t part_required;
    /* clamped interpolation fraction */
    float alpha;
    /* pending stream bits */
    entasis_collider_part_pending_t pending;
    /* zero */
    uint8_t reserved[3];
};

/**
 * completed time and independently delivered contact/trigger output. no completed step is replayed
 */
struct entasis_collider_part_contact_update_result_t {
    /* physics steps consumed exactly once */
    int32_t completed_steps;
    /* parent events copied */
    int32_t events_written;
    /* part events copied */
    int32_t part_events_written;
    /* contact events copied and acknowledged in this call */
    int32_t contact_events_written;
    /* exact pending parent batch size, zero after success */
    int32_t required;
    /* exact pending part batch size, zero after success */
    int32_t part_required;
    /* pending contact output count, or required pair capacity when tracker storage is insufficient. zero after delivery */
    int32_t contact_required;
    /* clamped interpolation fraction */
    float alpha;
    /* pending stream bits */
    entasis_collider_part_pending_t pending;
    /* zero */
    uint8_t reserved[3];
};

/**
 * completed time and pending output for the combined stepper
 */
struct entasis_joint_break_update_result_t {
    /* physics steps consumed once by this call */
    int32_t completed_steps;
    /* parent trigger events copied */
    int32_t events_written;
    /* part trigger events copied */
    int32_t part_events_written;
    /* contact events copied */
    int32_t contact_events_written;
    /* break events copied */
    int32_t break_events_written;
    /* required capacity for the pending parent batch */
    int32_t required;
    /* required capacity for the pending part batch */
    int32_t part_required;
    /* required contact output or tracker history capacity */
    int32_t contact_required;
    /* required capacity for the pending break batch */
    int32_t break_required;
    /* interpolation fraction clamped to zero through one */
    float alpha;
    /* streams preventing another physics step */
    entasis_joint_break_pending_t pending;
    /* zero */
    uint8_t reserved[3];
};

/**
 * a geometrically intersecting parent pair, not a solver constraint
 */
struct entasis_trigger_pair_t {
    /* first collidable snapshot */
    entasis_collidable_reference_t a;
    /* second collidable snapshot */
    entasis_collidable_reference_t b;
    /* world-local lifetime token for A */
    uint64_t token_a;
    /* world-local lifetime token for B */
    uint64_t token_b;
    /* trigger application value for A, or zero */
    uint64_t user_a;
    /* trigger application value for B, or zero */
    uint64_t user_b;
    /* bits 1/2 indicate trigger A/B. bit 4 requests Stay */
    uint32_t flags;
    /* reserved. zero */
    uint32_t reserved;
};

/**
 * copied configured part identity and settings
 */
struct entasis_collider_part_info_t {
    /* lifetime-qualified identity */
    entasis_collider_part_identity_t identity;
    /* copied settings */
    entasis_collider_part_settings_t settings;
};

/**
 * pointer-free observed endpoint. retained after deletion
 */
struct entasis_collider_part_endpoint_t {
    /* original collidable reference, not a durable lookup after removal */
    entasis_collidable_reference_t reference;
    /* top-level part index */
    int32_t child_index;
    /* instance lifetime */
    uint64_t instance;
    /* shape lifetime */
    uint64_t incarnation;
    /* part serial */
    uint64_t serial;
    /* captured application ID */
    uint64_t user_id;
};

/**
 * buffered pointer-free discrete trigger event. output is copied atomically on drain
 */
struct entasis_trigger_event_t {
    /* lifetime-safe collidable pair snapshot */
    entasis_trigger_pair_t pair;
    /* completed simulation step index */
    uint64_t step;
    /* trigger owner epoch */
    uint64_t epoch;
    /* Enter, Stay or Exit */
    entasis_trigger_event_kind_t kind;
    /* Exit reason. separation for non-exit events */
    entasis_trigger_exit_reason_t reason;
};

/**
 * canonical lifetime-qualified part pair
 */
struct entasis_collider_part_pair_t {
    /* first endpoint */
    entasis_collider_part_endpoint_t a;
    /* second endpoint */
    entasis_collider_part_endpoint_t b;
    /* uses the existing trigger pair A/B/Stay bits */
    uint32_t flags;
    /* zero */
    uint32_t reserved;
};

/**
 * one owner-thread contact pair transition
 */
struct entasis_contact_event_t {
    /* active tagged variant */
    entasis_contact_event_kind_t kind;
    /* number of valid contacts */
    uint8_t contact_count;
    /* bit set describing optional event data */
    entasis_contact_event_flags_t flags;
    /* reserved for ABI compatibility */
    uint8_t reserved0;
    /* collidable A */
    entasis_collidable_reference_t a;
    /* collidable B */
    entasis_collidable_reference_t b;
    /* contact or hit normal */
    entasis_vector3_t normal;
    /* caller ID for collidable A when available */
    uint64_t user_a;
    /* caller ID for collidable B when available */
    uint64_t user_b;
    /* constraint handle */
    entasis_constraint_handle_t constraint;
    /* pointer-free solver contact data captured for the event */
    entasis_solver_contact_data_t contact_data;
    /* reserved for ABI compatibility */
    uint8_t reserved1[4];
};

/**
 * immutable part transition sharing the parent stream step
 */
struct entasis_collider_part_event_t {
    /* captured part pair */
    entasis_collider_part_pair_t pair;
    /* completed physics step */
    uint64_t step;
    /* trigger history epoch */
    uint64_t epoch;
    /* enter, Stay or Exit */
    entasis_trigger_event_kind_t kind;
    /* exit reason */
    entasis_trigger_exit_reason_t reason;
};

/**
 * initializes generation-aware contact user identifiers
 *
 * @param table target contact user table
 * @param body_capacity required body namespace capacity
 * @param static_capacity required static namespace capacity
 * @param allocator copied allocator callbacks for storage covered by the selected allocation scope. user_context remains borrowed until destruction
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_contact_user_table_init(entasis_contact_user_table_t * table, uint64_t body_capacity, uint64_t static_capacity, const entasis_allocator_t * allocator, entasis_diagnostic_t * diagnostic);

/**
 * grows contact user identifier storage
 *
 * @param table target contact user table
 * @param body_capacity required body namespace capacity
 * @param static_capacity required static namespace capacity
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_contact_user_table_ensure_capacity(entasis_contact_user_table_t * table, uint64_t body_capacity, uint64_t static_capacity, entasis_diagnostic_t * diagnostic);

/**
 * associates a user identifier with a body property lifetime
 *
 * @param table target contact user table
 * @param handle target body handle
 * @param user_id caller-selected stable collidable ID
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_contact_user_set_body(entasis_contact_user_table_t * table, entasis_body_handle_t handle, uint64_t user_id, entasis_diagnostic_t * diagnostic);

/**
 * associates a user identifier with a static property lifetime
 *
 * @param table target contact user table
 * @param handle target static handle
 * @param user_id caller-selected stable collidable ID
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_contact_user_set_static(entasis_contact_user_table_t * table, entasis_static_handle_t handle, uint64_t user_id, entasis_diagnostic_t * diagnostic);

/**
 * ends one body user identifier lifetime
 *
 * @param table target contact user table
 * @param handle target body handle
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_contact_user_remove_body(entasis_contact_user_table_t * table, entasis_body_handle_t handle, entasis_diagnostic_t * diagnostic);

/**
 * ends one static user identifier lifetime
 *
 * @param table target contact user table
 * @param handle target static handle
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_contact_user_remove_static(entasis_contact_user_table_t * table, entasis_static_handle_t handle, entasis_diagnostic_t * diagnostic);

/**
 * clears contact user identifiers while retaining storage
 *
 * @param table target contact user table
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_contact_user_table_clear(entasis_contact_user_table_t * table, entasis_diagnostic_t * diagnostic);

/**
 * destroys contact user identifier storage
 *
 * @param table target contact user table
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_contact_user_table_destroy(entasis_contact_user_table_t * table, entasis_diagnostic_t * diagnostic);

/**
 * initializes caller-owned contact pair history
 *
 * initial_capacity is the maximum simultaneously retained pair count before explicit growth
 *
 * @param tracker target contact tracker
 * @param initial_capacity initial retained capacity
 * @param allocator copied allocator callbacks for storage covered by the selected allocation scope. user_context remains borrowed until destruction
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_contact_tracker_init(entasis_contact_tracker_t * tracker, uint64_t initial_capacity, const entasis_allocator_t * allocator, entasis_diagnostic_t * diagnostic);

/**
 * returns retained contact pair capacity
 *
 * @param tracker target contact tracker
 *
 * @return returns the retained capacity
 */
ENTASIS_API uint64_t ENTASIS_CALL entasis_contact_tracker_capacity(const entasis_contact_tracker_t * tracker);

/**
 * grows contact pair history
 *
 * existing pair lifetimes and the current binding are preserved
 *
 * @param tracker target contact tracker
 * @param required_capacity required retained capacity
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_contact_tracker_ensure_capacity(entasis_contact_tracker_t * tracker, uint64_t required_capacity, entasis_diagnostic_t * diagnostic);

/**
 * binds contact history to one world and optional user table
 *
 * binding begins a new event history. the first successfully drained step reports begin for every retained pair
 *
 * @param tracker target contact tracker
 * @param world target world
 * @param users optional contact user table bound to the tracker
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_contact_tracker_bind(entasis_contact_tracker_t * tracker, entasis_world_t * world, entasis_contact_user_table_t * users, entasis_diagnostic_t * diagnostic);

/**
 * clears contact history while retaining binding and capacity
 *
 * the next completed step begins a new event stream
 *
 * @param tracker target contact tracker
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_contact_tracker_clear(entasis_contact_tracker_t * tracker, entasis_diagnostic_t * diagnostic);

/**
 * unbinds contact history from its world
 *
 * the tracker may then bind to another world
 *
 * @param tracker target contact tracker
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_contact_tracker_unbind(entasis_contact_tracker_t * tracker, entasis_diagnostic_t * diagnostic);

/**
 * destroys contact pair history
 *
 * destroy or unbind the tracker before destroying the bound world
 *
 * @param tracker target contact tracker
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_contact_tracker_destroy(entasis_contact_tracker_t * tracker, entasis_diagnostic_t * diagnostic);

/**
 * drains one completed step of pair lifetime events
 *
 * it performs no global ordering pass. on ENTASIS_STATUS_CAPACITY_MISSING no history is committed and the call may be retried with a larger output slice or after entasis_contact_tracker_ensure_capacity
 *
 * @param tracker target contact tracker
 * @param events caller-owned contact event output array
 * @param capacity number of entries available in the output array
 * @param out_written receives the number of output entries written
 * @param out_required receives the total required output capacity
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_contact_events_drain(entasis_contact_tracker_t * tracker, entasis_contact_event_t * events, uint64_t capacity, uint64_t * out_written, uint64_t * out_required, entasis_diagnostic_t * diagnostic);

/**
 * commits and discards one completed step of events
 *
 * it is useful when a frame intentionally ignores contact notifications. on ENTASIS_STATUS_CAPACITY_MISSING history is not committed
 *
 * @param tracker target contact tracker
 * @param out_required receives the total required output capacity
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_contact_events_discard(entasis_contact_tracker_t * tracker, uint64_t * out_required, entasis_diagnostic_t * diagnostic);

/**
 * constructs version 1 trigger capacities
 *
 * @return returns the default configuration
 */
ENTASIS_API entasis_trigger_configuration_t ENTASIS_CALL entasis_trigger_configuration_default(void);

/**
 * enables optional non-solving collidables
 *
 * no trigger allocations or trigger worker execute in a world that has never enabled triggers. enabled triggers use private worker scratch and existing geometry kernels. NULL configuration selects defaults
 *
 * @param world idle target world
 * @param configuration configuration from the default constructor
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_enable_triggers(entasis_world_t * world, const entasis_trigger_configuration_t * configuration, entasis_diagnostic_t * diagnostic);

/**
 * disables triggers and releases optional resources
 *
 * drain or explicitly discard a nonempty pending event batch first. existing collidables become solid. explicit joints are unaffected
 *
 * @param world idle target world
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_disable_triggers(entasis_world_t * world, entasis_diagnostic_t * diagnostic);

/**
 * reserves trigger capacity without shrinking
 *
 * identical and smaller capacity requests reuse storage. a failed growth preserves committed history and existing resources
 *
 * @param world idle target world
 * @param configuration configuration from the default constructor
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_trigger_reserve(entasis_world_t * world, const entasis_trigger_configuration_t * configuration, entasis_diagnostic_t * diagnostic);

/**
 * marks one collidable as non-solving
 *
 * sensor mode belongs to the instance, not its shared shape. existing contact constraints are removed. explicit joints remain. detection filters apply, material/solver callbacks do not. reentry and read-phase mutation are rejected
 *
 * @param world idle target world
 * @param reference target collidable instance
 * @param settings settings, or NULL for Enter/Exit defaults
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_trigger_set(entasis_world_t * world, entasis_collidable_reference_t reference, const entasis_trigger_settings_t * settings, entasis_diagnostic_t * diagnostic);

/**
 * reads current sensor settings
 *
 * @param world idle target world
 * @param reference target collidable instance
 * @param out_settings receives current settings
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_trigger_get(entasis_world_t * world, entasis_collidable_reference_t reference, entasis_trigger_settings_t * out_settings, entasis_diagnostic_t * diagnostic);

/**
 * removes sensor mode without removing the collidable
 *
 * @param world idle target world
 * @param reference target collidable instance
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_trigger_remove(entasis_world_t * world, entasis_collidable_reference_t reference, entasis_diagnostic_t * diagnostic);

/**
 * notifies supported direct geometry edits on one collidable
 *
 * @param world idle target world
 * @param reference target collidable instance
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_trigger_mark_geometry_dirty(entasis_world_t * world, entasis_collidable_reference_t reference, entasis_diagnostic_t * diagnostic);

/**
 * invalidates trigger detection after application filter-policy changes
 *
 * @param world idle target world
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_trigger_mark_filters_dirty(entasis_world_t * world, entasis_diagnostic_t * diagnostic);

/**
 * discards history and notification errors while keeping registrations and capacity
 *
 * @param world idle target world
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_trigger_reset_history(entasis_world_t * world, entasis_diagnostic_t * diagnostic);

/**
 * explicitly acknowledges a pending event batch without copying it
 *
 * @param world idle target world
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_trigger_events_discard(entasis_world_t * world, entasis_diagnostic_t * diagnostic);

/**
 * drains one completed immutable batch
 *
 * insufficient capacity writes no elements, returns CAPACITY_MISSING and permits retry without repeating physics. events sample the collision phase, not continuous crossings or post-solve containment
 *
 * @param world idle target world
 * @param output caller-owned output array, NULL only at zero capacity
 * @param capacity output element capacity
 * @param out_written receives elements copied
 * @param out_required receives exact required element count
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_trigger_events_drain(entasis_world_t * world, entasis_trigger_event_t * output, uint64_t capacity, uint64_t * out_written, uint64_t * out_required, entasis_diagnostic_t * diagnostic);

/**
 * copies the current committed parent-pair set
 *
 * insufficient capacity writes no elements, returns CAPACITY_MISSING and permits retry without repeating physics. events sample the collision phase, not continuous crossings or post-solve containment
 *
 * @param world idle target world
 * @param output caller-owned output array, NULL only at zero capacity
 * @param capacity output element capacity
 * @param out_written receives elements copied
 * @param out_required receives exact required element count
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_trigger_overlaps(entasis_world_t * world, entasis_trigger_pair_t * output, uint64_t capacity, uint64_t * out_written, uint64_t * out_required, entasis_diagnostic_t * diagnostic);

/**
 * advances fixed steps with retriable notification backpressure
 *
 * stops on a pending event batch, retaining unconsumed accumulator time. calls returning a completed step have already consumed that physics time even if drain reports CAPACITY_MISSING. contact tracker events are a separate explicitly drained stream
 *
 * @param stepper caller-owned stepper
 * @param world idle target world
 * @param elapsed elapsed time added once
 * @param output caller-owned event output
 * @param capacity output event capacity
 * @param out_result receives completed steps and pending state
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_trigger_stepper_update(entasis_fixed_stepper_t * stepper, entasis_world_t * world, float elapsed, entasis_trigger_event_t * output, uint64_t capacity, entasis_trigger_update_result_t * out_result, entasis_diagnostic_t * diagnostic);

/**
 * copies an endpoint application ID without changing solid or sensor mode
 *
 * the ID is copied into subsequent retained pair records. pending published batches remain unchanged. removing an endpoint clears the copied ID before its raw handle is reused
 *
 * @param world idle target world with triggers enabled
 * @param reference any live body or static endpoint
 * @param user_id application identity captured in future event snapshots
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK or a resolution/capacity failure
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_trigger_set_user_id(entasis_world_t * world, entasis_collidable_reference_t reference, uint64_t user_id, entasis_diagnostic_t * diagnostic);

/**
 * constructs sparse mixed-part defaults with part events disabled
 *
 * @return returns a copied default configuration
 */
ENTASIS_API entasis_collider_part_configuration_t ENTASIS_CALL entasis_collider_part_configuration_default(void);

/**
 * initializes or grows optional mixed-part storage
 *
 * enable triggers first. subscription cannot change after initialization. equal/smaller capacity is reused. no shared shape is changed
 *
 * @param world target world
 * @param configuration required size/version-tagged capacities
 * @param diagnostic optional diagnostic
 *
 * @return OK on success or the first failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collider_parts_reserve(entasis_world_t * world, const entasis_collider_part_configuration_t * configuration, entasis_diagnostic_t * diagnostic);

/**
 * sets a per-instance top-level part override
 *
 * native convex and mesh roots and registered Compound/Big_Compound hierarchies are supported. every nested descendant inherits its top-level child role. mesh triangles remain one mesh part, not independent parts. hierarchies are bounded to 32 nonconvex descendant levels. exhausted collision/query scratch reports capacity failure without publishing partial events. whole-trigger mode is mutually exclusive. role edits preserve the part serial. remove/rebind and shape replacement retire it
 *
 * @param world target world
 * @param reference collidable instance
 * @param child_index top-level child index
 * @param settings required copied settings
 * @param out_info receives the configured override on success
 * @param diagnostic optional diagnostic
 *
 * @return OK on success or the first failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collider_part_set(entasis_world_t * world, entasis_collidable_reference_t reference, int32_t child_index, const entasis_collider_part_settings_t * settings, entasis_collider_part_info_t * out_info, entasis_diagnostic_t * diagnostic);

/**
 * reads one configured part without changing its lifetime
 *
 * @param world target world
 * @param reference collidable instance
 * @param child_index top-level child index
 * @param out_info receives the configured override on success
 * @param diagnostic optional diagnostic
 *
 * @return OK on success or the first failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collider_part_get(entasis_world_t * world, entasis_collidable_reference_t reference, int32_t child_index, entasis_collider_part_info_t * out_info, entasis_diagnostic_t * diagnostic);

/**
 * removes an override and restores solid behavior
 *
 * @param world target world
 * @param reference collidable instance
 * @param child_index top-level child index
 * @param diagnostic optional diagnostic
 *
 * @return OK on success or the first failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collider_part_remove(entasis_world_t * world, entasis_collidable_reference_t reference, int32_t child_index, entasis_diagnostic_t * diagnostic);

/**
 * lists configured overrides ordered by child index
 *
 * insufficient output writes zero records and permits retry. output and count spans must be disjoint
 *
 * @param world target world
 * @param reference collidable instance
 * @param output caller-owned aligned output, NULL only at zero capacity
 * @param capacity output element capacity
 * @param out_written copied count
 * @param out_required exact required count
 * @param diagnostic optional diagnostic
 *
 * @return OK on success or the first failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collider_parts(entasis_world_t * world, entasis_collidable_reference_t reference, entasis_collider_part_info_t * output, uint64_t capacity, uint64_t * out_written, uint64_t * out_required, entasis_diagnostic_t * diagnostic);

/**
 * reads the committed part intersections
 *
 * insufficient output writes zero records and permits retry. output and count spans must be disjoint
 *
 * @param world target world
 * @param output caller-owned aligned output, NULL only at zero capacity
 * @param capacity output element capacity
 * @param out_written copied count
 * @param out_required exact required count
 * @param diagnostic optional diagnostic
 *
 * @return OK on success or the first failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_trigger_part_overlaps(entasis_world_t * world, entasis_collider_part_pair_t * output, uint64_t capacity, uint64_t * out_written, uint64_t * out_required, entasis_diagnostic_t * diagnostic);

/**
 * drains one immutable part batch without repeating physics
 *
 * insufficient output writes zero records and permits retry. output and count spans must be disjoint
 *
 * @param world target world
 * @param output caller-owned aligned output, NULL only at zero capacity
 * @param capacity output element capacity
 * @param out_written copied count
 * @param out_required exact required count
 * @param diagnostic optional diagnostic
 *
 * @return OK on success or the first failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_trigger_part_events_drain(entasis_world_t * world, entasis_collider_part_event_t * output, uint64_t capacity, uint64_t * out_written, uint64_t * out_required, entasis_diagnostic_t * diagnostic);

/**
 * acknowledges the part stream without discarding the parent batch
 *
 * @param world target world
 * @param diagnostic optional diagnostic
 *
 * @return OK on success or the first failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_trigger_part_events_discard(entasis_world_t * world, entasis_diagnostic_t * diagnostic);

/**
 * consumes each completed physics step once while delivering both trigger streams
 *
 * part event subscription is required. pending output is checked before either batch is acknowledged. distinct output arrays, stepper and result are required. this entry does not drain contact history. use entasis_collider_part_stepper_update_with_contacts when catch-up must also preserve a bound contact tracker
 *
 * @param stepper caller-owned accumulator
 * @param world target world
 * @param elapsed nonnegative elapsed time. use zero for delivery retry
 * @param output parent event output
 * @param capacity parent output capacity
 * @param part_output part event output
 * @param part_capacity part output capacity
 * @param out_result completed-time/output/pending result
 * @param diagnostic optional diagnostic
 *
 * @return OK on success or the first failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collider_part_stepper_update(entasis_fixed_stepper_t * stepper, entasis_world_t * world, float elapsed, entasis_trigger_event_t * output, uint64_t capacity, entasis_collider_part_event_t * part_output, uint64_t part_capacity, entasis_collider_part_update_result_t * out_result, entasis_diagnostic_t * diagnostic);

/**
 * drains contact and both trigger streams before each following fixed physics step
 *
 * part subscription is required. contact history is drained before trigger streams. delivered contacts remain delivered if a trigger batch is short. both trigger streams are acknowledged together. all pending streams block further physics. retry with elapsed zero. completed_steps never counts the same step twice. tracker capacity failure may require contact_tracker_ensure_capacity in addition to larger output. wrong-world, disposed or skipped-history trackers are rejected before accepting elapsed time. output arrays, result, stepper and handles must be disjoint. no allocation or automatic history reset occurs
 *
 * @param stepper caller-owned accumulator
 * @param world target world
 * @param elapsed nonnegative elapsed time. use zero for delivery retry
 * @param output parent event output
 * @param capacity parent output capacity
 * @param part_output part event output
 * @param part_capacity part output capacity
 * @param tracker ready tracker bound to the same world. at current or immediately preceding completed step
 * @param contact_output caller-owned contact output
 * @param contact_capacity contact output capacity
 * @param out_result completed-time/output/pending result
 * @param diagnostic optional diagnostic
 *
 * @return OK on success or the first failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collider_part_stepper_update_with_contacts(entasis_fixed_stepper_t * stepper, entasis_world_t * world, float elapsed, entasis_trigger_event_t * output, uint64_t capacity, entasis_collider_part_event_t * part_output, uint64_t part_capacity, entasis_contact_tracker_t * tracker, entasis_contact_event_t * contact_output, uint64_t contact_capacity, entasis_collider_part_contact_update_result_t * out_result, entasis_diagnostic_t * diagnostic);

/**
 * advances fixed steps with combined break and event delivery
 *
 * joint breaks must be enabled. enabled parent and part subscriptions participate automatically. NULL tracker requires empty contact output. inactive streams accept empty output only. consume written prefixes once and retry elapsed=0 after backpressure. successful physics time is consumed even when later publication or delivery fails
 *
 * @param stepper caller-owned fixed-step accumulator
 * @param world idle world with joint breaks enabled
 * @param elapsed elapsed seconds accepted once
 * @param break_output caller-owned event output, NULL only at zero capacity
 * @param break_capacity output element capacity
 * @param output caller-owned event output, NULL only at zero capacity
 * @param capacity output element capacity
 * @param part_output caller-owned event output, NULL only at zero capacity
 * @param part_capacity output element capacity
 * @param tracker optional tracker selects contact delivery
 * @param contact_output caller-owned contact output
 * @param contact_capacity contact output capacity
 * @param out_result receives completed time, written prefixes and pending streams
 * @param diagnostic optional diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK or the original failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_joint_break_stepper_update(entasis_fixed_stepper_t * stepper, entasis_world_t * world, float elapsed, entasis_joint_break_event_t * break_output, uint64_t break_capacity, entasis_trigger_event_t * output, uint64_t capacity, entasis_collider_part_event_t * part_output, uint64_t part_capacity, entasis_contact_tracker_t * tracker, entasis_contact_event_t * contact_output, uint64_t contact_capacity, entasis_joint_break_update_result_t * out_result, entasis_diagnostic_t * diagnostic);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* ENTASIS_EVENTS_H */
