// generated by tools/abi/generate_abi. do not edit
#ifndef ENTASIS_PROPERTIES_H
#define ENTASIS_PROPERTIES_H

#include <entasis/bodies.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * dense type-erased properties indexed by body handle
 */
struct entasis_body_property_table_t {
    /* internal body property state managed by Entasis */
    void * opaque;
};

/**
 * dense type-erased properties indexed by static handle
 */
struct entasis_static_property_table_t {
    /* internal static property state managed by Entasis */
    void * opaque;
};

/**
 * separate dense body and static property namespaces
 */
struct entasis_collidable_property_table_t {
    /* internal collidable property state managed by Entasis */
    void * opaque;
};

/**
 * generation-protected body property lifetime key
 */
struct entasis_body_property_key_t {
    /* object handle */
    entasis_body_handle_t handle;
    /* reserved for ABI compatibility */
    uint32_t reserved;
    /* generation used to reject stale keys */
    uint64_t generation;
    /* world mutation epoch captured with the view or key */
    uint64_t epoch;
    /* owning table or world identity used for validation */
    uint64_t owner;
};

/**
 * generation-protected static property lifetime key
 */
struct entasis_static_property_key_t {
    /* object handle */
    entasis_static_handle_t handle;
    /* reserved for ABI compatibility */
    uint32_t reserved;
    /* generation used to reject stale keys */
    uint64_t generation;
    /* world mutation epoch captured with the view or key */
    uint64_t epoch;
    /* owning table or world identity used for validation */
    uint64_t owner;
};

/**
 * generation-protected body or static property lifetime key
 */
struct entasis_collidable_property_key_t {
    /* collidable description or identity */
    entasis_collidable_reference_t collidable;
    /* reserved for ABI compatibility */
    uint32_t reserved;
    /* generation used to reject stale keys */
    uint64_t generation;
    /* world mutation epoch captured with the view or key */
    uint64_t epoch;
    /* owning table or world identity used for validation */
    uint64_t owner;
};

/**
 * initializes a dense type-erased body property table
 *
 * capacity is an initial hint and may be zero. a NULL allocator selects the runtime heap. ownership: caller owned. keep the table at a stable address until destroy
 *
 * @param table target body property table
 * @param value_size size of one property value in bytes
 * @param value_alignment required alignment of one property value in bytes
 * @param initial_capacity initial retained capacity
 * @param allocator copied allocator callbacks for storage covered by the selected allocation scope. user_context remains borrowed until destruction
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_property_init(entasis_body_property_table_t * table, uint64_t value_size, uint64_t value_alignment, uint64_t initial_capacity, const entasis_allocator_t * allocator, entasis_diagnostic_t * diagnostic);

/**
 * grows body property storage
 *
 * existing values and lifetime generations are preserved
 *
 * @param table target body property table
 * @param capacity requested minimum property storage capacity in entries, not an output-buffer size
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_property_ensure_capacity(entasis_body_property_table_t * table, uint64_t capacity, entasis_diagnostic_t * diagnostic);

/**
 * returns body property slot capacity
 *
 * @param table target body property table
 *
 * @return returns the retained capacity
 */
ENTASIS_API uint64_t ENTASIS_CALL entasis_body_property_capacity(const entasis_body_property_table_t * table);

/**
 * sets one body property value
 *
 * creating a missing value begins a new generation. updating a present value preserves existing keys. allocation may occur only when the handle index exceeds current capacity
 *
 * @param table target body property table
 * @param handle target body handle
 * @param value property bytes to copy
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_property_set(entasis_body_property_table_t * table, entasis_body_handle_t handle, const void * value, entasis_diagnostic_t * diagnostic);

/**
 * sets body properties in input order after one reserve preflight
 *
 * input and output storage remain caller owned
 *
 * @param table target body property table
 * @param handles input body handles
 * @param values packed input property values
 * @param value_stride byte stride between consecutive property values
 * @param count number of entries in the input arrays
 * @param out_completed receives the number of successfully completed prefix entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_property_set_batch(entasis_body_property_table_t * table, const entasis_body_handle_t * handles, const void * values, uint64_t value_stride, uint64_t count, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * returns a borrowed pointer to one body property
 *
 * allocation: none. the returned pointer is invalidated by growth, clear, destroy, or reinitialization
 *
 * @param table target body property table
 * @param handle target body handle
 * @param out_value receives the borrowed memory
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_property_get(const entasis_body_property_table_t * table, entasis_body_handle_t handle, const void ** out_value, entasis_diagnostic_t * diagnostic);

/**
 * captures one generation-protected body property key
 *
 * @param table target body property table
 * @param handle target body handle
 * @param out_key receives the body property key
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_property_key(const entasis_body_property_table_t * table, entasis_body_handle_t handle, entasis_body_property_key_t * out_key, entasis_diagnostic_t * diagnostic);

/**
 * resolves one generation-protected body property key
 *
 * allocation: none
 *
 * @param table target body property table
 * @param key generation-protected body property key
 * @param out_value receives the borrowed memory
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_property_get_key(const entasis_body_property_table_t * table, entasis_body_property_key_t key, const void ** out_value, entasis_diagnostic_t * diagnostic);

/**
 * removes one body property lifetime
 *
 * call it after a successful body removal or for the committed prefix of body_remove_batch
 *
 * @param table target body property table
 * @param handle target body handle
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_property_remove(entasis_body_property_table_t * table, entasis_body_handle_t handle, entasis_diagnostic_t * diagnostic);

/**
 * removes body property lifetimes in input order
 *
 * @param table target body property table
 * @param handles input body handles
 * @param count number of entries in the input arrays
 * @param out_completed receives the number of successfully completed prefix entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_property_remove_batch(entasis_body_property_table_t * table, const entasis_body_handle_t * handles, uint64_t count, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * clears body properties while retaining capacity
 *
 * @param table target body property table
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_property_clear(entasis_body_property_table_t * table, entasis_diagnostic_t * diagnostic);

/**
 * destroys body property storage
 *
 * the table may be initialized again at the same address
 *
 * @param table target body property table
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_body_property_destroy(entasis_body_property_table_t * table, entasis_diagnostic_t * diagnostic);

/**
 * initializes a dense type-erased static property table
 *
 * @param table target static property table
 * @param value_size size of one property value in bytes
 * @param value_alignment required alignment of one property value in bytes
 * @param initial_capacity initial retained capacity
 * @param allocator copied allocator callbacks for storage covered by the selected allocation scope. user_context remains borrowed until destruction
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_property_init(entasis_static_property_table_t * table, uint64_t value_size, uint64_t value_alignment, uint64_t initial_capacity, const entasis_allocator_t * allocator, entasis_diagnostic_t * diagnostic);

/**
 * grows static property storage
 *
 * @param table target static property table
 * @param capacity requested minimum property storage capacity in entries, not an output-buffer size
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_property_ensure_capacity(entasis_static_property_table_t * table, uint64_t capacity, entasis_diagnostic_t * diagnostic);

/**
 * returns static property slot capacity
 *
 * @param table target static property table
 *
 * @return returns the retained capacity
 */
ENTASIS_API uint64_t ENTASIS_CALL entasis_static_property_capacity(const entasis_static_property_table_t * table);

/**
 * sets one static property value
 *
 * allocation may occur on growth. updating an existing value preserves its key generation
 *
 * @param table target static property table
 * @param handle target static handle
 * @param value property bytes to copy
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_property_set(entasis_static_property_table_t * table, entasis_static_handle_t handle, const void * value, entasis_diagnostic_t * diagnostic);

/**
 * sets static properties in input order after one reserve preflight
 *
 * @param table target static property table
 * @param handles input static handles
 * @param values packed input property values
 * @param value_stride byte stride between consecutive property values
 * @param count number of entries in the input arrays
 * @param out_completed receives the number of successfully completed prefix entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_property_set_batch(entasis_static_property_table_t * table, const entasis_static_handle_t * handles, const void * values, uint64_t value_stride, uint64_t count, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * returns a borrowed pointer to one static property
 *
 * @param table target static property table
 * @param handle target static handle
 * @param out_value receives the borrowed memory
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_property_get(const entasis_static_property_table_t * table, entasis_static_handle_t handle, const void ** out_value, entasis_diagnostic_t * diagnostic);

/**
 * captures one generation-protected static property key
 *
 * @param table target static property table
 * @param handle target static handle
 * @param out_key receives the static property key
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_property_key(const entasis_static_property_table_t * table, entasis_static_handle_t handle, entasis_static_property_key_t * out_key, entasis_diagnostic_t * diagnostic);

/**
 * resolves one generation-protected static property key
 *
 * @param table target static property table
 * @param key generation-protected static property key
 * @param out_value receives the borrowed memory
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_property_get_key(const entasis_static_property_table_t * table, entasis_static_property_key_t key, const void ** out_value, entasis_diagnostic_t * diagnostic);

/**
 * removes one static property lifetime
 *
 * call it after the matching successful static removal
 *
 * @param table target static property table
 * @param handle target static handle
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_property_remove(entasis_static_property_table_t * table, entasis_static_handle_t handle, entasis_diagnostic_t * diagnostic);

/**
 * removes static property lifetimes in input order
 *
 * @param table target static property table
 * @param handles input static handles
 * @param count number of entries in the input arrays
 * @param out_completed receives the number of successfully completed prefix entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_property_remove_batch(entasis_static_property_table_t * table, const entasis_static_handle_t * handles, uint64_t count, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * clears static properties while retaining capacity
 *
 * @param table target static property table
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_property_clear(entasis_static_property_table_t * table, entasis_diagnostic_t * diagnostic);

/**
 * destroys static property storage
 *
 * @param table target static property table
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_static_property_destroy(entasis_static_property_table_t * table, entasis_diagnostic_t * diagnostic);

/**
 * initializes independent dense body and static property spaces
 *
 * @param table target collidable property table
 * @param value_size size of one property value in bytes
 * @param value_alignment required alignment of one property value in bytes
 * @param body_capacity required body namespace capacity
 * @param static_capacity required static namespace capacity
 * @param allocator copied allocator callbacks for storage covered by the selected allocation scope. user_context remains borrowed until destruction
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collidable_property_init(entasis_collidable_property_table_t * table, uint64_t value_size, uint64_t value_alignment, uint64_t body_capacity, uint64_t static_capacity, const entasis_allocator_t * allocator, entasis_diagnostic_t * diagnostic);

/**
 * grows both collidable property namespaces
 *
 * @param table target collidable property table
 * @param body_capacity required body namespace capacity
 * @param static_capacity required static namespace capacity
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collidable_property_ensure_capacity(entasis_collidable_property_table_t * table, uint64_t body_capacity, uint64_t static_capacity, entasis_diagnostic_t * diagnostic);

/**
 * sets one collidable property value
 *
 * @param table target collidable property table
 * @param collidable target collidable reference
 * @param value property bytes to copy
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collidable_property_set(entasis_collidable_property_table_t * table, entasis_collidable_reference_t collidable, const void * value, entasis_diagnostic_t * diagnostic);

/**
 * sets collidable properties in input order after one reserve preflight
 *
 * @param table target collidable property table
 * @param collidables input collidable references
 * @param values packed input property values
 * @param value_stride byte stride between consecutive property values
 * @param count number of entries in the input arrays
 * @param out_completed receives the number of successfully completed prefix entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collidable_property_set_batch(entasis_collidable_property_table_t * table, const entasis_collidable_reference_t * collidables, const void * values, uint64_t value_stride, uint64_t count, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * returns a borrowed pointer to one collidable property
 *
 * @param table target collidable property table
 * @param collidable target collidable reference
 * @param out_value receives the borrowed memory
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collidable_property_get(const entasis_collidable_property_table_t * table, entasis_collidable_reference_t collidable, const void ** out_value, entasis_diagnostic_t * diagnostic);

/**
 * captures one generation-protected collidable property key
 *
 * @param table target collidable property table
 * @param collidable target collidable reference
 * @param out_key receives the collidable property key
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collidable_property_key(const entasis_collidable_property_table_t * table, entasis_collidable_reference_t collidable, entasis_collidable_property_key_t * out_key, entasis_diagnostic_t * diagnostic);

/**
 * resolves one generation-protected collidable property key
 *
 * @param table target collidable property table
 * @param key generation-protected collidable property key
 * @param out_value receives the borrowed memory
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collidable_property_get_key(const entasis_collidable_property_table_t * table, entasis_collidable_property_key_t key, const void ** out_value, entasis_diagnostic_t * diagnostic);

/**
 * removes one collidable property lifetime
 *
 * @param table target collidable property table
 * @param collidable target collidable reference
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collidable_property_remove(entasis_collidable_property_table_t * table, entasis_collidable_reference_t collidable, entasis_diagnostic_t * diagnostic);

/**
 * removes collidable property lifetimes in input order
 *
 * @param table target collidable property table
 * @param collidables input collidable references
 * @param count number of entries in the input arrays
 * @param out_completed receives the number of successfully completed prefix entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collidable_property_remove_batch(entasis_collidable_property_table_t * table, const entasis_collidable_reference_t * collidables, uint64_t count, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * clears collidable properties while retaining capacity
 *
 * @param table target collidable property table
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collidable_property_clear(entasis_collidable_property_table_t * table, entasis_diagnostic_t * diagnostic);

/**
 * destroys collidable property storage
 *
 * @param table target collidable property table
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collidable_property_destroy(entasis_collidable_property_table_t * table, entasis_diagnostic_t * diagnostic);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* ENTASIS_PROPERTIES_H */
