// generated by tools/abi/generate_abi. do not edit
#ifndef ENTASIS_SHAPES_H
#define ENTASIS_SHAPES_H

#include <entasis/world.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * read-only access to registered shapes during a custom callback
 *
 * valid only on the invoking callback thread until that invocation returns. copying does not extend lifetime. do not destroy, forge, retain or use on another thread. helpers do not acquire ordinary world access or borrow mutable query scratch
 */
struct entasis_shape_access_t {
    /* borrowed callback-local implementation token. never dereference or retain */
    const void * opaque;
};

/**
 * read-only registered-task helper scope
 *
 * valid on the invoking thread only until the callback returns. it owns no world, registry or scratch. helpers reject recursive use of the same scope. callback chains must not contain cycles. ordinary world APIs remain forbidden during callbacks
 */
struct entasis_task_access_t {
    /* private callback-local token. never dereference or forge */
    const void * opaque;
};

/**
 * computes oriented bounds without translating the shape
 *
 * @param user_context caller-owned context, borrowed through world destruction
 * @param shape original stored custom payload, borrowed for this callback
 * @param orientation orientation to apply about the local origin
 * @param access read-only callback-local child-access scope
 * @param out_bounds output bounds
 *
 * @return returns the operation status. outputs are discarded on failure. foreign unwinding is forbidden
 */
typedef entasis_status_t (ENTASIS_CALL *entasis_shape_bounds_fn)(void * user_context, const void * shape, const entasis_quaternion_t * orientation, entasis_shape_access_t access, entasis_shape_bounds_t * out_bounds);
/**
 * computes inertia for the registered shape
 *
 * @param user_context caller-owned context, borrowed through world destruction
 * @param shape original stored custom payload, borrowed for this callback
 * @param mass mass used to compute inertia
 * @param access read-only callback-local child-access scope
 * @param out_inertia output inverse inertia and mass
 *
 * @return returns the operation status. outputs are discarded on failure. foreign unwinding is forbidden
 */
typedef entasis_status_t (ENTASIS_CALL *entasis_shape_inertia_fn)(void * user_context, const void * shape, float mass, entasis_shape_access_t access, entasis_body_inertia_t * out_inertia);
/**
 * tests a ray against a registered custom shape
 *
 * @param user_context caller-owned context, borrowed through world destruction
 * @param shape original stored custom payload, borrowed for this callback
 * @param pose shape world pose
 * @param ray world-space bounded ray
 * @param access read-only callback-local child-access scope
 * @param out_hit output hit or explicit miss
 *
 * @return returns the operation status. outputs are discarded on failure. foreign unwinding is forbidden
 */
typedef entasis_status_t (ENTASIS_CALL *entasis_shape_ray_fn)(void * user_context, const void * shape, const entasis_rigid_pose_t * pose, const entasis_ray_t * ray, entasis_shape_access_t access, entasis_shape_ray_hit_t * out_hit);
/**
 * computes a local-space convex support point
 *
 * @param user_context caller-owned context, borrowed through world destruction
 * @param shape original stored custom payload, borrowed for this callback
 * @param direction local-space support direction
 * @param access read-only callback-local child-access scope
 * @param out_support output local-space support point
 *
 * @return returns the operation status. outputs are discarded on failure. foreign unwinding is forbidden
 */
typedef entasis_status_t (ENTASIS_CALL *entasis_shape_support_fn)(void * user_context, const void * shape, const entasis_vector3_t * direction, entasis_shape_access_t access, entasis_vector3_t * out_support);
/**
 * releases caller-owned resources inside a removed custom payload, not the payload storage itself
 *
 * @param user_context caller-owned context, borrowed through world destruction
 * @param shape stored payload whose caller-owned resources must be released
 * @param access read-only callback-local child-access scope
 *
 * @return returns the operation status. outputs are discarded on failure. foreign unwinding is forbidden
 */
typedef entasis_status_t (ENTASIS_CALL *entasis_shape_dispose_fn)(void * user_context, void * shape, entasis_shape_access_t access);
/**
 * tests one convex collision pair
 *
 * @param user_context caller-owned registration context, distinct from the current query filter context
 * @param input borrowed callback-local input
 * @param access borrowed callback-local task scope. never retain or share
 * @param out_result required output. initially empty
 *
 * @return returns the operation status. invalid output or unknown status is rejected. foreign unwinding is forbidden
 */
typedef entasis_status_t (ENTASIS_CALL *entasis_collision_task_fn)(void * user_context, const entasis_collision_task_input_t * input, entasis_task_access_t access, entasis_convex_contact_manifold_t * out_result);
/**
 * tests one native eight-lane convex bundle without scalar callback expansion
 *
 * @param user_context caller-owned registration context, distinct from the current query filter context
 * @param input borrowed callback-local input
 * @param access borrowed callback-local task scope. never retain or share
 * @param out_result required output. initially empty
 *
 * @return returns the operation status. invalid output or unknown status is rejected. foreign unwinding is forbidden
 */
typedef entasis_status_t (ENTASIS_CALL *entasis_collision_task_wide_fn)(void * user_context, const entasis_collision_task_wide_input_t * input, entasis_task_access_t access, entasis_convex_manifold_wide_t * out_result);
/**
 * tests a top-level or child sweep in registered route order
 *
 * @param user_context caller-owned registration context, distinct from the current query filter context
 * @param input borrowed callback-local input
 * @param access borrowed callback-local task scope. never retain or share
 * @param out_result required output. initially empty
 *
 * @return returns the operation status. invalid output or unknown status is rejected. foreign unwinding is forbidden
 */
typedef entasis_status_t (ENTASIS_CALL *entasis_sweep_task_fn)(void * user_context, const entasis_sweep_task_input_t * input, entasis_task_access_t access, entasis_sweep_task_result_t * out_result);

/**
 * sphere shape description
 */
struct entasis_sphere_t {
    /* sphere radius */
    float radius;
};

/**
 * capsule shape description
 */
struct entasis_capsule_t {
    /* capsule radius */
    float radius;
    /* half length of the internal segment along the local Y axis */
    float half_length;
};

/**
 * box shape description using half extents
 */
struct entasis_box_t {
    /* half extent along the local X axis */
    float half_width;
    /* half extent along the local Y axis */
    float half_height;
    /* half extent along the local Z axis */
    float half_length;
};

/**
 * cylinder shape description
 */
struct entasis_cylinder_t {
    /* cylinder radius */
    float radius;
    /* half length along the local Y axis */
    float half_length;
};

/**
 * caller-owned zero-allocation view over compound children and masses
 */
struct entasis_compound_builder_t {
    /* borrowed compound child array */
    const entasis_compound_child_t * children;
    /* borrowed child mass array matching children */
    const float * masses;
    /* number of entries in children and masses */
    uint64_t count;
};

/**
 * opaque cooked convex hull owned by one cooking context
 */
struct entasis_cooked_hull_t {
    /* internal cooked hull state managed by Entasis */
    void * opaque;
};

/**
 * opaque cooked mesh owned by one cooking context
 */
struct entasis_cooked_mesh_t {
    /* internal cooked mesh state managed by Entasis */
    void * opaque;
};

/**
 * opaque portable compound owned by one cooking context
 */
struct entasis_cooked_compound_t {
    /* internal cooked compound state managed by Entasis */
    void * opaque;
};

/**
 * opaque tree-accelerated compound owned by one cooking context
 */
struct entasis_cooked_big_compound_t {
    /* internal cooked big compound state managed by Entasis */
    void * opaque;
};

/**
 * callback-local custom payload view
 *
 * only custom shapes can expose original bytes. built-in containers remain opaque. use the shape-access operations instead. no ownership is transferred
 */
struct entasis_custom_shape_view_t {
    /* original custom payload, immutable and borrowed until callback return */
    const void * data;
    /* registered payload size excluding stride padding */
    uint64_t size;
    /* registered payload alignment */
    uint64_t alignment;
    /* registered custom type ID */
    entasis_shape_type_id_t type_id;
    /* zero */
    uint32_t _reserved0;
};

/**
 * storage and callback description copied during custom registration
 *
 * register before the first successful world step. the callback table is copied. user_context remains borrowed until world destruction. payloads keep their exact caller representation. callbacks may run on worker/query threads and must synchronize their own shared data. world mutation and ordinary world API reentry from callbacks are forbidden. registering a type alone does not install collision or sweep pair routes
 */
struct entasis_custom_shape_registration_t {
    /* initialize to sizeof this structure */
    uint32_t struct_size;
    /* initialize to 1 */
    uint32_t struct_version;
    /* ENTASIS_SHAPE_TYPE_INVALID selects the next sequential type ID */
    entasis_shape_type_id_t expected_type_id;
    /* shape storage classification */
    entasis_shape_batch_type_t batch_type;
    /* exact payload size, greater than zero */
    uint64_t size;
    /* power-of-two alignment from 1 through 128 */
    uint64_t alignment;
    /* caller-owned context, borrowed through world destruction */
    void * user_context;
    /* required bounds callback */
    entasis_shape_bounds_fn bounds;
    /* required inertia callback */
    entasis_shape_inertia_fn inertia;
    /* required ray callback */
    entasis_shape_ray_fn ray;
    /* required local support callback */
    entasis_shape_support_fn support;
    /* NULL reuses support */
    entasis_shape_support_fn sweep_support;
    /* NULL means no caller resources need disposal */
    entasis_shape_dispose_fn dispose;
};

/**
 * eight-lane pointer view without private native payload storage
 *
 * exactly one callback per existing native bundle. compute offsets relative to A at the origin. the engine owns pair flipping. do not flip results. inactive lanes must not be read and must produce no contacts. inputs expire on return
 */
struct entasis_collision_task_wide_input_t {
    /* eight borrowed immutable payload pointers. only lanes below count are valid */
    const void *const * shape_a;
    /* eight borrowed immutable payload pointers in registered route order */
    const void *const * shape_b;
    /* B minus A world-space position, aligned to 32 bytes */
    const entasis_vector3_wide_t * offset_b;
    /* world orientation A, aligned to 32 bytes */
    const entasis_quaternion_wide_t * orientation_a;
    /* world orientation B, aligned to 32 bytes */
    const entasis_quaternion_wide_t * orientation_b;
    /* eight margins, aligned to 32 bytes */
    const entasis_f32x8_t * speculative_margin;
    /* active prefix length from 1 through 8 */
    uint32_t count;
    /* registered type A shared by the bundle */
    entasis_shape_type_id_t type_a;
    /* registered type B shared by the bundle */
    entasis_shape_type_id_t type_b;
};

/**
 * copied scalar and wide convex collision route
 *
 * register before stepping. descriptors are snapshotted before output writes and allocator callbacks. user_context remains caller-owned through world destruction. registration does not replace an existing route or consume an ID on failure. both callbacks are required. clear/reuse preserves bindings. callbacks may run concurrently and must synchronize shared application data. no global/TLS routing, payload header or per-pair allocation is used
 */
struct entasis_collision_task_registration_t {
    /* initialize to sizeof this structure */
    uint32_t struct_size;
    /* initialize to 1 */
    uint32_t struct_version;
    /* registered type A */
    entasis_shape_type_id_t shape_type_a;
    /* registered type B */
    entasis_shape_type_id_t shape_type_b;
    /* batch capacity from 1 through 32 */
    uint32_t batch_size;
    /* native pair-storage classification */
    entasis_collision_pair_type_t pair_type;
    /* caller-owned registration context, distinct from the current query filter context */
    void * user_context;
    /* required scalar callback */
    entasis_collision_task_fn test;
    /* required eight-lane callback */
    entasis_collision_task_wide_fn wide_test;
};

/**
 * copied top-level and child sweep route
 *
 * register before stepping. descriptors are snapshotted before output writes and allocator callbacks. user_context remains caller-owned through world destruction. registration does not replace an existing route or consume an ID on failure. both callbacks are required. clear/reuse preserves bindings. callbacks may run concurrently and must synchronize shared application data. no global/TLS routing, payload header or per-pair allocation is used
 */
struct entasis_sweep_task_registration_t {
    /* initialize to sizeof this structure */
    uint32_t struct_size;
    /* initialize to 1 */
    uint32_t struct_version;
    /* registered type A */
    entasis_shape_type_id_t shape_type_a;
    /* registered type B */
    entasis_shape_type_id_t shape_type_b;
    /* caller-owned registration context, distinct from the current query filter context */
    void * user_context;
    /* required top-level callback */
    entasis_sweep_task_fn test;
    /* required callback preserving parent and local child poses */
    entasis_sweep_task_fn child_test;
};

/**
 * callback-free native compound collision route
 *
 * register before stepping. the descriptor is copied before writing out_task_id, which may alias one descriptor field. uses the existing Bounds_Tested native compound traversal without allocating a callback binding or adding per-body/per-query storage. shape B must be an engine-owned Compound, Big_Compound or Mesh. Convex_Compound requires registered convex A. Compound_Pair requires engine-owned compound types on both sides. those built-in routes already exist and cannot be replaced. a custom shape tagged Compound is not native compound storage. child collision tasks must be registered separately. no missing child route is synthesized. Subtask_Generator is required. only Child_Order and Mesh_Reduction may additionally be set. these are task metadata, not switches that disable native filtering or reduction. failure does not consume a task ID. clear/reuse retains routes. mutation, read-phase and callback-reentry restrictions are unchanged
 */
struct entasis_compound_task_registration_t {
    /* initialize to sizeof this structure */
    uint32_t struct_size;
    /* initialize to 1 */
    uint32_t struct_version;
    /* registered convex type for Convex_Compound. engine-owned compound type for Compound_Pair */
    entasis_shape_type_id_t shape_type_a;
    /* engine-owned Compound, Big_Compound or Mesh type, never a custom payload */
    entasis_shape_type_id_t shape_type_b;
    /* batch capacity from 1 through 32 */
    uint32_t batch_size;
    /* Convex_Compound or Compound_Pair */
    entasis_collision_task_kind_t kind;
    /* Subtask_Generator required. Child_Order and Mesh_Reduction are optional native metadata bits */
    entasis_collision_task_capabilities_t capabilities;
};

/**
 * triangle shape description
 */
struct entasis_triangle_t {
    /* triangle vertex A */
    entasis_vector3_t a;
    /* triangle vertex B */
    entasis_vector3_t b;
    /* triangle vertex C */
    entasis_vector3_t c;
};

/**
 * local shape bounds, radius, and angular expansion
 */
struct entasis_shape_bounds_t {
    /* minimum local bound */
    entasis_vector3_t min;
    /* maximum local bound */
    entasis_vector3_t max;
    /* maximum distance from the local origin to the shape */
    float maximum_radius;
    /* maximum bounds expansion caused by shape rotation */
    float maximum_angular_expansion;
};

/**
 * ray hit returned by a custom shape callback
 */
struct entasis_shape_ray_hit_t {
    /* ray parameter at the hit */
    float t;
    /* contact or hit normal */
    entasis_vector3_t normal;
    /* compound child index, or -1 for the root shape */
    int32_t child_index;
    /* whether the ray hit the shape */
    entasis_bool_t hit;
    /* reserved for ABI compatibility */
    uint8_t reserved[3];
};

/**
 * pointer-free metadata for one registered shape
 */
struct entasis_shape_info_t {
    /* object handle */
    entasis_shape_handle_t handle;
    /* registered public type ID */
    entasis_shape_type_id_t type_id;
    /* stored shape value size in bytes */
    uint64_t value_size;
    /* stored shape value alignment in bytes */
    uint64_t value_alignment;
    /* number of live shape references */
    uint64_t reference_count;
};

/**
 * registered child shape and local pose used by a compound
 */
struct entasis_compound_child_t {
    /* child position in compound local space */
    entasis_vector3_t local_position;
    /* child orientation in compound local space */
    entasis_quaternion_t local_orientation;
    /* registered shape handle */
    entasis_shape_handle_t shape;
};

/**
 * custom sweep interval and hit geometry
 *
 * initialized to a miss at maximum_t with child indices -1. a hit requires finite geometry and 0 <= t0 <= maximum_t and t0 <= t1. t1 may exceed maximum_t as in the native conservative interval. the engine flips normals and child indices for reversed routes. outputs are discarded on error
 */
struct entasis_sweep_task_result_t {
    /* lower time bound */
    float t0;
    /* upper time bound */
    float t1;
    /* world hit location */
    entasis_vector3_t location;
    /* world normal from B toward A */
    entasis_vector3_t normal;
    /* child index A, or -1 */
    int32_t child_a;
    /* child index B, or -1 */
    int32_t child_b;
    /* ENTASIS_TRUE for a hit, ENTASIS_FALSE for a miss */
    entasis_bool_t hit;
};

/**
 * registered compound shape and its mass properties
 */
struct entasis_compound_build_result_t {
    /* registered shape handle */
    entasis_shape_handle_t shape;
    /* computed body inertia */
    entasis_body_inertia_t inertia;
    /* center of mass or policy center */
    entasis_vector3_t center;
};

/**
 * mesh inertia, center of mass, and signed closed volume
 */
struct entasis_mesh_mass_properties_t {
    /* computed body inertia */
    entasis_body_inertia_t inertia;
    /* center of mass or policy center */
    entasis_vector3_t center;
    /* signed closed volume. zero for open meshes */
    float volume;
};

/**
 * portable compound child pose and caller-defined shape table slot
 */
struct entasis_cooked_compound_child_t {
    /* child pose in compound local space */
    entasis_rigid_pose_t local_pose;
    /* caller-defined index into the import shape table */
    int32_t shape_slot;
};

/**
 * portable big-compound child pose, shape table slot, and local bounds
 */
struct entasis_cooked_big_compound_child_t {
    /* child pose in compound local space */
    entasis_rigid_pose_t local_pose;
    /* caller-defined index into the import shape table */
    int32_t shape_slot;
    /* child bounds in compound local space */
    entasis_bounding_box_t local_bounds;
};

/**
 * scalar pair in registered route order
 */
struct entasis_collision_task_input_t {
    /* borrowed immutable payload A in the exact representation associated with type_a */
    const void * shape_a;
    /* borrowed immutable payload B in the exact representation associated with type_b */
    const void * shape_b;
    /* registered type for payload A */
    entasis_shape_type_id_t type_a;
    /* registered type for payload B */
    entasis_shape_type_id_t type_b;
    /* world pose A */
    entasis_rigid_pose_t pose_a;
    /* world pose B */
    entasis_rigid_pose_t pose_b;
    /* pair speculative margin */
    float speculative_margin;
};

/**
 * one contact slot across eight lanes
 */
struct entasis_convex_contact_wide_t {
    /* world-oriented offsets relative to A */
    entasis_vector3_wide_t offset_a;
    /* contact depths */
    entasis_f32x8_t depth;
    /* feature IDs */
    entasis_i32x8_t feature_id;
    /* each lane is -1 for contact or 0 for absent. inactive lanes must be 0 */
    entasis_i32x8_t exists;
};

/**
 * sweep pair including parent and local child poses
 *
 * the engine supplies expected registration order, including flipped-route velocity and child-pose remapping. top-level callbacks may invoke the separate child-filter helper. child callbacks have already been filtered by the native traversal
 */
struct entasis_sweep_task_input_t {
    /* borrowed immutable payload A */
    const void * shape_a;
    /* borrowed immutable payload B */
    const void * shape_b;
    /* registered payload type A */
    entasis_shape_type_id_t type_a;
    /* registered payload type B */
    entasis_shape_type_id_t type_b;
    /* parent world pose A */
    entasis_rigid_pose_t parent_pose_a;
    /* parent world pose B */
    entasis_rigid_pose_t parent_pose_b;
    /* local child pose A, which is identity in a top-level callback */
    entasis_rigid_pose_t local_pose_a;
    /* local child pose B, which is identity in a top-level callback */
    entasis_rigid_pose_t local_pose_b;
    /* parent linear and angular velocity A */
    entasis_body_velocity_t velocity_a;
    /* parent linear and angular velocity B */
    entasis_body_velocity_t velocity_b;
    /* maximum sweep interval */
    float maximum_t;
    /* minimum advancement used by the native solver */
    float minimum_progression;
    /* native convergence threshold */
    float convergence_threshold;
    /* maximum solver iterations */
    int32_t maximum_iteration_count;
};

/**
 * four convex contact slots for one eight-lane callback
 *
 * output starts zeroed and is discarded on callback failure. only existing contacts require finite normal, offset and depth. this C scalar-array representation does not expose the compiler vector ABI
 */
struct entasis_convex_manifold_wide_t {
    /* one world-oriented normal per lane, directed from B toward A */
    entasis_vector3_wide_t normal;
    /* four contact slots */
    entasis_convex_contact_wide_t contacts[4];
};

/**
 * computes weighted mass properties and registers a tree-accelerated big compound
 *
 * it is intended for larger child counts whose local queries benefit from an internal tree
 *
 * @param world target world
 * @param builder compound builder input
 * @param recenter whether geometry is shifted around the computed center of mass
 * @param out_result receives the compound build result
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_big_compound_build_dynamic(entasis_world_t * world, entasis_compound_builder_t builder, entasis_bool_t recenter, entasis_compound_build_result_t * out_result, entasis_diagnostic_t * diagnostic);

/**
 * constructs a box from full width, height, and depth
 *
 * @param width full box width
 * @param height full box height
 * @param depth full box depth
 *
 * @return returns the box
 */
ENTASIS_API entasis_box_t ENTASIS_CALL entasis_box(float width, float height, float depth);

/**
 * constructs a box from explicit half extents
 *
 * @param half_width half extent along the local X axis
 * @param half_height half extent along the local Y axis
 * @param half_depth half extent along the local Z axis
 *
 * @return returns the box
 */
ENTASIS_API entasis_box_t ENTASIS_CALL entasis_box_half_extents(float half_width, float half_height, float half_depth);

/**
 * constructs a Y-axis capsule from radius and full cylindrical length
 *
 * @param radius shape radius
 * @param length full shape length
 *
 * @return returns the capsule
 */
ENTASIS_API entasis_capsule_t ENTASIS_CALL entasis_capsule(float radius, float length);

/**
 * constructs a Y-axis capsule from radius and half length
 *
 * @param radius shape radius
 * @param half_length half length of the internal segment along the local Y axis
 *
 * @return returns the capsule
 */
ENTASIS_API entasis_capsule_t ENTASIS_CALL entasis_capsule_half_length(float radius, float half_length);

/**
 * enables swept continuous collision detection
 *
 * larger positive thresholds terminate sweeps earlier. smaller positive thresholds refine the estimated time of impact more closely
 *
 * @param minimum_sweep_timestep minimum positive sweep time interval
 * @param convergence_threshold positive sweep convergence threshold
 *
 * @return returns the continuous detection
 */
ENTASIS_API entasis_continuous_detection_t ENTASIS_CALL entasis_ccd_continuous(float minimum_sweep_timestep, float convergence_threshold);

/**
 * disables sweep tests and limits velocity expansion to the collidable's speculative-margin range
 *
 * @return returns the continuous detection
 */
ENTASIS_API entasis_continuous_detection_t ENTASIS_CALL entasis_ccd_discrete(void);

/**
 * disables sweep tests but allows velocity expansion beyond the calculated speculative margin so continuous partners can discover the pair
 *
 * @return returns the continuous detection
 */
ENTASIS_API entasis_continuous_detection_t ENTASIS_CALL entasis_ccd_passive(void);

/**
 * optionally recenters caller-owned children, computes weighted inertia, and registers a standard compound in one owner-thread call
 *
 * @param world target world
 * @param builder compound builder input
 * @param recenter whether geometry is shifted around the computed center of mass
 * @param out_result receives the compound build result
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_compound_build_dynamic(entasis_world_t * world, entasis_compound_builder_t builder, entasis_bool_t recenter, entasis_compound_build_result_t * out_result, entasis_diagnostic_t * diagnostic);

/**
 * binds caller-owned child and mass arrays without allocation
 *
 * @param children input compound child array
 * @param masses input child masses matching the children array
 * @param count number of entries in the input arrays
 *
 * @return returns the compound builder
 */
ENTASIS_API entasis_compound_builder_t ENTASIS_CALL entasis_compound_builder(const entasis_compound_child_t * children, const float * masses, uint64_t count);

/**
 * computes the weighted center and inverse total mass without allocating or mutating children
 *
 * @param builder compound builder input
 * @param out_center receives the computed center of mass
 * @param out_inverse_mass receives the inverse total mass
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_compound_center_of_mass(entasis_compound_builder_t builder, entasis_vector3_t * out_center, float * out_inverse_mass);

/**
 * creates one compound child from a registered shape and local pose
 *
 * the returned value owns no resources
 *
 * @param shape registered shape handle
 * @param local_pose child pose relative to the compound origin
 *
 * @return returns the compound child
 */
ENTASIS_API entasis_compound_child_t ENTASIS_CALL entasis_compound_child(entasis_shape_handle_t shape, entasis_rigid_pose_t local_pose);

/**
 * computes mass properties around the current child origin
 *
 * it performs no allocation and does not modify the builder
 *
 * @param world target world
 * @param builder compound builder input
 * @param out_inertia receives the body inertia
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_compound_inertia_weighted(entasis_world_t * world, entasis_compound_builder_t builder, entasis_body_inertia_t * out_inertia, entasis_diagnostic_t * diagnostic);

/**
 * computes mass properties about the center of mass and subtracts that center from every caller-owned child position
 *
 * @param world target world
 * @param builder compound builder input
 * @param out_inertia receives the body inertia
 * @param out_center receives the computed center of mass
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_compound_inertia_weighted_recenter(entasis_world_t * world, entasis_compound_builder_t builder, entasis_body_inertia_t * out_inertia, entasis_vector3_t * out_center, entasis_diagnostic_t * diagnostic);

/**
 * constructs a Y-axis cylinder from radius and full length
 *
 * @param radius shape radius
 * @param length full shape length
 *
 * @return returns the cylinder
 */
ENTASIS_API entasis_cylinder_t ENTASIS_CALL entasis_cylinder(float radius, float length);

/**
 * constructs a Y-axis cylinder from radius and half length
 *
 * @param radius shape radius
 * @param half_length half length along the local Y axis
 *
 * @return returns the cylinder
 */
ENTASIS_API entasis_cylinder_t ENTASIS_CALL entasis_cylinder_half_length(float radius, float half_length);

/**
 * returns signed closed volume and center of mass
 *
 * @param world target world
 * @param handle target shape handle
 * @param out_volume receives the computed signed volume
 * @param out_center receives the computed center of mass
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_mesh_closed_center_of_mass(entasis_world_t * world, entasis_shape_handle_t handle, float * out_volume, entasis_vector3_t * out_center, entasis_diagnostic_t * diagnostic);

/**
 * computes closed-solid inertia for a registered mesh
 *
 * @param world target world
 * @param handle target shape handle
 * @param mass positive mass used to compute inertia or mass properties
 * @param out_inertia receives the body inertia
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_mesh_closed_inertia(entasis_world_t * world, entasis_shape_handle_t handle, float mass, entasis_body_inertia_t * out_inertia, entasis_diagnostic_t * diagnostic);

/**
 * returns the area-weighted center of an open triangle soup
 *
 * @param world target world
 * @param handle target shape handle
 * @param out_center receives the computed center of mass
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_mesh_open_center_of_mass(entasis_world_t * world, entasis_shape_handle_t handle, entasis_vector3_t * out_center, entasis_diagnostic_t * diagnostic);

/**
 * computes triangle-soup inertia for a registered mesh
 *
 * @param world target world
 * @param handle target shape handle
 * @param mass positive mass used to compute inertia or mass properties
 * @param out_inertia receives the body inertia
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_mesh_open_inertia(entasis_world_t * world, entasis_shape_handle_t handle, float mass, entasis_body_inertia_t * out_inertia, entasis_diagnostic_t * diagnostic);

/**
 * validates and registers one built-in primitive
 *
 * type_id selects the built-in primitive representation stored at shape_value. ownership: owner thread only while the world is idle
 *
 * @param world target world
 * @param type_id registered shape type ID
 * @param shape_value shape value matching type_id
 * @param out_handle receives the created shape handle
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_shape_add(entasis_world_t * world, entasis_shape_type_id_t type_id, const void * shape_value, entasis_shape_handle_t * out_handle, entasis_diagnostic_t * diagnostic);

/**
 * validates and registers built-in primitive shapes in input order
 *
 * each entry supplies its own type ID and value. the batch stops at the first failure and reports the completed prefix. the failing handle is invalid and later output slots are untouched. allocation: each registration may grow registry storage. ownership: owner thread only while the world is idle
 *
 * @param world target world
 * @param type_ids input shape type IDs
 * @param shape_values input pointers to shape values matching type_ids
 * @param count number of entries in the input arrays
 * @param out_handles receives shape handles in input order
 * @param out_completed receives the number of successfully completed prefix entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_shape_add_batch(entasis_world_t * world, const entasis_shape_type_id_t * type_ids, const void * const * shape_values, uint64_t count, entasis_shape_handle_t * out_handles, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * computes local bounds for a registered shape at an orientation
 *
 * @param world target world
 * @param handle target shape handle
 * @param orientation shape orientation used for local bounds
 * @param out_bounds receives the shape bounds
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_shape_bounds(entasis_world_t * world, entasis_shape_handle_t handle, entasis_quaternion_t orientation, entasis_shape_bounds_t * out_bounds, entasis_diagnostic_t * diagnostic);

/**
 * copies caller-owned child descriptors, builds the internal child tree in the world's pool, and registers one big compound
 *
 * @param world target world
 * @param children input compound child array
 * @param count number of entries in the input arrays
 * @param out_handle receives the created shape handle
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_shape_import_big_compound(entasis_world_t * world, const entasis_compound_child_t * children, uint64_t count, entasis_shape_handle_t * out_handle, entasis_diagnostic_t * diagnostic);

/**
 * copies caller-owned child descriptors into the world's pool and registers one compound
 *
 * child shapes are retained by the registry
 *
 * @param world target world
 * @param children input compound child array
 * @param count number of entries in the input arrays
 * @param out_handle receives the created shape handle
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_shape_import_compound(entasis_world_t * world, const entasis_compound_child_t * children, uint64_t count, entasis_shape_handle_t * out_handle, entasis_diagnostic_t * diagnostic);

/**
 * computes inertia directly from a built-in primitive value
 *
 * it performs no registry lookup and allocates nothing
 *
 * @param type_id registered shape type ID
 * @param shape_value shape value matching type_id
 * @param mass positive mass used to compute inertia or mass properties
 * @param out_inertia receives the body inertia
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_shape_inertia(entasis_shape_type_id_t type_id, const void * shape_value, float mass, entasis_body_inertia_t * out_inertia);

/**
 * returns the registered type, value layout and live reference count of a shape
 *
 * the reference count includes bodies, statics and compound child references
 *
 * @param world target world
 * @param handle target shape handle
 * @param out_info receives the shape info
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_shape_inspect(entasis_world_t * world, entasis_shape_handle_t handle, entasis_shape_info_t * out_info, entasis_diagnostic_t * diagnostic);

/**
 * tests one registered shape directly at the supplied pose, without creating a body or static or traversing the broad phase
 *
 * @param world target world
 * @param handle target shape handle
 * @param shape_pose world pose of the tested shape
 * @param query ray to execute
 * @param out_hit receives the shape ray hit
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_shape_ray(entasis_world_t * world, entasis_shape_handle_t handle, entasis_rigid_pose_t shape_pose, entasis_ray_t query, entasis_shape_ray_hit_t * out_hit, entasis_diagnostic_t * diagnostic);

/**
 * removes an unreferenced shape
 *
 * bodies, statics, and compound children retain shapes automatically. referenced shapes return ENTASIS_STATUS_SHAPE_IN_USE. ownership: owner thread only while the world is idle
 *
 * @param world target world
 * @param handle target shape handle
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_shape_remove(entasis_world_t * world, entasis_shape_handle_t handle, entasis_diagnostic_t * diagnostic);

/**
 * removes unreferenced shapes in input order
 *
 * a failure stops the batch. out_completed reports how many shapes were removed and identifies the first failing index. earlier removals remain applied. ownership: owner thread only while the world is idle
 *
 * @param world target world
 * @param handles input shape handles
 * @param count number of entries in the input arrays
 * @param out_completed receives the number of successfully completed prefix entries
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_shape_remove_batch(entasis_world_t * world, const entasis_shape_handle_t * handles, uint64_t count, uint64_t * out_completed, entasis_diagnostic_t * diagnostic);

/**
 * removes an unreferenced root and then removes every now-unreferenced reachable child shape
 *
 * shared descendants remain registered. scratch is caller-owned and must hold the returned required upper bound. the upper bound counts duplicate references conservatively. no hidden allocation occurs. the root is never modified when capacity is insufficient
 *
 * @param world target world
 * @param root root shape removed first
 * @param scratch caller-owned shape handle scratch array
 * @param scratch_count number of handles available in scratch storage
 * @param out_removed receives the number of shapes removed
 * @param out_required receives the total required output capacity
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_shape_remove_recursive(entasis_world_t * world, entasis_shape_handle_t root, entasis_shape_handle_t * scratch, uint64_t scratch_count, uint64_t * out_removed, uint64_t * out_required, entasis_diagnostic_t * diagnostic);

/**
 * returns type_id when it identifies a built-in shape type
 *
 * unsupported types return ENTASIS_SHAPE_TYPE_INVALID. this checks the type ID, not whether a shape instance exists. container types require their dedicated import APIs
 *
 * @param type_id registered shape type ID
 *
 * @return returns the shape type ID
 */
ENTASIS_API entasis_shape_type_id_t ENTASIS_CALL entasis_shape_type_id(entasis_shape_type_id_t type_id);

/**
 * validates public built-in primitive descriptions without allocation
 *
 * container and custom shapes use their dedicated advanced paths
 *
 * @param type_id registered shape type ID
 * @param shape_value shape value matching type_id
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_shape_validate(entasis_shape_type_id_t type_id, const void * shape_value);

/**
 * constructs a sphere from its radius
 *
 * validation occurs in shape_validate, shape_add, and shape_inertia
 *
 * @param radius shape radius
 *
 * @return returns the sphere
 */
ENTASIS_API entasis_sphere_t ENTASIS_CALL entasis_sphere(float radius);

/**
 * initializes descriptor size/version, next-ID selection, convex classification and alignment 1
 *
 * @return returns the initialized description
 */
ENTASIS_API entasis_custom_shape_registration_t ENTASIS_CALL entasis_custom_shape_registration_default(void);

/**
 * returns the next sequential custom type ID without reserving it
 *
 * @param world initialized caller-owned world
 * @param out_type_id required type ID output
 * @param diagnostic optional diagnostic output
 *
 * @return returns the operation status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_custom_shape_next_type_id(entasis_world_t * world, entasis_shape_type_id_t * out_type_id, entasis_diagnostic_t * diagnostic);

/**
 * registers a custom shape type using copied per-world callbacks
 *
 * rejected during a read phase, callback reentry or after stepping. allocation/validation failure does not consume a type ID. a non-convex classification requires appropriate custom pair routes, not a reinterpretation as a built-in compound
 *
 * @param world initialized caller-owned world
 * @param registration complete registration descriptor
 * @param out_type_id required type ID output. invalid on failure
 * @param diagnostic optional diagnostic output
 *
 * @return returns the operation status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_custom_shape_register(entasis_world_t * world, const entasis_custom_shape_registration_t * registration, entasis_shape_type_id_t * out_type_id, entasis_diagnostic_t * diagnostic);

/**
 * copies an instance into a registered custom shape batch
 *
 * source bytes need not be aligned, but stored payloads meet the registered alignment. on success, ownership of resources described by the payload transfers to its disposal callback. on failure it remains with the caller. use entasis_shape_remove for unreferenced instances. bodies, statics and built-in compound children retain shape handles normally
 *
 * @param world initialized caller-owned world
 * @param type_id previously registered custom type ID
 * @param shape source payload copied into registry storage
 * @param size must equal the registered payload size
 * @param out_handle required handle output. invalid on failure
 * @param diagnostic optional diagnostic output
 *
 * @return returns the operation status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_custom_shape_add(entasis_world_t * world, entasis_shape_type_id_t type_id, const void * shape, uint64_t size, entasis_shape_handle_t * out_handle, entasis_diagnostic_t * diagnostic);

/**
 * copies a custom payload without exposing mutable registry storage
 *
 * no bytes are written on insufficient capacity. returns Capacity_Missing with the exact size. a copy does not transfer ownership or duplicate pointed-to resources. this callback-free operation is allowed during an owner-controlled read phase
 *
 * @param world initialized caller-owned world
 * @param handle registered shape handle
 * @param output destination for a shallow byte copy. NULL is allowed only with zero capacity
 * @param capacity output capacity in bytes
 * @param out_required optional exact registered byte size, including on insufficient capacity
 * @param diagnostic optional diagnostic output
 *
 * @return returns the operation status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_custom_shape_get(entasis_world_t * world, entasis_shape_handle_t handle, void * output, uint64_t capacity, uint64_t * out_required, entasis_diagnostic_t * diagnostic);

/**
 * computes inertia for an existing custom shape through its registered callback
 *
 * requires idle exclusive world access. use the callback-local shape-access helper from callbacks instead of reentering this function
 *
 * @param world initialized caller-owned world
 * @param handle registered shape handle
 * @param mass mass passed to the custom inertia callback
 * @param out_inertia required inertia output, zero on failure
 * @param diagnostic optional diagnostic output
 *
 * @return returns the operation status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_custom_shape_inertia(entasis_world_t * world, entasis_shape_handle_t handle, float mass, entasis_body_inertia_t * out_inertia, entasis_diagnostic_t * diagnostic);

/**
 * resolves immutable custom bytes during a callback
 *
 * built-in types return Invalid_Argument. data and the scope expire at the invoking callback return. no world access state is modified
 *
 * @param access read-only callback-local child-access scope
 * @param handle registered shape handle
 * @param out_view required borrowed custom payload view, cleared on failure
 *
 * @return returns the operation status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_shape_access_custom_data(entasis_shape_access_t access, entasis_shape_handle_t handle, entasis_custom_shape_view_t * out_view);

/**
 * computes child bounds using the existing registered shape operation
 *
 * @param access read-only callback-local child-access scope
 * @param handle registered shape handle
 * @param orientation required local orientation
 * @param out_bounds required bounds output, cleared on failure
 *
 * @return returns the operation status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_shape_access_bounds(entasis_shape_access_t access, entasis_shape_handle_t handle, const entasis_quaternion_t * orientation, entasis_shape_bounds_t * out_bounds);

/**
 * computes child inertia using the existing registered shape operation
 *
 * @param access read-only callback-local child-access scope
 * @param handle registered shape handle
 * @param mass mass used to compute inertia
 * @param out_inertia required inertia output, cleared on failure
 *
 * @return returns the operation status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_shape_access_inertia(entasis_shape_access_t access, entasis_shape_handle_t handle, float mass, entasis_body_inertia_t * out_inertia);

/**
 * ray tests a registered child using the existing shape operation
 *
 * @param access read-only callback-local child-access scope
 * @param handle registered shape handle
 * @param pose required child world pose
 * @param ray required bounded ray
 * @param out_hit required output, initialized as a miss
 *
 * @return returns the operation status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_shape_access_ray(entasis_shape_access_t access, entasis_shape_handle_t handle, const entasis_rigid_pose_t * pose, const entasis_ray_t * ray, entasis_shape_ray_hit_t * out_hit);

/**
 * computes a registered child support point
 *
 * @param access read-only callback-local child-access scope
 * @param handle registered shape handle
 * @param direction required local-space direction
 * @param out_support required local-space support output, cleared on failure
 *
 * @return returns the operation status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_shape_access_support(entasis_shape_access_t access, entasis_shape_handle_t handle, const entasis_vector3_t * direction, entasis_vector3_t * out_support);

/**
 * computes a registered child sweep-support point
 *
 * @param access read-only callback-local child-access scope
 * @param handle registered shape handle
 * @param direction required local-space direction
 * @param out_support required local-space support output, cleared on failure
 *
 * @return returns the operation status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_shape_access_sweep_support(entasis_shape_access_t access, entasis_shape_handle_t handle, const entasis_vector3_t * direction, entasis_vector3_t * out_support);

/**
 * initializes task descriptor version, invalid type IDs, standard storage and batch size 32
 *
 * @return returns the initialized descriptor
 */
ENTASIS_API entasis_collision_task_registration_t ENTASIS_CALL entasis_collision_task_registration_default(void);

/**
 * registers one contextual collision pair route
 *
 * register before stepping. descriptors are snapshotted before output writes and allocator callbacks. user_context remains caller-owned through world destruction. registration does not replace an existing route or consume an ID on failure. both callbacks are required. clear/reuse preserves bindings. callbacks may run concurrently and must synchronize shared application data. no global/TLS routing, payload header or per-pair allocation is used
 *
 * @param world world while idle
 * @param registration description copied during registration
 * @param out_task_id required registered task ID. -1 on failure
 * @param diagnostic optional diagnostic output
 *
 * @return returns the operation status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collision_task_register(entasis_world_t * world, const entasis_collision_task_registration_t * registration, int32_t * out_task_id, entasis_diagnostic_t * diagnostic);

/**
 * initializes task descriptor version, invalid type IDs
 *
 * @return returns the initialized descriptor
 */
ENTASIS_API entasis_sweep_task_registration_t ENTASIS_CALL entasis_sweep_task_registration_default(void);

/**
 * registers one contextual sweep pair route
 *
 * register before stepping. descriptors are snapshotted before output writes and allocator callbacks. user_context remains caller-owned through world destruction. registration does not replace an existing route or consume an ID on failure. both callbacks are required. clear/reuse preserves bindings. callbacks may run concurrently and must synchronize shared application data. no global/TLS routing, payload header or per-pair allocation is used
 *
 * @param world world while idle
 * @param registration description copied during registration
 * @param out_task_id required registered task ID. -1 on failure
 * @param diagnostic optional diagnostic output
 *
 * @return returns the operation status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_sweep_task_register(entasis_world_t * world, const entasis_sweep_task_registration_t * registration, int32_t * out_task_id, entasis_diagnostic_t * diagnostic);

/**
 * obtains the existing read-only shape helpers without entering ordinary world APIs
 *
 * @param access borrowed callback-local task scope. never retain or share
 * @param out_access required borrowed child-access scope. expires with the task callback
 *
 * @return returns the operation status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_task_shape_access(entasis_task_access_t access, entasis_shape_access_t * out_access);

/**
 * invokes the current query child filter, keeping its context separate from registration context
 *
 * the engine remaps flipped routes. a missing filter allows the pair. no filter is supplied in scalar/wide collision or child-sweep callbacks. same-scope recursive helper use returns Invalid_Argument
 *
 * @param access borrowed callback-local task scope. never retain or share
 * @param pair_id native callback-local pair ID
 * @param child_a child A in registered route order
 * @param child_b child B in registered route order
 * @param out_allowed required result, false on failure
 *
 * @return returns the operation status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_task_allow_child(entasis_task_access_t access, int32_t pair_id, int32_t child_a, int32_t child_b, entasis_bool_t * out_allowed);

/**
 * invokes the existing registered scalar convex route without mutable world scratch
 *
 * rejects direct reentry into the current collision route and same-scope helper recursion. payload representation must match its supplied registered type. do not create cyclic callback chains
 *
 * @param access borrowed callback-local task scope. never retain or share
 * @param input typed borrowed payloads and poses for a registered convex route
 * @param out_result required output, empty on failure
 *
 * @return returns the operation status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_task_collide_convex(entasis_task_access_t access, const entasis_collision_task_input_t * input, entasis_convex_contact_manifold_t * out_result);

/**
 * uses the native support-based convex sweep kernel for top-level or child poses
 *
 * does not redispatch the registered sweep callback or implicitly invoke a child filter. a compound task must call task_allow_child for each candidate before this helper. accepts built-in convex types Sphere through ConvexHull only, matching the native helper. custom callbacks may explicitly convert payloads or supply their own algorithm. no borrowed world batcher or pool is used
 *
 * @param access borrowed callback-local task scope. never retain or share
 * @param input convex typed payloads and parent/local poses
 * @param out_result required output, miss on failure
 *
 * @return returns the operation status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_task_sweep_convex(entasis_task_access_t access, const entasis_sweep_task_input_t * input, entasis_sweep_task_result_t * out_result);

/**
 * initializes invalid type IDs, batch size 16, Convex_Compound and Subtask_Generator with Child_Order
 *
 * @return returns the initialized descriptor
 */
ENTASIS_API entasis_compound_task_registration_t ENTASIS_CALL entasis_compound_task_registration_default(void);

/**
 * registers callback-free native compound traversal for a new pair route
 *
 * register before stepping. the descriptor is copied before writing out_task_id, which may alias one descriptor field. uses the existing Bounds_Tested native compound traversal without allocating a callback binding or adding per-body/per-query storage. shape B must be an engine-owned Compound, Big_Compound or Mesh. Convex_Compound requires registered convex A. Compound_Pair requires engine-owned compound types on both sides. those built-in routes already exist and cannot be replaced. a custom shape tagged Compound is not native compound storage. child collision tasks must be registered separately. no missing child route is synthesized. Subtask_Generator is required. only Child_Order and Mesh_Reduction may additionally be set. these are task metadata, not switches that disable native filtering or reduction. failure does not consume a task ID. clear/reuse retains routes. mutation, read-phase and callback-reentry restrictions are unchanged
 *
 * @param world world while idle
 * @param registration description copied during registration
 * @param out_task_id required registered task ID. -1 on failure
 * @param diagnostic optional diagnostic output
 *
 * @return returns the operation status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_collision_task_compound_register(entasis_world_t * world, const entasis_compound_task_registration_t * registration, int32_t * out_task_id, entasis_diagnostic_t * diagnostic);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* ENTASIS_SHAPES_H */
