// generated by tools/abi/generate_abi. do not edit
#ifndef ENTASIS_WORLD_H
#define ENTASIS_WORLD_H

#include <entasis/collision.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * opaque caller-owned world handle kept at a stable address while ready
 */
struct entasis_world_t {
    /* internal world state managed by Entasis */
    void * opaque;
};

/**
 * opaque caller-owned reusable buffer pool handle
 */
struct entasis_buffer_pool_t {
    /* internal buffer pool state managed by Entasis */
    void * opaque;
};

/**
 * opaque caller-owned included thread pool handle
 */
struct entasis_thread_pool_t {
    /* internal thread pool state managed by Entasis */
    void * opaque;
};

/**
 * borrowed value token valid only within one custom timestep callback
 *
 * a copied token is rejected after its invocation expires while the world remains alive. it owns no stack memory. use after world destruction violates the normal handle lifetime contract. recursive scope operations are rejected
 */
struct entasis_step_scope_t {
    /* borrowed world handle. ordinary reentrant mutation is rejected */
    entasis_world_t world;
    /* invocation generation checked against the live owning world */
    uint64_t generation;
};

/**
 * allocates aligned memory through caller-provided storage
 *
 * @param user_context caller-owned context passed unchanged by Entasis
 * @param size allocation size in bytes
 * @param alignment required power-of-two alignment in bytes
 *
 * @return returns allocated memory or NULL on failure
 */
typedef void * (ENTASIS_CALL *entasis_allocate_fn)(void * user_context, uint64_t size, uint64_t alignment);
/**
 * resizes aligned memory through caller-provided storage
 *
 * @param user_context caller-owned context passed unchanged by Entasis
 * @param memory memory returned by the paired allocator
 * @param old_size current allocation size in bytes
 * @param new_size requested allocation size in bytes
 * @param alignment required power-of-two alignment in bytes
 *
 * @return returns allocated memory or NULL on failure
 */
typedef void * (ENTASIS_CALL *entasis_reallocate_fn)(void * user_context, void * memory, uint64_t old_size, uint64_t new_size, uint64_t alignment);
/**
 * releases aligned memory returned by the paired allocator
 *
 * @param user_context caller-owned context passed unchanged by Entasis
 * @param memory memory returned by the paired allocator
 * @param size allocation size in bytes
 * @param alignment required power-of-two alignment in bytes
 *
 * @return no return value
 */
typedef void (ENTASIS_CALL *entasis_deallocate_fn)(void * user_context, void * memory, uint64_t size, uint64_t alignment);
/**
 * runs one worker index for a blocking dispatch
 *
 * @param worker_index zero-based worker index
 * @param work_context dispatch work context supplied by Entasis
 *
 * @return no return value
 */
typedef void (ENTASIS_CALL *entasis_dispatch_work_proc_t)(uint32_t worker_index, void * work_context);
/**
 * invokes each worker exactly once and returns after all workers complete
 *
 * @param user_context caller-owned context passed unchanged by Entasis
 * @param work worker procedure invoked once per worker index
 * @param work_context dispatch work context supplied by Entasis
 * @param worker_count number of participating workers, including the caller when required by the dispatcher contract
 *
 * @return returns ENTASIS_DISPATCHER_STATUS_OK on success or a dispatcher failure status
 */
typedef entasis_dispatcher_status_t (ENTASIS_CALL *entasis_dispatch_proc_t)(void * user_context, entasis_dispatch_work_proc_t work, void * work_context, uint32_t worker_count);
/**
 * returns the reusable buffer pool assigned to one worker
 *
 * @param user_context caller-owned context passed unchanged by Entasis
 * @param worker_index zero-based worker index
 * @param out_pool receives the buffer pool assigned to the worker
 *
 * @return returns ENTASIS_DISPATCHER_STATUS_OK on success or a dispatcher failure status
 */
typedef entasis_dispatcher_status_t (ENTASIS_CALL *entasis_dispatch_worker_pool_proc_t)(void * user_context, uint32_t worker_index, entasis_buffer_pool_t * out_pool);
/**
 * initializes velocity callback resources before the world is returned to its owner
 *
 * @param user_context caller-owned callback state, borrowed for the registered lifetime
 * @param world borrowed world handle. ordinary reentrant mutation is rejected
 *
 * @return returns OK only after successfully initializing owned callback resources
 */
typedef entasis_status_t (ENTASIS_CALL *entasis_velocity_initialize_fn)(void * user_context, entasis_world_t world);
/**
 * prepares custom velocity integration for the supplied duration
 *
 * @param user_context caller-owned callback state, borrowed for the registered lifetime
 * @param dt positive duration in seconds
 *
 * @return returns OK or an error which aborts subsequent stage work
 */
typedef entasis_status_t (ENTASIS_CALL *entasis_velocity_prepare_fn)(void * user_context, float dt);
/**
 * integrates one native eight-lane bundle without per-body foreign calls
 *
 * @param user_context caller-owned callback state, borrowed for the registered lifetime
 * @param view borrowed eight-lane view. only view->velocity is writable
 *
 * @return returns normally without throwing or retaining borrowed views
 */
typedef void (ENTASIS_CALL *entasis_velocity_integrate_fn)(void * user_context, const entasis_pose_integration_view_t * view);
/**
 * disposes successfully initialized velocity callback resources exactly once
 *
 * @param user_context caller-owned callback state, borrowed for the registered lifetime
 *
 * @return returns after releasing callback-owned resources. foreign unwinding is forbidden
 */
typedef void (ENTASIS_CALL *entasis_velocity_dispose_fn)(void * user_context);
/**
 * initializes custom contact state before the world is published
 *
 * @param user_context caller-owned callback state, borrowed for the registered lifetime
 * @param world borrowed world handle. ordinary reentrant mutation is rejected
 *
 * @return returns OK only after successful initialization
 */
typedef entasis_status_t (ENTASIS_CALL *entasis_contact_initialize_fn)(void * user_context, entasis_world_t world);
/**
 * filters a pair before collision testing. may adjust its speculative margin
 *
 * @param user_context caller-owned callback state, borrowed for the registered lifetime
 * @param worker_index calling narrow-phase worker index
 * @param a first collidable
 * @param b second collidable
 * @param speculative_margin in/out speculative margin for this pair
 *
 * @return returns true to test the pair or false to reject it
 */
typedef entasis_bool_t (ENTASIS_CALL *entasis_contact_allow_fn)(void * user_context, int32_t worker_index, entasis_collidable_reference_t a, entasis_collidable_reference_t b, float * speculative_margin);
/**
 * filters one child pair before collision testing
 *
 * @param user_context caller-owned callback state, borrowed for the registered lifetime
 * @param worker_index calling narrow-phase worker index
 * @param a first collidable
 * @param b second collidable
 * @param child_a first child index in the current pair ordering
 * @param child_b second child index in the current pair ordering
 *
 * @return returns true to test the child pair
 */
typedef entasis_bool_t (ENTASIS_CALL *entasis_contact_allow_child_fn)(void * user_context, int32_t worker_index, entasis_collidable_reference_t a, entasis_collidable_reference_t b, int32_t child_a, int32_t child_b);
/**
 * edits the actual manifold and material used for constraint generation
 *
 * @param user_context caller-owned callback state, borrowed for the registered lifetime
 * @param worker_index calling narrow-phase worker index
 * @param a first collidable
 * @param b second collidable
 * @param manifold in/out manifold. preserve native kind and fixed contact capacity
 * @param material in/out material consumed by the solver
 *
 * @return returns true to accept the modified contact pair
 */
typedef entasis_bool_t (ENTASIS_CALL *entasis_contact_configure_fn)(void * user_context, int32_t worker_index, entasis_collidable_reference_t a, entasis_collidable_reference_t b, entasis_contact_manifold_t * manifold, entasis_contact_material_t * material);
/**
 * edits one convex child manifold before reduction
 *
 * @param user_context caller-owned callback state, borrowed for the registered lifetime
 * @param worker_index calling narrow-phase worker index
 * @param a first collidable
 * @param b second collidable
 * @param child_a first child index in the current pair ordering
 * @param child_b second child index in the current pair ordering
 * @param manifold in/out child manifold. preserve fixed contact capacity
 *
 * @return returns true to retain the child manifold
 */
typedef entasis_bool_t (ENTASIS_CALL *entasis_contact_configure_child_fn)(void * user_context, int32_t worker_index, entasis_collidable_reference_t a, entasis_collidable_reference_t b, int32_t child_a, int32_t child_b, entasis_convex_contact_manifold_t * manifold);
/**
 * disposes successfully initialized contact resources exactly once
 *
 * @param user_context caller-owned callback state, borrowed for the registered lifetime
 *
 * @return returns after callback resource cleanup
 */
typedef void (ENTASIS_CALL *entasis_contact_dispose_fn)(void * user_context);
/**
 * optionally selects a compatible registered contact constraint type
 *
 * @param user_context caller-owned callback state, borrowed for the registered lifetime
 * @param a first collidable
 * @param b second collidable
 * @param manifold read-only configured manifold
 * @param default_type_id native constraint type selected for this manifold
 *
 * @return returns a compatible registered type ID. returning default_type_id preserves the native selection
 */
typedef int32_t (ENTASIS_CALL *entasis_contact_select_constraint_fn)(void * user_context, entasis_collidable_reference_t a, entasis_collidable_reference_t b, const entasis_contact_manifold_t * manifold, int32_t default_type_id);
/**
 * observes a timestep completion point without ordinary world reentry
 *
 * @param user_context caller-owned callback state, borrowed for the registered lifetime
 * @param world borrowed world handle. ordinary reentrant mutation is rejected
 * @param stage completed stage identifier
 * @param dt positive duration in seconds
 *
 * @return returns OK to continue. errors do not roll back completed work
 */
typedef entasis_status_t (ENTASIS_CALL *entasis_stage_completed_fn)(void * user_context, entasis_world_t world, entasis_timestep_completion_stage_t stage, float dt);
/**
 * performs a caller-selected stage sequence using the live scope
 *
 * @param user_context caller-owned callback state, borrowed for the registered lifetime
 * @param scope live scope for this invocation
 * @param dt positive duration in seconds
 *
 * @return returns OK to advance the step counter exactly once. errors leave the counter unchanged without rollback
 */
typedef entasis_status_t (ENTASIS_CALL *entasis_timestep_fn)(void * user_context, entasis_step_scope_t scope, float dt);
/**
 * chooses the existing solver velocity-iteration count per substep
 *
 * @param user_context caller-owned callback state, borrowed for the registered lifetime
 * @param substep_index zero-based current solver substep
 *
 * @return positive values select the iteration count. nonpositive values retain the configured fixed iteration count, matching Odin
 */
typedef int32_t (ENTASIS_CALL *entasis_substep_iterations_fn)(void * user_context, int32_t substep_index);

/**
 * versioned allocator callback table and caller context
 */
struct entasis_allocator_t {
    /* size of this struct in bytes */
    uint32_t struct_size;
    /* version of this struct layout */
    uint32_t struct_version;
    /* caller-owned context passed unchanged to associated callbacks */
    void * user_context;
    /* allocate callback */
    entasis_allocate_fn allocate;
    /* reallocate callback */
    entasis_reallocate_fn reallocate;
    /* deallocate callback */
    entasis_deallocate_fn deallocate;
};

/**
 * linear and angular damping values
 */
struct entasis_damping_t {
    /* linear damping coefficient */
    float linear;
    /* angular damping coefficient */
    float angular;
};

/**
 * initial storage capacity hints for world-owned collections
 */
struct entasis_capacity_hints_t {
    /* initial body capacity hint */
    int32_t bodies;
    /* initial static capacity hint */
    int32_t statics;
    /* initial capacity for inactive body sets */
    int32_t inactive_body_sets;
    /* initial shape capacity reserved for each registered type */
    int32_t shapes_per_type;
    /* initial constraint capacity hint */
    int32_t constraints;
    /* initial constraint capacity reserved for each type batch */
    int32_t initial_constraints_per_type_batch;
    /* minimum constraint capacity reserved per body */
    int32_t minimum_constraints_per_body;
    /* initial capacity for broad-phase candidate pairs */
    int32_t broad_phase_candidates;
    /* initial collision pair capacity hint */
    int32_t pairs;
    /* initial capacity for compound child collision pairs */
    int32_t collision_child_pairs;
    /* initial capacity for inactive collision pairs */
    int32_t inactive_pairs;
    /* per-worker capacity for pending collision pairs */
    int32_t pending_pairs_per_worker;
};

/**
 * caller-owned dense gravity table indexed by body handle
 */
struct entasis_per_body_gravity_policy_t {
    /* borrowed dense gravity array indexed by body handle value */
    const entasis_vector3_t * gravity_by_body_handle;
    /* number of entries in gravity_by_body_handle */
    uint64_t gravity_count;
    /* linear damping coefficient */
    float linear_damping;
    /* angular damping coefficient */
    float angular_damping;
};

/**
 * blocking external dispatcher callback table
 */
struct entasis_dispatcher_interface_t {
    /* size of this struct in bytes */
    uint32_t struct_size;
    /* version of this struct layout */
    uint32_t struct_version;
    /* caller-owned context passed unchanged to associated callbacks */
    void * user_context;
    /* number of participating workers */
    uint32_t worker_count;
    /* reserved for ABI compatibility */
    uint32_t reserved;
    /* dispatch callback */
    entasis_dispatch_proc_t dispatch;
    /* worker pool callback */
    entasis_dispatch_worker_pool_proc_t worker_pool;
};

/**
 * solver iteration and substep settings
 */
struct entasis_solve_description_t {
    /* size of this struct in bytes */
    uint32_t struct_size;
    /* version of this struct layout */
    uint32_t struct_version;
    /* velocity solve iterations executed per substep */
    int32_t velocity_iterations;
    /* solver substeps executed during one world step */
    int32_t substeps;
    /* batch index reserved for fallback constraints */
    int32_t fallback_batch_threshold;
    /* reserved for ABI compatibility */
    uint32_t reserved;
};

/**
 * worker count, pool block size, and optional external dispatcher
 */
struct entasis_threading_description_t {
    /* size of this struct in bytes */
    uint32_t struct_size;
    /* version of this struct layout */
    uint32_t struct_version;
    /* number of participating workers */
    uint32_t worker_count;
    /* native block size used by each worker buffer pool */
    uint32_t worker_pool_block_size;
    /* borrowed dispatcher interface */
    const entasis_dispatcher_interface_t * external_dispatcher;
};

/**
 * allocation-free world counts and completed step index
 */
struct entasis_world_stats_t {
    /* completed world step index */
    uint64_t step_index;
    /* number of bodies in the active set */
    int64_t active_bodies;
    /* number of bodies in sleeping sets */
    int64_t sleeping_bodies;
    /* number of sleeping connected islands */
    int64_t sleeping_islands;
    /* number of live statics */
    int64_t statics;
    /* number of constraints in active solver storage */
    int64_t active_constraints;
    /* number of constraints in sleeping sets */
    int64_t sleeping_constraints;
    /* number of active collision pairs */
    int64_t active_pairs;
    /* number of inactive collision pairs */
    int64_t inactive_pairs;
    /* number of live registered shape instances */
    int64_t registered_shapes;
    /* number of registered shape types */
    int64_t registered_shape_types;
};

/**
 * callback-local integration inputs and output for one existing SIMD bundle
 *
 * all pointers expire on callback return. one invocation handles eight lanes, not one invocation per body. do not call ordinary world/body getters during stepping. do not retain any view pointer or unwind a foreign exception through Entasis
 */
struct entasis_pose_integration_view_t {
    /* eight stable body handles. inactive lanes contain invalid handles */
    const entasis_body_handle_t * body_handles;
    /* eight active-lane masks. never access inactive bodies */
    const entasis_i32x8_t * active_mask;
    /* read-only world-space positions */
    const entasis_vector3_wide_t * position;
    /* read-only orientations */
    const entasis_quaternion_wide_t * orientation;
    /* read-only world-space inertia */
    const entasis_body_inertia_wide_t * inertia;
    /* read-only per-lane timestep durations */
    const entasis_f32x8_t * dt;
    /* writable velocities. inactive lanes are restored after the callback */
    entasis_body_velocity_wide_t * velocity;
    /* calling worker index. callback state must support concurrent workers */
    int32_t worker_index;
    /* reserved output padding. do not modify */
    uint32_t _reserved0;
};

/**
 * copied custom integration table. caller context remains borrowed
 *
 * all four function pointers are required. conflicts with an explicitly selected legacy pose policy are rejected. a failed initialize callback must clean up its own partial resources. dispose is called only after initialization succeeds
 */
struct entasis_velocity_callbacks_t {
    /* initialize to sizeof this structure */
    uint32_t struct_size;
    /* initialize to 1 */
    uint32_t struct_version;
    /* existing angular integration policy */
    entasis_angular_integration_mode_t angular_mode;
    /* whether unconstrained bodies use substeps */
    entasis_bool_t allow_substeps_for_unconstrained;
    /* whether kinematic velocity is passed through integration */
    entasis_bool_t integrate_kinematic_velocity;
    /* initialize reserved storage to zero */
    uint8_t _reserved0;
    /* caller-owned callback state, borrowed for the registered lifetime */
    void * user_context;
    /* required initialization callback */
    entasis_velocity_initialize_fn initialize;
    /* required preparation callback */
    entasis_velocity_prepare_fn prepare;
    /* required eight-lane callback */
    entasis_velocity_integrate_fn integrate;
    /* required callback resource disposal */
    entasis_velocity_dispose_fn dispose;
};

/**
 * copied custom narrow-phase table with borrowed caller context
 *
 * all callbacks except select_constraint are required. they may run on multiple workers and must not reenter world mutation. conflicts with explicit built-in narrow policies are rejected. views expire on return. failed initialization owns its partial cleanup. successful initialization receives one disposal
 */
struct entasis_contact_callbacks_t {
    /* initialize to sizeof this structure */
    uint32_t struct_size;
    /* initialize to 1 */
    uint32_t struct_version;
    /* caller-owned callback state, borrowed for the registered lifetime */
    void * user_context;
    /* required initialization callback */
    entasis_contact_initialize_fn initialize;
    /* required pair filter */
    entasis_contact_allow_fn allow;
    /* required child-pair filter */
    entasis_contact_allow_child_fn allow_child;
    /* required manifold and material callback */
    entasis_contact_configure_fn configure;
    /* required child-manifold callback */
    entasis_contact_configure_child_fn configure_child;
    /* required disposal callback */
    entasis_contact_dispose_fn dispose;
    /* optional compatible contact-constraint selection */
    entasis_contact_select_constraint_fn select_constraint;
};

/**
 * copied stage completion hook
 */
struct entasis_timestep_callbacks_t {
    /* initialize to sizeof this structure */
    uint32_t struct_size;
    /* initialize to 1 */
    uint32_t struct_version;
    /* caller-owned callback state, borrowed for the registered lifetime */
    void * user_context;
    /* required selected callback */
    entasis_stage_completed_fn stage_completed;
};

/**
 * copied custom complete-timestep hook
 */
struct entasis_timestepper_t {
    /* initialize to sizeof this structure */
    uint32_t struct_size;
    /* initialize to 1 */
    uint32_t struct_version;
    /* caller-owned callback state, borrowed for the registered lifetime */
    void * user_context;
    /* required selected callback */
    entasis_timestep_fn step;
};

/**
 * copied solver substep scheduling hook
 */
struct entasis_substep_scheduler_t {
    /* initialize to sizeof this structure */
    uint32_t struct_size;
    /* initialize to 1 */
    uint32_t struct_version;
    /* caller-owned callback state, borrowed for the registered lifetime */
    void * user_context;
    /* required selected callback */
    entasis_substep_iterations_fn iterations;
};

/**
 * additive initialization options. a null table retains the existing native path
 *
 * initialize with entasis_world_extensions_default. descriptors are copied, but user contexts and application arrays remain borrowed for their documented lifetime. malformed selected tables and conflicting explicit convenience policies fail before initialization callbacks run. Legacy allocator reach remains unchanged. All_Owned routes all owned world/pool/worker/query and extension storage through the selected allocator, preserving independent borrowed resource owners
 */
struct entasis_world_extensions_t {
    /* initialize to sizeof this structure */
    uint32_t struct_size;
    /* initialize to 1 */
    uint32_t struct_version;
    /* ENTASIS_ALLOCATION_LEGACY or ENTASIS_ALLOCATION_ALL_OWNED. borrowed pools and external dispatchers retain their independent allocator */
    entasis_allocation_scope_t allocation_scope;
    /* initialize reserved storage to zero */
    uint32_t _reserved0;
    /* optional descriptor copied into stable world-owned storage */
    const entasis_velocity_callbacks_t * velocity_callbacks;
    /* optional descriptor copied into stable world-owned storage */
    const entasis_contact_callbacks_t * contact_callbacks;
    /* optional descriptor copied into stable world-owned storage */
    const entasis_timestep_callbacks_t * timestep_callbacks;
    /* optional descriptor copied into stable world-owned storage */
    const entasis_timestepper_t * timestepper;
    /* optional descriptor copied into stable world-owned storage */
    const entasis_substep_scheduler_t * substep_scheduler;
};

/**
 * uniform gravity and damping policy
 */
struct entasis_uniform_gravity_policy_t {
    /* uniform world-space gravity acceleration */
    entasis_vector3_t gravity;
    /* linear damping coefficient */
    float linear_damping;
    /* angular damping coefficient */
    float angular_damping;
};

/**
 * inverse-square planetary gravity and damping policy
 */
struct entasis_planetary_gravity_policy_t {
    /* center of mass or policy center */
    entasis_vector3_t center;
    /* planetary gravity strength */
    float gravity;
    /* linear damping coefficient */
    float linear_damping;
    /* angular damping coefficient */
    float angular_damping;
};

/**
 * versioned built-in pose policy with no foreign callback pointers
 */
struct entasis_pose_policy_t {
    /* size of this struct in bytes */
    uint32_t struct_size;
    /* version of this struct layout */
    uint32_t struct_version;
    /* active tagged variant */
    entasis_pose_policy_kind_t kind;
    /* angular velocity integration mode used by the pose policy */
    entasis_angular_integration_mode_t angular_mode;
    /* whether unconstrained bodies integrate once per substep */
    entasis_pose_integration_state_t allow_substeps_for_unconstrained;
    /* whether kinematic velocity is integrated into pose */
    entasis_pose_integration_state_t integrate_kinematic_velocity;
    /* reserved for ABI compatibility */
    uint8_t reserved0[4];
    /* policy-specific gravity vector or center */
    entasis_vector3_t vector;
    /* policy-specific gravity strength */
    float gravity;
    /* linear damping coefficient */
    float linear_damping;
    /* angular damping coefficient */
    float angular_damping;
    /* borrowed vector3 array */
    const entasis_vector3_t * gravity_by_body_handle;
    /* number of entries in gravity_by_body_handle */
    uint64_t gravity_count;
    /* reserved for ABI compatibility */
    uint64_t reserved1;
};

/**
 * complete versioned world initialization description
 */
struct entasis_world_description_t {
    /* size of this struct in bytes */
    uint32_t struct_size;
    /* version of this struct layout */
    uint32_t struct_version;
    /* whether per-stage profiling is enabled */
    entasis_bool_t profiling;
    /* whether narrow_policy overrides the default narrow-phase policy */
    entasis_bool_t use_narrow_policy;
    /* whether pose_policy overrides the gravity and damping fields */
    entasis_bool_t use_pose_policy;
    /* reserved for ABI compatibility */
    uint8_t reserved_flags[5];
    /* default world-space gravity acceleration */
    entasis_vector3_t gravity;
    /* default linear and angular damping */
    entasis_damping_t damping;
    /* initial storage capacity hints */
    entasis_capacity_hints_t capacity;
    /* solver iteration and substep settings */
    entasis_solve_description_t solve;
    /* threading and dispatcher settings */
    entasis_threading_description_t threading;
    /* allocator used for facade-owned storage */
    entasis_allocator_t allocator;
    /* built-in narrow-phase policy copied into the world */
    entasis_default_narrow_policy_t narrow_policy;
    /* built-in pose integration policy copied into the world */
    entasis_pose_policy_t pose_policy;
    /* borrowed narrow policy */
    const entasis_narrow_policy_t * narrow_policy_v1;
};

/**
 * returns the default capacity hints
 *
 * @return returns the default capacity hints
 */
ENTASIS_API entasis_capacity_hints_t ENTASIS_CALL entasis_capacity_hints_default(void);

/**
 * returns the built-in solver defaults
 *
 * @return returns the default solve description
 */
ENTASIS_API entasis_solve_description_t ENTASIS_CALL entasis_solve_description_default(void);

/**
 * returns a caller-thread-only threading descriptor
 *
 * @return returns the default threading description
 */
ENTASIS_API entasis_threading_description_t ENTASIS_CALL entasis_threading_description_default(void);

/**
 * returns a complete versioned default world descriptor
 *
 * @return returns the default world description
 */
ENTASIS_API entasis_world_description_t ENTASIS_CALL entasis_world_description_default(void);

/**
 * builds a uniform gravity policy
 *
 * allocation: none
 *
 * @param gravity uniform world-space gravity acceleration
 * @param linear_damping linear damping coefficient applied by the policy
 * @param angular_damping angular damping coefficient applied by the policy
 *
 * @return returns the uniform gravity policy
 */
ENTASIS_API entasis_uniform_gravity_policy_t ENTASIS_CALL entasis_uniform_gravity_policy(entasis_vector3_t gravity, float linear_damping, float angular_damping);

/**
 * builds an inverse-square planetary gravity policy
 *
 * gravity must be nonnegative. damping values use the same [0, 1] contract as uniform_gravity_policy. allocation: none
 *
 * @param center planetary gravity center
 * @param gravity planetary gravity strength
 * @param linear_damping linear damping coefficient applied by the policy
 * @param angular_damping angular damping coefficient applied by the policy
 *
 * @return returns the planetary gravity policy
 */
ENTASIS_API entasis_planetary_gravity_policy_t ENTASIS_CALL entasis_planetary_gravity_policy(entasis_vector3_t center, float gravity, float linear_damping, float angular_damping);

/**
 * builds a dense handle-indexed per-body gravity policy
 *
 * allocation: none
 *
 * @param gravity_by_body_handle dense gravity array indexed by body handle value
 * @param gravity_count number of entries in gravity_by_body_handle
 * @param linear_damping linear damping coefficient applied by the policy
 * @param angular_damping angular damping coefficient applied by the policy
 *
 * @return returns the per body gravity policy
 */
ENTASIS_API entasis_per_body_gravity_policy_t ENTASIS_CALL entasis_per_body_gravity_policy(const entasis_vector3_t * gravity_by_body_handle, uint64_t gravity_count, float linear_damping, float angular_damping);

/**
 * builds the uniform-gravity pose policy
 *
 * no facade callback is inserted in the per-body integration path
 *
 * @param policy uniform gravity policy to copy
 *
 * @return returns the pose policy
 */
ENTASIS_API entasis_pose_policy_t ENTASIS_CALL entasis_pose_policy_uniform(const entasis_uniform_gravity_policy_t * policy);

/**
 * builds a uniform policy with explicit angular integration
 *
 * this is useful for gyroscopes and other bodies whose angular momentum behavior matters. allocation: none
 *
 * @param policy uniform gravity policy to copy
 * @param angular_mode angular velocity integration mode used by the policy
 *
 * @return returns the pose policy
 */
ENTASIS_API entasis_pose_policy_t ENTASIS_CALL entasis_pose_policy_uniform_mode(const entasis_uniform_gravity_policy_t * policy, entasis_angular_integration_mode_t angular_mode);

/**
 * builds the planetary-gravity pose policy
 *
 * the hot integration path remains SIMD and performs no allocation
 *
 * @param policy planetary gravity policy to copy
 *
 * @return returns the pose policy
 */
ENTASIS_API entasis_pose_policy_t ENTASIS_CALL entasis_pose_policy_planetary(const entasis_planetary_gravity_policy_t * policy);

/**
 * builds the dense per-body gravity pose policy
 *
 * reads are direct handle-indexed table lookups and perform no allocation
 *
 * @param policy per body gravity policy to copy
 *
 * @return returns the pose policy
 */
ENTASIS_API entasis_pose_policy_t ENTASIS_CALL entasis_pose_policy_per_body(const entasis_per_body_gravity_policy_t * policy);

/**
 * copies optional built-in policies into a world descriptor
 *
 * copies built-in policy descriptors into the world description. this operation does not register foreign disposal callbacks. use the additive world extensions descriptor for custom velocity/contact callback tables
 *
 * @param description world description to copy
 * @param narrow borrowed default narrow policy
 * @param pose optional pose integration policy, or NULL to use the description fields
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_description_set_callbacks(entasis_world_description_t * description, const entasis_default_narrow_policy_t * narrow, const entasis_pose_policy_t * pose);

/**
 * initializes an opaque caller-owned buffer pool
 *
 * @param pool target buffer pool
 * @param minimum_block_size minimum native block size in bytes
 * @param expected_resource_count expected number of retained resources
 * @param allocator copied allocator callbacks for storage covered by the selected allocation scope. user_context remains borrowed until destruction
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_buffer_pool_init(entasis_buffer_pool_t * pool, int32_t minimum_block_size, int32_t expected_resource_count, const entasis_allocator_t * allocator, entasis_diagnostic_t * diagnostic);

/**
 * initializes an opaque caller-owned buffer pool with explicit Legacy/All_Owned allocation scope. allocator callbacks and user data remain alive through resource destruction
 *
 * @param pool target buffer pool
 * @param minimum_block_size minimum native block size in bytes
 * @param expected_resource_count expected number of retained resources
 * @param allocator copied allocator callbacks for storage covered by the selected allocation scope. user_context remains borrowed until destruction
 * @param allocation_scope Legacy preserves existing behavior. All_Owned includes pool metadata, native blocks and included thread records
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_buffer_pool_init_extended(entasis_buffer_pool_t * pool, int32_t minimum_block_size, int32_t expected_resource_count, const entasis_allocator_t * allocator, entasis_allocation_scope_t allocation_scope, entasis_diagnostic_t * diagnostic);

/**
 * clears an unattached buffer pool while retaining ready metadata
 *
 * @param pool target buffer pool
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_buffer_pool_clear(entasis_buffer_pool_t * pool, entasis_diagnostic_t * diagnostic);

/**
 * destroys an unattached caller-owned buffer pool
 *
 * @param pool target buffer pool
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_buffer_pool_destroy(entasis_buffer_pool_t * pool, entasis_diagnostic_t * diagnostic);

/**
 * initializes the included blocking thread pool
 *
 * @param pool target buffer pool
 * @param worker_count number of participating workers, including the caller when required by the dispatcher contract
 * @param worker_pool_block_size native block size used by each worker buffer pool
 * @param allocator copied allocator callbacks for storage covered by the selected allocation scope. user_context remains borrowed until destruction
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_DISPATCHER_STATUS_OK on success or a dispatcher failure status
 */
ENTASIS_API entasis_dispatcher_status_t ENTASIS_CALL entasis_thread_pool_init(entasis_thread_pool_t * pool, uint32_t worker_count, uint32_t worker_pool_block_size, const entasis_allocator_t * allocator, entasis_diagnostic_t * diagnostic);

/**
 * initializes the included blocking thread pool with explicit Legacy/All_Owned allocation scope. allocator callbacks and user data remain alive through resource destruction
 *
 * @param pool target buffer pool
 * @param worker_count number of participating workers, including the caller when required by the dispatcher contract
 * @param worker_pool_block_size native block size used by each worker buffer pool
 * @param allocator copied allocator callbacks for storage covered by the selected allocation scope. user_context remains borrowed until destruction
 * @param allocation_scope Legacy preserves existing behavior. All_Owned includes pool metadata, native blocks and included thread records
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_DISPATCHER_STATUS_OK on success or a dispatcher failure status
 */
ENTASIS_API entasis_dispatcher_status_t ENTASIS_CALL entasis_thread_pool_init_extended(entasis_thread_pool_t * pool, uint32_t worker_count, uint32_t worker_pool_block_size, const entasis_allocator_t * allocator, entasis_allocation_scope_t allocation_scope, entasis_diagnostic_t * diagnostic);

/**
 * stops and destroys an unattached included thread pool
 *
 * @param pool target buffer pool
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_DISPATCHER_STATUS_OK on success or a dispatcher failure status
 */
ENTASIS_API entasis_dispatcher_status_t ENTASIS_CALL entasis_thread_pool_destroy(entasis_thread_pool_t * pool, entasis_diagnostic_t * diagnostic);

/**
 * builds a dispatcher interface over an included thread pool
 *
 * @param pool target buffer pool
 * @param out_interface receives the dispatcher interface backed by the thread pool
 *
 * @return returns ENTASIS_DISPATCHER_STATUS_OK on success or a dispatcher failure status
 */
ENTASIS_API entasis_dispatcher_status_t ENTASIS_CALL entasis_dispatcher_from_thread_pool(const entasis_thread_pool_t * pool, entasis_dispatcher_interface_t * out_interface);

/**
 * validates the blocking external dispatcher contract
 *
 * @param interface external dispatcher interface
 *
 * @return returns ENTASIS_DISPATCHER_STATUS_OK on success or a dispatcher failure status
 */
ENTASIS_API entasis_dispatcher_status_t ENTASIS_CALL entasis_dispatcher_interface_validate(const entasis_dispatcher_interface_t * interface);

/**
 * initializes one world and its owned resources
 *
 * a dispatcher is also owned when description.threading.worker_count is greater than one and no external dispatcher was supplied
 *
 * @param world target world
 * @param description world description to copy
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_init(entasis_world_t * world, const entasis_world_description_t * description, entasis_diagnostic_t * diagnostic);

/**
 * initializes one world with a caller-owned buffer pool
 *
 * the world returns its buffers during destruction but never disposes the pool
 *
 * @param world target world
 * @param description world description to copy
 * @param pool target buffer pool
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_init_with_pool(entasis_world_t * world, const entasis_world_description_t * description, entasis_buffer_pool_t * pool, entasis_diagnostic_t * diagnostic);

/**
 * clears one world while retaining capacity
 *
 * @param world target world
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_clear(entasis_world_t * world, entasis_diagnostic_t * diagnostic);

/**
 * grows world storage to satisfy capacity hints
 *
 * it never shrinks storage or changes the initialized threading policy
 *
 * @param world target world
 * @param hints requested world storage capacity hints
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_ensure_capacity(entasis_world_t * world, const entasis_capacity_hints_t * hints, entasis_diagnostic_t * diagnostic);

/**
 * resizes retained world storage while preserving live occupancy
 *
 * live counts are always preserved by the low-level resize operation. a target below current occupancy is raised to the required live capacity. this is an owner-thread cold operation and invalidates direct views
 *
 * @param world target world
 * @param hints requested world storage capacity hints
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_resize(entasis_world_t * world, const entasis_capacity_hints_t * hints, entasis_diagnostic_t * diagnostic);

/**
 * advances one timestep without wrapper allocation
 *
 * @param world target world
 * @param dt positive timestep duration in seconds
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_step(entasis_world_t * world, float dt, entasis_diagnostic_t * diagnostic);

/**
 * advances one timestep through a caller-owned blocking dispatcher
 *
 * the interface and all worker pools remain caller owned. the interface is used only for this call and may be stack allocated
 *
 * @param world target world
 * @param dt positive timestep duration in seconds
 * @param interface external dispatcher interface
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_step_external(entasis_world_t * world, float dt, const entasis_dispatcher_interface_t * interface, entasis_diagnostic_t * diagnostic);

/**
 * copies allocation-free world counts and the step index
 *
 * allocation: none. thread safety: owner thread only
 *
 * @param world target world
 * @param out_stats receives the world stats
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_stats(const entasis_world_t * world, entasis_world_stats_t * out_stats, entasis_diagnostic_t * diagnostic);

/**
 * destroys one world and every C-ABI-owned adapter resource
 *
 * it never disposes an external pool or external dispatcher. a destroyed world may be initialized again
 *
 * @param world target world
 * @param diagnostic optional diagnostic output, or NULL when detailed failure data is not needed
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_destroy(entasis_world_t * world, entasis_diagnostic_t * diagnostic);

/**
 * installs one built-in narrow-phase policy in a world description
 *
 * @param description world description to copy
 * @param narrow borrowed narrow policy
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_description_set_narrow_policy(entasis_world_description_t * description, const entasis_narrow_policy_t * narrow);

/**
 * begins an immutable-world read phase
 *
 * owner-thread operation, not a lock. the application must publish jobs only after begin_read and join every reader before end_read. mutation, stepping, registration, capacity changes, import and destruction are rejected during this phase. query contexts require independent outputs and callback user data safe for concurrent reads
 *
 * @param world live world kept at a stable address until every context is destroyed
 * @param diagnostic optional caller-exclusive diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_begin_read(entasis_world_t * world, entasis_diagnostic_t * diagnostic);

/**
 * ends a read phase after the caller joins every read job
 *
 * owner-thread operation, not a lock. the application must publish jobs only after begin_read and join every reader before end_read. mutation, stepping, registration, capacity changes, import and destruction are rejected during this phase. query contexts require independent outputs and callback user data safe for concurrent reads
 *
 * @param world live world kept at a stable address until every context is destroyed
 * @param diagnostic optional caller-exclusive diagnostic output
 *
 * @return returns ENTASIS_STATUS_OK on success or a failure status
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_end_read(entasis_world_t * world, entasis_diagnostic_t * diagnostic);

/**
 * constructs empty optional tables with Legacy allocation scope
 *
 * @return returns an initialized descriptor using the current structure version
 */
ENTASIS_API entasis_world_extensions_t ENTASIS_CALL entasis_world_extensions_default(void);

/**
 * initializes a world with optional custom callbacks and timestep hooks
 *
 * @param world caller-owned world handle initialized to zero
 * @param description existing world configuration and sole allocator authority
 * @param extensions optional copied initialization extensions. NULL preserves the existing behavior
 * @param diagnostic optional output diagnostic
 *
 * @return returns the operation status. completed work is not rolled back on callback failure
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_init_extended(entasis_world_t * world, const entasis_world_description_t * description, const entasis_world_extensions_t * extensions, entasis_diagnostic_t * diagnostic);

/**
 * initializes a world with borrowed storage and optional extensions
 *
 * @param world caller-owned world handle initialized to zero
 * @param description existing world configuration and sole allocator authority
 * @param pool borrowed independently initialized pool, not attached to a query context
 * @param extensions optional copied initialization extensions. NULL preserves the existing behavior
 * @param diagnostic optional output diagnostic
 *
 * @return returns the operation status. completed work is not rolled back on callback failure
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_init_with_pool_extended(entasis_world_t * world, const entasis_world_description_t * description, entasis_buffer_pool_t * pool, const entasis_world_extensions_t * extensions, entasis_diagnostic_t * diagnostic);

/**
 * executes only the sleep stage on an idle world
 *
 * does not increment the completed-step counter or automatically report timestep completion. existing native stage order requirements and view invalidation apply. callback reentry and calls during a read phase are rejected
 *
 * @param world caller-owned initialized world handle
 * @param diagnostic optional output diagnostic
 *
 * @return returns the operation status. completed work is not rolled back on callback failure
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_stage_sleep(entasis_world_t * world, entasis_diagnostic_t * diagnostic);

/**
 * executes the sleep stage within the selected custom timestep
 *
 * uses the current dispatcher without reentering world_step. scope operations cannot execute recursively and do not increment the step counter
 *
 * @param scope current live custom timestep scope
 * @param diagnostic optional output diagnostic
 *
 * @return returns the operation status. completed work is not rolled back on callback failure
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_step_scope_sleep(entasis_step_scope_t scope, entasis_diagnostic_t * diagnostic);

/**
 * executes only the predict bounds stage on an idle world
 *
 * does not increment the completed-step counter or automatically report timestep completion. existing native stage order requirements and view invalidation apply. callback reentry and calls during a read phase are rejected
 *
 * @param world caller-owned initialized world handle
 * @param dt positive duration in seconds
 * @param diagnostic optional output diagnostic
 *
 * @return returns the operation status. completed work is not rolled back on callback failure
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_stage_predict_bounds(entasis_world_t * world, float dt, entasis_diagnostic_t * diagnostic);

/**
 * executes the predict bounds stage within the selected custom timestep
 *
 * uses the current dispatcher without reentering world_step. scope operations cannot execute recursively and do not increment the step counter
 *
 * @param scope current live custom timestep scope
 * @param dt positive duration in seconds
 * @param diagnostic optional output diagnostic
 *
 * @return returns the operation status. completed work is not rolled back on callback failure
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_step_scope_predict_bounds(entasis_step_scope_t scope, float dt, entasis_diagnostic_t * diagnostic);

/**
 * executes only the collision detection stage on an idle world
 *
 * does not increment the completed-step counter or automatically report timestep completion. existing native stage order requirements and view invalidation apply. callback reentry and calls during a read phase are rejected
 *
 * @param world caller-owned initialized world handle
 * @param dt positive duration in seconds
 * @param diagnostic optional output diagnostic
 *
 * @return returns the operation status. completed work is not rolled back on callback failure
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_stage_collision_detection(entasis_world_t * world, float dt, entasis_diagnostic_t * diagnostic);

/**
 * executes the collision detection stage within the selected custom timestep
 *
 * uses the current dispatcher without reentering world_step. scope operations cannot execute recursively and do not increment the step counter
 *
 * @param scope current live custom timestep scope
 * @param dt positive duration in seconds
 * @param diagnostic optional output diagnostic
 *
 * @return returns the operation status. completed work is not rolled back on callback failure
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_step_scope_collision_detection(entasis_step_scope_t scope, float dt, entasis_diagnostic_t * diagnostic);

/**
 * executes only the solve stage on an idle world
 *
 * does not increment the completed-step counter or automatically report timestep completion. existing native stage order requirements and view invalidation apply. callback reentry and calls during a read phase are rejected
 *
 * @param world caller-owned initialized world handle
 * @param dt positive duration in seconds
 * @param diagnostic optional output diagnostic
 *
 * @return returns the operation status. completed work is not rolled back on callback failure
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_stage_solve(entasis_world_t * world, float dt, entasis_diagnostic_t * diagnostic);

/**
 * executes the solve stage within the selected custom timestep
 *
 * uses the current dispatcher without reentering world_step. scope operations cannot execute recursively and do not increment the step counter
 *
 * @param scope current live custom timestep scope
 * @param dt positive duration in seconds
 * @param diagnostic optional output diagnostic
 *
 * @return returns the operation status. completed work is not rolled back on callback failure
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_step_scope_solve(entasis_step_scope_t scope, float dt, entasis_diagnostic_t * diagnostic);

/**
 * executes only the optimize stage on an idle world
 *
 * does not increment the completed-step counter or automatically report timestep completion. existing native stage order requirements and view invalidation apply. callback reentry and calls during a read phase are rejected
 *
 * @param world caller-owned initialized world handle
 * @param diagnostic optional output diagnostic
 *
 * @return returns the operation status. completed work is not rolled back on callback failure
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_world_stage_optimize(entasis_world_t * world, entasis_diagnostic_t * diagnostic);

/**
 * executes the optimize stage within the selected custom timestep
 *
 * uses the current dispatcher without reentering world_step. scope operations cannot execute recursively and do not increment the step counter
 *
 * @param scope current live custom timestep scope
 * @param diagnostic optional output diagnostic
 *
 * @return returns the operation status. completed work is not rolled back on callback failure
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_step_scope_optimize(entasis_step_scope_t scope, entasis_diagnostic_t * diagnostic);

/**
 * reports a completion point chosen by the custom timestepper
 *
 * scope stages do not emit completion hooks implicitly. reports invoke the existing completion callback and profiler stage. callback errors propagate without rollback
 *
 * @param scope current live custom timestep scope
 * @param stage completed stage identifier
 * @param dt positive duration in seconds
 * @param diagnostic optional output diagnostic
 *
 * @return returns the operation status. completed work is not rolled back on callback failure
 */
ENTASIS_API entasis_status_t ENTASIS_CALL entasis_step_scope_report_completion(entasis_step_scope_t scope, entasis_timestep_completion_stage_t stage, float dt, entasis_diagnostic_t * diagnostic);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* ENTASIS_WORLD_H */
